# Évaluation finale : la version finale du machine learning sur le test, lu une seule fois

**But** : vérifier, sur des clients que rien n'a jamais vu, ce que la version finale du machine learning tient vraiment, et présenter le résultat comme la banque l'utiliserait. Le test (`data/ML/test_dataset.csv`, 20 % des clients laissés au ML, découpage de `creation_datasets_ML.ipynb`) n'a servi à **aucun** choix : ni variables, ni réglages, ni seuil, ni modèle. **Il est lu une seule fois, ici.**

**Tout est fixé avant la lecture** (`methodologie_ML.md`, sections 10 et 13) :
- **version finale** : le scénario `SCENARIO_FINAL` (cellule suivante), l'entraînement final `ml_17` ;
- **modèle de décision** : le premier du podium de ce scénario (score décisionnel F2), tel qu'il est enregistré avec son seuil dans `lab_ML/best_models/` : entraîné sur tout le train par la boucle, seuil fixé sur les probabilités hors pli du train pour détecter 60 % des défauts (rappel minimal). Son nom est lu dans le fichier enregistré, jamais choisi ici ;
- **les autres modèles** du scénario sont réentraînés sur le train avec leurs réglages figés et affichés **pour information** : ils ne changent pas la décision ;
- **seuils des autres rappels et bornes des niveaux de risque** : tous calculés sur les probabilités hors pli du **train** (`data/ML/probas_hors_pli/`), jamais sur le test. Les niveaux du modèle sont coupés tous les 10 % des défauts détectés, de 10 % à 60 % (le rappel minimal, seuil de décision) : six tranches, puis les non signalés ;
- **système complet** : deux règles métier d'abord, lues dans le statut à M (`STATUT_INCIDENT`) : les clients **en incident à M** sont en défaut par la règle, ceux en **retard imminent** aussi (la banque a déjà jugé la facture de septembre impayée) ; le modèle juge tous les autres. Le test ne contient aucun client de ces deux populations (retirées avant le découpage) : on lui adjoint un **échantillon de 20 % de chacune des deux populations** du même périmètre (S12 : `BILL_AMT1 > 0`, `LIMIT_BAL <= 500 000`), tiré comme le test (stratifié sur la cible, `random_state=42`), pour garder les proportions du portefeuille. Les règles n'apprennent rien : aucune fuite.

**Ce qu'on attend** : que le test retrouve ce qu'annonce la validation (affichée en regard à la section 2), avec plus d'incertitude (moins de clients).

**Étapes** :
1. chargement du train, du test et du modèle ; garde-fou de lecture unique ;
2. le modèle de décision sur le test, au seuil fixé, avec son incertitude, face à la validation ;
3. précision à plusieurs rappels (seuils du train) ;
4. les autres modèles, pour information ;
5. tableau des niveaux de risque et système complet (règles métier + modèle), face aux règles seules ;
6. le tableau des niveaux de risque sur tout le périmètre du ML.

## 1. Chargement et garde-fou de lecture unique

In [1]:
import joblib
import numpy as np
import pandas as pd
from datetime import datetime
from pathlib import Path
from IPython.display import Markdown, display
from sklearn.metrics import average_precision_score, fbeta_score, precision_score, recall_score, roc_auc_score
from sklearn.model_selection import train_test_split

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 250)

# Version finale : le scénario retenu et la version de la méthode de ses résultats (fixés avant la lecture du test)
SCENARIO_FINAL = "17"
VERSION_METHODE = "v9"

current_dir = Path.cwd()
root_dir = next(p for p in [current_dir] + list(current_dir.parents) if (p / "data").exists())
dossier_ml = root_dir / "data" / "ML"
CHEMIN_TEST = dossier_ml / "test_dataset.csv"
SCENARIO = f"ml_{SCENARIO_FINAL}"

# Le modèle de décision est lu avant le test : son nom vient du fichier enregistré par le scénario (premier du podium)
enregistre = joblib.load(root_dir / "lab_ML" / "best_models" / f"model_{SCENARIO}.joblib")
assert enregistre["scenario"] == SCENARIO
NOM, VARIABLES, SEUIL, RAPPEL_MINIMAL = enregistre["nom"], enregistre["variables"], enregistre["seuil"], enregistre["rappel_minimal"]

# Garde-fou : la date de la première lecture du test est notée ; une relance est signalée (les résultats ne doivent plus rien décider)
trace = dossier_ml / "lecture_test.txt"
if trace.exists():
    display(Markdown(f"⚠️ **Le test a déjà été lu** ({trace.read_text(encoding='utf-8').strip()}). Cette relance ne doit servir qu'à réafficher les résultats, jamais à revoir un choix."))
else:
    trace.write_text(f"Première lecture du test : {datetime.now():%d/%m/%Y %H:%M}, version {SCENARIO}, modèle de décision {NOM}\n", encoding="utf-8")
    display(Markdown(f"Première lecture du test, notée dans `{trace.name}`."))

train = pd.read_csv(dossier_ml / "train_dataset.csv")
test = pd.read_csv(CHEMIN_TEST)
assert not set(train["ID"]) & set(test["ID"]), "Des clients sont à la fois dans le train et le test"
y_test = test["dpnm"].to_numpy()
oof = pd.read_csv(dossier_ml / "probas_hors_pli" / f"{SCENARIO}_{VERSION_METHODE}.csv").set_index("ID").loc[train["ID"]]
y_train = oof["dpnm"].to_numpy()
p_train_oof = oof[NOM].to_numpy()
display(Markdown(f"**Train** : {len(train)} clients, taux de défaut {y_train.mean() * 100:.1f} % ; **test** : {len(test)} clients, "
                 f"taux de défaut {y_test.mean() * 100:.1f} % ; **modèle de décision** : {NOM} de `{SCENARIO}`, {len(VARIABLES)} variables, "
                 f"seuil {SEUIL:.3f} (rappel minimal {RAPPEL_MINIMAL:.0%}, fixé sur le train)"))

Première lecture du test, notée dans `lecture_test.txt`.

**Train** : 17967 clients, taux de défaut 13.8 % ; **test** : 4492 clients, taux de défaut 13.8 % ; **modèle de décision** : CatBoost de `ml_17`, 21 variables, seuil 0.520 (rappel minimal 60%, fixé sur le train)

## 2. Le modèle de décision sur le test, au seuil fixé

Le modèle prédit chaque client du test ; un client est signalé si sa probabilité atteint le seuil fixé sur le train. Les mesures sont données avec un **intervalle à 95 %** (2 000 tirages avec remise des clients du test) : le test compte beaucoup moins de défauts que le train, son incertitude est plus grande que celle de la validation. En regard : ce qu'annonçait la validation (probabilités hors pli du train, même seuil).

In [2]:
def mesures(y, p, seuil):
    s = p >= seuil
    return {"Rappel": recall_score(y, s), "Précision des défauts prédits": precision_score(y, s, zero_division=0),
            "Clients signalés": s.mean(), "Score décisionnel F2": fbeta_score(y, s, beta=2),
            "ROC AUC": roc_auc_score(y, p), "Précision moyenne": average_precision_score(y, p)}

p_test = enregistre["modele"].predict_proba(test[VARIABLES])[:, 1]
sur_test = mesures(y_test, p_test, SEUIL)
en_validation = mesures(y_train, p_train_oof, SEUIL)

generateur = np.random.default_rng(42)
tirages = [mesures(y_test[i], p_test[i], SEUIL) for i in (generateur.integers(0, len(y_test), len(y_test)) for _ in range(2000))]
lignes = []
for nom in sur_test:
    valeurs = np.array([t[nom] for t in tirages])
    pourcent = nom not in ("Score décisionnel F2", "ROC AUC", "Précision moyenne")
    f = (lambda v: f"{v * 100:.1f} %") if pourcent else (lambda v: f"{v:.3f}")
    lignes.append({"Mesure": nom, "Validation (train, hors pli)": f(en_validation[nom]), "Test": f(sur_test[nom]),
                   "Intervalle à 95 % (test)": f"{f(np.percentile(valeurs, 2.5))} – {f(np.percentile(valeurs, 97.5))}"})
display(Markdown(f"**{NOM} de `{SCENARIO}`, au seuil fixé sur le train ({SEUIL:.3f})**"))
display(pd.DataFrame(lignes).set_index("Mesure"))

s = p_test >= SEUIL
display(Markdown(f"**Sur le test** : {s.sum()} clients signalés, dont {(s & (y_test == 1)).sum()} défauts détectés sur {y_test.sum()} "
                 f"et {(s & (y_test == 0)).sum()} fausses alertes ; {(~s & (y_test == 1)).sum()} défauts manqués."))

**CatBoost de `ml_17`, au seuil fixé sur le train (0.520)**

                              Validation (train, hors pli)    Test Intervalle à 95 % (test)
Mesure
Rappel                                              60.0 %  55.8 %          51.9 % – 59.8 %
Précision des défauts prédits                       22.6 %  21.9 %          19.9 % – 24.0 %
Clients signalés                                    36.7 %  35.2 %          33.7 % – 36.6 %
Score décisionnel F2                                 0.451   0.426            0.396 – 0.455
ROC AUC                                              0.690   0.675            0.652 – 0.697
Précision moyenne                                    0.262   0.277            0.246 – 0.313

**Sur le test** : 1579 clients signalés, dont 346 défauts détectés sur 620 et 1233 fausses alertes ; 274 défauts manqués.

**Comment lire** : si les mesures du test tombent dans leur intervalle et près de la validation, le modèle tient sur des clients jamais vus : le plafond mesuré en validation est bien celui des données. Un rappel un peu différent de 60 % est normal : le seuil vient du train, le test a ses propres clients.

## 3. Précision à plusieurs rappels (seuils fixés sur le train)

Pour chaque rappel visé, le seuil est celui qui atteint ce rappel sur les probabilités hors pli du **train** ; il est appliqué tel quel au test. Le rappel de 44 % est le repère de la première itération (précision de 38,5 % sur son test, sur la population laissée au ML) : comparaison indicative, les découpages et les populations n'étant pas les mêmes.

In [3]:
def seuil_pour_rappel(y, p, rappel):
    proba_defauts = np.sort(p[y == 1])[::-1]
    return proba_defauts[int(np.ceil(rappel * len(proba_defauts))) - 1]

lignes = []
for r in (0.10, 0.20, 0.30, 0.40, 0.44, 0.50, 0.60, 0.70, 0.80):
    seuil = seuil_pour_rappel(y_train, p_train_oof, r)
    v, t = mesures(y_train, p_train_oof, seuil), mesures(y_test, p_test, seuil)
    lignes.append({"Rappel visé (seuil du train)": f"{r:.0%}" + (" (1re itération)" if r == 0.44 else " (rappel minimal)" if r == RAPPEL_MINIMAL else ""),
                   "Seuil": round(seuil, 3), "Rappel sur le test (%)": round(t["Rappel"] * 100, 1),
                   "Précision en validation (%)": round(v["Précision des défauts prédits"] * 100, 1),
                   "Précision sur le test (%)": round(t["Précision des défauts prédits"] * 100, 1),
                   "Clients signalés sur le test (%)": round(t["Clients signalés"] * 100, 1)})
display(pd.DataFrame(lignes).set_index("Rappel visé (seuil du train)"))

                              Seuil  Rappel sur le test (%)  Précision en validation (%)  Précision sur le test (%)  Clients signalés sur le test (%)
Rappel visé (seuil du train)
10%                           0.744                    12.4                         40.4                       46.1                               3.7
20%                           0.668                    21.5                         34.1                       39.2                               7.5
30%                           0.616                    31.8                         29.0                       32.5                              13.5
40%                           0.580                    40.3                         26.3                       27.6                              20.2
44% (1re itération)           0.569                    42.9                         25.5                       26.0                              22.8
50%                           0.550                    48.1                         24.2                       24.1                              27.5
60% (rappel minimal)          0.520                    55.8                         22.6                       21.9                              35.2
70%                           0.480                    65.8                         20.6                       19.6                              46.3
80%                           0.430                    75.8                         19.0                       18.0                              58.2

## 4. Les autres modèles du scénario, pour information

Les autres modèles de la version finale, réentraînés sur tout le train avec les réglages retenus par la boucle (relus dans le fichier de résultats, `data/ML/resultats_scenarios.csv`). Ils reçoivent **exactement la même préparation des colonnes** que le modèle de décision (une copie vierge de celle du modèle enregistré) et les mêmes réglages de base que dans le scénario. Le seuil de chacun est fixé sur ses probabilités hors pli du train, au rappel minimal. **Ces lignes ne changent pas la décision** (fixée avant la lecture) : elles montrent si le classement de la validation se retrouve sur le test.

In [4]:
import ast
from catboost import CatBoostClassifier
from sklearn.base import clone
from sklearn.calibration import CalibratedClassifierCV
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import make_pipeline
from sklearn.svm import SVC

def lire_reglage(texte):
    # « C 0.01 ; gamma auto » -> {"C": 0.01, "gamma": "auto"}
    reglage = {}
    if pd.isna(texte):
        return reglage
    for morceau in texte.split(" ; "):
        nom, valeur = morceau.split(" ", 1)
        try:
            reglage[nom] = ast.literal_eval(valeur)
        except (ValueError, SyntaxError):
            reglage[nom] = valeur
    return reglage

def appliquer_reglage(pipeline, reglage):
    # Chaque réglage est donné par son nom court : on retrouve son nom complet dans le modèle (ex. calibratedclassifiercv__estimator__C),
    # jamais dans la préparation des colonnes (première étape du pipeline). CatBoost ne déclare que les réglages qu'on lui a passés :
    # un réglage qu'on ne trouve pas va au modèle lui-même (dernière étape), qui refuse un nom inconnu
    preparation, dernier = pipeline.steps[0][0], pipeline.steps[-1][0]
    noms = [n for n in pipeline.get_params() if "__" in n and not n.startswith(preparation + "__")]
    complets = {}
    for court, valeur in reglage.items():
        candidats = [n for n in noms if n.split("__")[-1] == court]
        assert len(candidats) <= 1, f"Réglage {court} ambigu : {candidats}"
        complets[candidats[0] if candidats else f"{dernier}__{court}"] = valeur
    return pipeline.set_params(**complets)

# Mêmes modèles de base que dans le scénario (fonction modeles_de_base), autour d'une copie vierge de la préparation du modèle enregistré
scale_pos = (y_train == 0).sum() / (y_train == 1).sum()
ESTIMATEURS = {
    "LogisticRegression": lambda: LogisticRegression(solver="saga", max_iter=5000, class_weight="balanced", random_state=42),
    "SVM": lambda: CalibratedClassifierCV(estimator=SVC(class_weight="balanced", random_state=42), ensemble=False),
    "MLPClassifier": lambda: MLPClassifier(hidden_layer_sizes=(50, 25), max_iter=500, random_state=42, early_stopping=True),
    "KNN": lambda: KNeighborsClassifier(n_neighbors=5, n_jobs=-1),
    "CatBoost": lambda: CatBoostClassifier(scale_pos_weight=scale_pos, random_state=42, verbose=0, thread_count=-1, allow_writing_files=False),
}

def ligne_modele(nom, reglage, v, t):
    return {"Modèle": nom, "Réglage": reglage, "F2 validation": round(v["Score décisionnel F2"], 3), "F2 test": round(t["Score décisionnel F2"], 3),
            "Rappel test (%)": round(t["Rappel"] * 100, 1), "Précision test (%)": round(t["Précision des défauts prédits"] * 100, 1),
            "ROC AUC test": round(t["ROC AUC"], 3)}

resultats = pd.read_csv(dossier_ml / "resultats_scenarios.csv")
lignes_scenario = resultats[(resultats["scenario"] == SCENARIO) & (resultats["version_methode"] == VERSION_METHODE)].set_index("modele")
assert NOM in lignes_scenario.index, f"{NOM} absent des résultats de {SCENARIO}"
preparation = enregistre["modele"][0]
lignes = [ligne_modele(f"{NOM} (décision)", lignes_scenario.loc[NOM, "reglage"], en_validation, sur_test)]
for nom in [m for m in lignes_scenario.index if m != NOM]:
    assert nom in ESTIMATEURS, f"Modèle {nom} inconnu de cette cellule"
    modele = appliquer_reglage(make_pipeline(clone(preparation), ESTIMATEURS[nom]()), lire_reglage(lignes_scenario.loc[nom, "reglage"]))
    modele.fit(train[VARIABLES], train["dpnm"])
    seuil = seuil_pour_rappel(y_train, oof[nom].to_numpy(), RAPPEL_MINIMAL)
    lignes.append(ligne_modele(nom, lignes_scenario.loc[nom, "reglage"], mesures(y_train, oof[nom].to_numpy(), seuil),
                               mesures(y_test, modele.predict_proba(test[VARIABLES])[:, 1], seuil)))
display(pd.DataFrame(lignes).set_index("Modèle"))

                                                               Réglage  F2 validation  F2 test  Rappel test (%)  Précision test (%)  ROC AUC test
Modèle
CatBoost (décision)  depth 2 ; iterations 500 ; l2_leaf_reg 30 ; le...          0.451    0.426             55.8                21.9         0.675
LogisticRegression                               C 0.01 ; l1_ratio 1.0          0.448    0.434             56.9                22.2         0.668
SVM                                                 C 0.1 ; gamma 0.01          0.444    0.429             57.3                21.4         0.667
MLPClassifier                 alpha 1.0 ; hidden_layer_sizes (128, 64)          0.442    0.413             52.3                22.4         0.667
KNN                            n_neighbors 201 ; p 2 ; weights uniform          0.444    0.441             61.0                20.9         0.670

## 5. Tableau des niveaux de risque et système complet

**Niveaux de risque**, du plus risqué au moins risqué (bornes fixées sur le train, probabilités hors pli du modèle de décision) :
- **en incident (règle)** : client en incident à M, en défaut par la règle ;
- **retard imminent (règle)** : client en retard imminent, en défaut par la règle ;
- **six tranches du modèle**, de 10 % des défauts du train chacune : la tranche 1 va jusqu'au seuil qui détecte 10 % des défauts (la tête de liste), la tranche 2 de 10 % à 20 %, et ainsi de suite jusqu'à la tranche 6, de 50 % au rappel minimal (60 %, seuil de décision) ;
- **non signalés** : en dessous du seuil de décision.

Pour chaque niveau, sur le test complété des échantillons des deux règles : nombre de clients, défauts, taux de défaut (la précision si on signale ce niveau) et part de tous les défauts. Puis le **système complet** (règles + modèle au rappel minimal), face aux **règles seules** : défauts détectés, précision, clients signalés. La banque choisit jusqu'à quel niveau elle signale, selon le coût qu'elle donne à une fausse alerte. Les bornes des démos (`creation_demo_ML.ipynb`, `bornes_niveaux.json`) sont prises parmi celles-ci : leurs niveaux se lisent en regroupant des tranches.

In [5]:
# Échantillons des deux règles métier, dans le même périmètre (S12), tirés comme le test : 20 % de chacune, stratifié sur la cible, graine 42
cleaned3 = pd.read_csv(root_dir / "data" / "cleaned3_creditcard.csv")
perimetre = cleaned3[(cleaned3["BILL_AMT1"] > 0) & (cleaned3["LIMIT_BAL"] <= 500000)]
REGLES = {"En incident": "1. En incident (règle)", "Retard imminent": "2. Retard imminent (règle)"}
populations, echantillons = {}, {}
for statut in REGLES:
    populations[statut] = perimetre[perimetre["STATUT_INCIDENT"] == statut]
    _, echantillons[statut] = train_test_split(populations[statut], test_size=0.2, stratify=populations[statut]["dpnm"], random_state=42)
    assert not set(echantillons[statut]["ID"]) & set(test["ID"]), f"Des clients « {statut} » sont dans le test"
assert not test["STATUT_INCIDENT"].isin(list(REGLES)).any(), "Le test contient des clients des règles métier"

# Bornes des tranches du modèle : tous les 10 % des défauts du train, jusqu'au rappel minimal (dernière borne = seuil de décision enregistré)
RAPPELS_BORNES = [0.10, 0.20, 0.30, 0.40, 0.50, RAPPEL_MINIMAL]
bornes = {r: seuil_pour_rappel(y_train, p_train_oof, r) for r in RAPPELS_BORNES}
assert np.isclose(bornes[RAPPEL_MINIMAL], SEUIL), "La dernière borne doit être le seuil de décision enregistré"
bornes[RAPPEL_MINIMAL] = SEUIL
assert all(bornes[a] > bornes[b] for a, b in zip(RAPPELS_BORNES, RAPPELS_BORNES[1:])), "Bornes non décroissantes"
NOMS_TRANCHES = [f"{i + 3}. Tranche {i + 1} ({0 if i == 0 else round(RAPPELS_BORNES[i - 1] * 100)} à {round(r * 100)} % des défauts)"
                 for i, r in enumerate(RAPPELS_BORNES)]
NON_SIGNALES = f"{len(RAPPELS_BORNES) + 3}. Non signalés"
texte_bornes = " ; ".join(f"{round(r * 100)} % dès {s:.3f}" for r, s in bornes.items())

def niveau_modele(p):
    return np.select([p >= bornes[r] for r in RAPPELS_BORNES], NOMS_TRANCHES, NON_SIGNALES)

def tableau_niveaux(d):
    t = d.groupby("niveau")["dpnm"].agg(Clients="size", Défauts="sum")
    t["Précision du niveau seul (taux de défaut, %)"] = (t["Défauts"] / t["Clients"] * 100).round(1)
    t["Part de tous les défauts (%)"] = (t["Défauts"] / t["Défauts"].sum() * 100).round(1)
    t["Défauts cumulés (%)"] = (t["Défauts"].cumsum() / t["Défauts"].sum() * 100).round(1)   # cumul des effectifs, arrondi à la fin
    t["Précision cumulée (%)"] = (t["Défauts"].cumsum() / t["Clients"].cumsum() * 100).round(1)
    return t

portefeuille = pd.concat([pd.DataFrame({"niveau": REGLES[statut], "dpnm": echantillons[statut]["dpnm"].to_numpy()}) for statut in REGLES]
                         + [pd.DataFrame({"niveau": niveau_modele(p_test), "dpnm": y_test})], ignore_index=True)
display(Markdown(f"**Tableau des niveaux de risque** (test : {len(test)} clients ; échantillons des règles : {len(echantillons['En incident'])} en incident à M, "
                 f"{len(echantillons['Retard imminent'])} en retard imminent ; bornes du train, part des défauts détectés : {texte_bornes})"))
display(tableau_niveaux(portefeuille))

# Stratégies : on signale tous les niveaux jusqu'à un niveau donné (les numéros des niveaux donnent leur ordre)
y_tout = portefeuille["dpnm"].to_numpy()
def jusqua(dernier):
    return (portefeuille["niveau"] <= dernier).to_numpy()
strategies = {"Règles seules (en incident et retard imminent en défaut)": jusqua("2. Retard imminent (règle)")}
for r, tranche in zip(RAPPELS_BORNES, NOMS_TRANCHES):
    nom = f"Règles + modèle jusqu'à {round(r * 100)} % des défauts"
    strategies[nom + (" (système complet, rappel minimal)" if r == RAPPEL_MINIMAL else "")] = jusqua(tranche)
lignes = []
for nom, s in strategies.items():
    lignes.append({"Stratégie": nom, "Défauts détectés": (s & (y_tout == 1)).sum(), "Part des défauts (%)": round((s & (y_tout == 1)).sum() / y_tout.sum() * 100, 1),
                   "Clients signalés": s.sum(), "Part des clients signalés (%)": round(s.mean() * 100, 1),
                   "Précision des défauts prédits (%)": round((s & (y_tout == 1)).sum() / s.sum() * 100, 1), "Fausses alertes": (s & (y_tout == 0)).sum()})
display(Markdown(f"**Système complet face aux règles seules** ({len(portefeuille)} clients, {y_tout.sum()} défauts, taux de défaut {y_tout.mean() * 100:.1f} %)"))
display(pd.DataFrame(lignes).set_index("Stratégie"))

**Tableau des niveaux de risque** (test : 4492 clients ; échantillons des règles : 751 en incident à M, 198 en retard imminent ; bornes du train, part des défauts détectés : 10 % dès 0.744 ; 20 % dès 0.668 ; 30 % dès 0.616 ; 40 % dès 0.580 ; 50 % dès 0.550 ; 60 % dès 0.520)

                                      Clients  Défauts  Précision du niveau seul (taux de défaut, %)  Part de tous les défauts (%)  Défauts cumulés (%)  Précision cumulée (%)
niveau
1. En incident (règle)                    751      445                                          59.3                          37.2                 37.2                   59.3
2. Retard imminent (règle)                198      130                                          65.7                          10.9                 48.1                   60.6
3. Tranche 1 (0 à 10 % des défauts)       167       77                                          46.1                           6.4                 54.6                   58.4
4. Tranche 2 (10 à 20 % des défauts)      172       56                                          32.6                           4.7                 59.2                   55.0
5. Tranche 3 (20 à 30 % des défauts)      267       64                                          24.0                           5.4                 64.6                   49.6
6. Tranche 4 (30 à 40 % des défauts)      300       53                                          17.7                           4.4                 69.0                   44.5
7. Tranche 5 (40 à 50 % des défauts)      328       48                                          14.6                           4.0                 73.1                   40.0
8. Tranche 6 (50 à 60 % des défauts)      345       48                                          13.9                           4.0                 77.1                   36.4
9. Non signalés                          2913      274                                           9.4                          22.9                100.0                   22.0

**Système complet face aux règles seules** (5441 clients, 1195 défauts, taux de défaut 22.0 %)

                                                    Défauts détectés  Part des défauts (%)  Clients signalés  Part des clients signalés (%)  Précision des défauts prédits (%)  Fausses alertes
Stratégie
Règles seules (en incident et retard imminent e...               575                  48.1               949                           17.4                               60.6              374
Règles + modèle jusqu'à 10 % des défauts                         652                  54.6              1116                           20.5                               58.4              464
Règles + modèle jusqu'à 20 % des défauts                         708                  59.2              1288                           23.7                               55.0              580
Règles + modèle jusqu'à 30 % des défauts                         772                  64.6              1555                           28.6                               49.6              783
Règles + modèle jusqu'à 40 % des défauts                         825                  69.0              1855                           34.1                               44.5             1030
Règles + modèle jusqu'à 50 % des défauts                         873                  73.1              2183                           40.1                               40.0             1310
Règles + modèle jusqu'à 60 % des défauts (systè...               921                  77.1              2528                           46.5                               36.4             1607

**Comment lire** :
- **Niveaux de risque** : les deux règles métier ouvrent le tableau ; puis viennent les tranches du modèle, de la tête de liste aux non signalés. Chaque niveau ajouté va chercher plus de défauts, mais coûte plus de bons clients signalés par défaut attrapé : c'est à la banque de dire où elle s'arrête.
- **Système complet** : ce que le modèle ajoute aux règles métier, en défauts détectés et en fausses alertes.
- La conclusion s'écrit après lecture, sans revenir sur aucun choix : le test a parlé une fois.

## 6. Le tableau des niveaux de risque sur tout le périmètre du ML

Le test seul est petit (et ne contient qu'un échantillon des deux règles). Pour un tableau **représentatif du portefeuille**, chaque client du périmètre est classé **sans avoir été vu par le modèle qui le classe** :
- **en incident à M et retard imminent** : les deux populations entières du périmètre (et non plus un échantillon), en défaut par la règle ;
- **train** : probabilités **hors pli** du scénario final (chaque client prédit par un modèle entraîné sur les 4 autres plis) ;
- **test** : probabilités du modèle de décision, entraîné sur le train.

Mêmes bornes qu'en section 5 (tous les 10 % des défauts, jusqu'à 60 %, fixées sur le train). **Rôle de chaque tableau** : celui du test (section 5) reste la seule mesure sur des clients jamais vus ; celui-ci décrit le portefeuille entier. Petite réserve : les bornes ont été fixées sur les probabilités du train, qui font partie de ce tableau. La note de risque de chaque client est enregistrée dans `data/ML/comparatif_global/` (fichier `<scénario>_global.csv`), pour les comparaisons à venir.

In [6]:
# Tout le périmètre du ML : les deux règles (populations entières), train (hors pli), test (modèle de décision)
note = pd.concat(
    [pd.DataFrame({"ID": populations[statut]["ID"].to_numpy(), "dpnm": populations[statut]["dpnm"].to_numpy(),
                   "source": f"{statut.lower()} (règle)", "proba": np.nan, "niveau": REGLES[statut]}) for statut in REGLES]
    + [pd.DataFrame({"ID": train["ID"].to_numpy(), "dpnm": y_train, "source": "train (hors pli)", "proba": p_train_oof, "niveau": niveau_modele(p_train_oof)}),
       pd.DataFrame({"ID": test["ID"].to_numpy(), "dpnm": y_test, "source": "test (modèle de décision)", "proba": p_test, "niveau": niveau_modele(p_test)})],
    ignore_index=True)
assert note["ID"].is_unique, "Un client est classé deux fois"

display(Markdown(f"**Tableau des niveaux de risque, tout le périmètre du ML** ({len(note)} clients, {note['dpnm'].sum()} défauts, "
                 f"taux de défaut {note['dpnm'].mean() * 100:.1f} % ; bornes du train, part des défauts détectés : {texte_bornes})"))
display(tableau_niveaux(note))
display(Markdown("**Contrôle : le même tableau, train (hors pli) et test séparés** (sans les deux règles)"))
display(pd.concat({s: tableau_niveaux(note[note["source"] == s]) for s in ("train (hors pli)", "test (modèle de décision)")}, names=["Clients"]))

dossier_sortie = dossier_ml / "comparatif_global"
dossier_sortie.mkdir(parents=True, exist_ok=True)
note.to_csv(dossier_sortie / f"{SCENARIO}_global.csv", index=False)
print(f"Notes enregistrées : {dossier_sortie / f'{SCENARIO}_global.csv'}")

**Tableau des niveaux de risque, tout le périmètre du ML** (27202 clients, 5972 défauts, taux de défaut 22.0 % ; bornes du train, part des défauts détectés : 10 % dès 0.744 ; 20 % dès 0.668 ; 30 % dès 0.616 ; 40 % dès 0.580 ; 50 % dès 0.550 ; 60 % dès 0.520)

                                      Clients  Défauts  Précision du niveau seul (taux de défaut, %)  Part de tous les défauts (%)  Défauts cumulés (%)  Précision cumulée (%)
niveau
1. En incident (règle)                   3754     2222                                          59.2                          37.2                 37.2                   59.2
2. Retard imminent (règle)                989      649                                          65.6                          10.9                 48.1                   60.5
3. Tranche 1 (0 à 10 % des défauts)       783      326                                          41.6                           5.5                 53.5                   57.9
4. Tranche 2 (10 à 20 % des défauts)     1015      304                                          30.0                           5.1                 58.6                   53.5
5. Tranche 3 (20 à 30 % des défauts)     1381      312                                          22.6                           5.2                 63.8                   48.1
6. Tranche 4 (30 à 40 % des défauts)     1501      301                                          20.1                           5.0                 68.9                   43.7
7. Tranche 5 (40 à 50 % des défauts)     1684      296                                          17.6                           5.0                 73.8                   39.7
8. Tranche 6 (50 à 60 % des défauts)     1811      296                                          16.3                           5.0                 78.8                   36.4
9. Non signalés                         14284     1266                                           8.9                          21.2                100.0                   22.0

**Contrôle : le même tableau, train (hors pli) et test séparés** (sans les deux règles)

                                                                Clients  Défauts  Précision du niveau seul (taux de défaut, %)  Part de tous les défauts (%)  Défauts cumulés (%)  Précision cumulée (%)
Clients                   niveau
train (hors pli)          3. Tranche 1 (0 à 10 % des défauts)       616      249                                          40.4                          10.0                 10.0                   40.4
                          4. Tranche 2 (10 à 20 % des défauts)      843      248                                          29.4                          10.0                 20.0                   34.1
                          5. Tranche 3 (20 à 30 % des défauts)     1114      248                                          22.3                          10.0                 30.0                   29.0
                          6. Tranche 4 (30 à 40 % des défauts)     1201      248                                          20.6                          10.0                 40.0                   26.3
                          7. Tranche 5 (40 à 50 % des défauts)     1356      248                                          18.3                          10.0                 50.0                   24.2
                          8. Tranche 6 (50 à 60 % des défauts)     1466      248                                          16.9                          10.0                 60.0                   22.6
                          9. Non signalés                         11371      992                                           8.7                          40.0                100.0                   13.8
test (modèle de décision) 3. Tranche 1 (0 à 10 % des défauts)       167       77                                          46.1                          12.4                 12.4                   46.1
                          4. Tranche 2 (10 à 20 % des défauts)      172       56                                          32.6                           9.0                 21.5                   39.2
                          5. Tranche 3 (20 à 30 % des défauts)      267       64                                          24.0                          10.3                 31.8                   32.5
                          6. Tranche 4 (30 à 40 % des défauts)      300       53                                          17.7                           8.5                 40.3                   27.6
                          7. Tranche 5 (40 à 50 % des défauts)      328       48                                          14.6                           7.7                 48.1                   24.1
                          8. Tranche 6 (50 à 60 % des défauts)      345       48                                          13.9                           7.7                 55.8                   21.9
                          9. Non signalés                          2913      274                                           9.4                          44.2                100.0                   13.8

Notes enregistrées : c:\Users\johan\VS Code Wild 2\PROJET_DEFAULT_CREDIT_CARD_ML\data\ML\comparatif_global\ml_17_global.csv

## 7. Conclusion : ce que la version finale tient sur des clients jamais vus

test vérifié  
baisse des performances constaté mais acceptable  
modèle catboost validé