# Essai : le jeu corrigé (niveau 3) séparé par la règle métier (population en incident, retard imminent) et les autres clients, puis résultats accumulés

**Question** : vaut-il mieux un seul modèle sur tous les clients, ou séparer les populations de la règle métier du reste ? Et une fois les résultats des populations **accumulés sur l'ensemble des clients**, combien de défauts récupère-t-on en tout, et avec quelle précision ? À comparer à l'étude d'origine (Yeh et Lien, 2009) et à la règle métier qui place **toute la population en incident à M et tout le retard imminent en défaut**.

**Données** : `data/cleaned3_creditcard.csv` (niveau 3 du nettoyage, le plus haut niveau de corrections), dont seules les **23 colonnes d'origine** sont des variables ; le statut à M (`STATUT_INCIDENT`) sert seulement à séparer trois populations, jamais mêlées :
- **en incident à M** : `STATUT_INCIDENT` = « En incident » ;
- **retard imminent** : `STATUT_INCIDENT` = « Retard imminent » ;
- **autres clients** : tous les autres statuts (« Sorti de l'incident », « Retard régularisé », « Jamais en retard »).

**Méthode, pour chaque population** : exactement celle de `essai_jeu_corrige.ipynb` (même code, repris tel quel) : trois variantes (complet, `PAY_n` seuls, sans les `PAY_n`), 4 modèles, boucle de GridSearch sur la précision moyenne avec un seuil de surapprentissage de 7 %, seuil de décision par la **règle marginale** (`TunedThresholdClassifierCV`), validation croisée stratifiée à 5 plis, `random_state=42`, importance par permutation par famille de colonnes.

**Tolérance de la règle marginale, par population** (fixée par le métier, pas par les données ni par le taux de défaut) :
- **autres clients** : au plus **1 bon client signalé pour 1 défaut attrapé**, à la marge (un client est signalé s'il a au moins une chance sur deux d'être en défaut) ;
- **en incident à M et retard imminent**, la décision est de **sortir** un client de la règle, et sortir à tort un client qui ne paiera pas est très grave (on abandonne une créance) : on ne sort un client que s'il a **au moins 9 chances sur 10 d'être sain**, à la marge (au plus 1 défaillant sorti pour 9 sains libérés). Côté défaut, un client reste dans la règle dès 10 % de risque.

Si le modèle ne sort personne d'une population de la règle, c'est qu'il ne peut pas trancher à ce niveau d'exigence : la règle (toute la population en défaut) reste alors la bonne décision.

**Synthèse globale, sur tous les clients du niveau 3** (section 6) : chaque client reçoit la décision de sa population (hors pli : prédit par un modèle qui ne l'a pas vu). Stratégies comparées, avec le **meilleur modèle de la variante complète** de chaque population (règle fixée avant : la plus haute précision moyenne hors pli, qui ne dépend d'aucun seuil) :
1. **règle seule** : la population en incident et le retard imminent en défaut, personne d'autre ;
2. **règle + ML autres clients** : la règle, et le modèle pour les autres clients ;
3. **règle + ML autres clients sans les `PAY_n`** : la même, avec un modèle qui ne voit que les montants (le comportement), pas les codifications ;
4. **trois ML** : un modèle pour la population en incident, un pour le retard imminent, un pour les autres clients ;
5. **un seul ML** sur tous les clients (`essai_jeu_corrige.ipynb`, lu dans le fichier qu'il enregistre, s'il a été lancé avec sa cellule d'enregistrement).

Pour chacune : défauts détectés (nombre et part de tous les défauts), clients signalés, précision, fausses alertes, taux d'erreur, et ratio d'aire (mesure de Yeh et Lien : qualité du tri, sans seuil).

⚠️ **Le test du ML est inclus** dans ces clients : aucune conclusion de cet essai ne sert à choisir le modèle final ; elle éclaire la problématique et la place de la règle métier. **Ce n'est pas un scénario** : rien n'est écrit dans le fichier de résultats ni dans le journal, aucun modèle n'est enregistré ; les décisions, client par client, sont enregistrées dans `data/ML/comparatif_global/jeu_corrige_deux_populations.csv`.

**Étapes** :
1. chargement et séparation des trois populations ;
2. pipeline, critère et boucle (repris de `essai_jeu_corrige.ipynb`) ;
3. boucle d'optimisation, puis seuil optimisé, pour chaque population et chaque variante ;
4. ce qui porte les prédictions, dans chaque population (importance par famille) ;
5. comparaison unitaire : le modèle des autres clients face aux scénarios (`ml_4`, `ml_17`), sur les mêmes clients ;
6. synthèse globale : résultats accumulés sur tous les clients, face à la règle seule, à un seul ML et à l'étude d'origine.

In [6]:
import numpy as np
import pandas as pd
from pathlib import Path

current_dir = Path.cwd()
root_dir = next(p for p in [current_dir] + list(current_dir.parents) if (p / "data").exists())

COLONNES_ORIGINE = ["LIMIT_BAL", "SEX", "EDUCATION", "MARRIAGE", "AGE"] + [f"PAY_{n}" for n in range(1, 7)] \
    + [f"BILL_AMT{n}" for n in range(1, 7)] + [f"PAY_AMT{n}" for n in range(1, 7)]
niveau_3 = pd.read_csv(root_dir / "data" / "cleaned3_creditcard.csv")
assert niveau_3["ID"].is_unique and not niveau_3[COLONNES_ORIGINE + ["dpnm", "STATUT_INCIDENT"]].isna().any().any()
# Trois populations, jamais mêlées, lues dans le statut à M (niveau 3 du nettoyage) : les deux de la règle métier (en incident à M, retard imminent) et les autres clients
STATUTS_REGLE = {"En incident": "En incident", "Retard imminent": "Retard imminent"}   # population -> statut
statut = niveau_3["STATUT_INCIDENT"]
MASQUES = {population: (statut == s).to_numpy() for population, s in STATUTS_REGLE.items()}
MASQUES["Autres clients"] = ~statut.isin(STATUTS_REGLE.values()).to_numpy()
regle = ~MASQUES["Autres clients"]   # client déclaré en défaut par la règle métier (en incident à M ou retard imminent)
POPULATIONS = {population: niveau_3[masque][["ID"] + COLONNES_ORIGINE + ["dpnm"]].reset_index(drop=True) for population, masque in MASQUES.items()}
# Tolérance de la règle marginale, par population (fixée par le métier) : bons clients signalés acceptés, à la marge, par défaut attrapé.
# Populations de la règle : on n'en sort un client que s'il a au moins 9 chances sur 10 d'être sain (1 défaillant sorti pour 9 sains libérés, à la marge)
TOLERANCE = {"En incident": 1 / 9, "Retard imminent": 1 / 9, "Autres clients": 1}
for nom, d in POPULATIONS.items():
    print(f"{nom} : {len(d)} clients, {d['dpnm'].sum()} défauts ({d['dpnm'].mean() * 100:.1f} %) ; "
          f"signalé en défaut dès {TOLERANCE[nom] / (1 + TOLERANCE[nom]):.0%} de risque à la marge")
print(f"Ensemble : {len(niveau_3)} clients, {niveau_3['dpnm'].sum()} défauts ({niveau_3['dpnm'].mean() * 100:.1f} %)")

# Population active : les cellules reprises de essai_jeu_corrige.ipynb travaillent sur « original » et « y_train » (ici, l'ensemble, pour les définitions)
original = niveau_3[["ID"] + COLONNES_ORIGINE + ["dpnm"]].reset_index(drop=True)
y_train = original["dpnm"].reset_index(drop=True)

En incident : 3754 clients, 2222 défauts (59.2 %) ; signalé en défaut dès 10% de risque à la marge
Retard imminent : 989 clients, 649 défauts (65.6 %) ; signalé en défaut dès 10% de risque à la marge
Autres clients : 24108 clients, 3401 défauts (14.1 %) ; signalé en défaut dès 50% de risque à la marge
Ensemble : 28851 clients, 6272 défauts (21.7 %)

## 2. Variantes, pipeline, critère et boucle : repris de `essai_jeu_corrige.ipynb`

In [7]:
# ==============================================================================
# VARIABLES : les 23 variables d'origine, rangées selon leur encodage (celui des scénarios, méthode v8)
# ==============================================================================
PAY = [f"PAY_{n}" for n in range(1, 7)]

# PAY_n : nombres ordonnés (-2 à 8), mis à l'échelle (v6)
# PAY_AMTn : paiements très étirés, logarithme (v7)
# BILL_AMTn : factures, logarithme signé, car elles peuvent être négatives (v8)
# SEX, EDUCATION, MARRIAGE : catégories sans ordre, une colonne par catégorie (regroupées dès le niveau 0)
TYPES_ORIGINE = {
    "num": ["AGE"],
    "log": [f"PAY_AMT{n}" for n in range(1, 7)]+["LIMIT_BAL"],
    "log_signe": [f"BILL_AMT{n}" for n in range(1, 7)],
    "cat": ["SEX", "EDUCATION", "MARRIAGE"] + PAY,
}

# Les trois variantes : colonnes gardées, chacune avec son encodage d'origine
VARIANTES = {
    "Complet": lambda c: True,
    "PAY_n seuls": lambda c: c in PAY,
    "Sans les PAY_n": lambda c: c not in PAY,
}
TYPES_VARIANTE = {v: {t: [c for c in cols if garder(c)] for t, cols in TYPES_ORIGINE.items()} for v, garder in VARIANTES.items()}
COLONNES_VARIANTE = {v: [c for cols in types.values() for c in cols] for v, types in TYPES_VARIANTE.items()}

# Contrôles : colonnes présentes, ni identifiant ni cible, les 23 variables couvertes par la variante complète
assert sorted(COLONNES_VARIANTE["Complet"]) == sorted(c for c in original.columns if c not in ("ID", "dpnm"))
assert sorted(COLONNES_VARIANTE["PAY_n seuls"] + COLONNES_VARIANTE["Sans les PAY_n"]) == sorted(COLONNES_VARIANTE["Complet"])
assert (original[TYPES_ORIGINE["log"]] >= 0).all().all(), "Le logarithme ne s'applique qu'à des montants positifs ou nuls"

display(pd.DataFrame({
    "Variante": list(VARIANTES),
    "Nombre de variables": [len(COLONNES_VARIANTE[v]) for v in VARIANTES],
    "Variables": [", ".join(COLONNES_VARIANTE[v]) for v in VARIANTES],
}).set_index("Variante"))

                Nombre de variables                                                                                                                                                                                                         Variables
Variante
Complet                          23  AGE, PAY_AMT1, PAY_AMT2, PAY_AMT3, PAY_AMT4, PAY_AMT5, PAY_AMT6, LIMIT_BAL, BILL_AMT1, BILL_AMT2, BILL_AMT3, BILL_AMT4, BILL_AMT5, BILL_AMT6, SEX, EDUCATION, MARRIAGE, PAY_1, PAY_2, PAY_3, PAY_4, PAY_5, PAY_6
PAY_n seuls                       6                                                                                                                                                                          PAY_1, PAY_2, PAY_3, PAY_4, PAY_5, PAY_6
Sans les PAY_n                   17                                            AGE, PAY_AMT1, PAY_AMT2, PAY_AMT3, PAY_AMT4, PAY_AMT5, PAY_AMT6, LIMIT_BAL, BILL_AMT1, BILL_AMT2, BILL_AMT3, BILL_AMT4, BILL_AMT5, BILL_AMT6, SEX, EDUCATION, MARRIAGE

In [8]:
from catboost import CatBoostClassifier
from IPython.display import Markdown, display
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import FunctionTransformer, OneHotEncoder, StandardScaler

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 250)
pd.set_option("display.max_colwidth", None)   # textes affichés en entier

# Pondération des défauts pour CatBoost (part des non-défauts / part des défauts)
scale_pos = (y_train == 0).sum() / (y_train == 1).sum()

# Transformation de chaque type de colonne (un nouvel objet à chaque appel)
TRANSFORMATIONS = {
    "num": lambda: StandardScaler(),
    "log": lambda: make_pipeline(FunctionTransformer(np.log1p, feature_names_out="one-to-one"), StandardScaler()),
    "log_signe": lambda: make_pipeline(FunctionTransformer(np.arcsinh, feature_names_out="one-to-one"), StandardScaler()),
    "cat": lambda: OneHotEncoder(sparse_output=False, handle_unknown="ignore"),
}

def preprocesseur(variante):
    # Une branche par type de colonne, seulement pour les types présents dans la variante
    return ColumnTransformer(transformers=[(nom, TRANSFORMATIONS[nom](), colonnes)
                                           for nom, colonnes in TYPES_VARIANTE[variante].items() if colonnes])

# Critère optimisé par la boucle : la précision moyenne (aire sous la courbe précision-rappel), sur tous les rappels
CRITERE = "average_precision"
scorers = {
    "average_precision": "average_precision",
    "roc_auc": "roc_auc",
}

# Rappel minimal des scénarios (60 %) : sert seulement à la comparaison avec les scénarios (section 6)
RAPPEL_MINIMAL = 0.60

def seuil_pour_rappel(y, proba, rappel=RAPPEL_MINIMAL):
    # Seuil le plus haut qui détecte au moins la part voulue des défauts
    proba_defauts = np.sort(proba[np.asarray(y) == 1])[::-1]
    return proba_defauts[int(np.ceil(rappel * len(proba_defauts))) - 1]

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Modèles de l'essai : les meilleurs des scénarios, avec leurs réglages de la première itération
MODELES_A_TESTER = ["LogisticRegression", "MLPClassifier", "RandomForest", "CatBoost"]

def modeles_de_base(variante):
    prep = preprocesseur(variante)
    tous = {
        "LogisticRegression": make_pipeline(prep, LogisticRegression(max_iter=1000, class_weight="balanced", random_state=42)),
        "MLPClassifier": make_pipeline(prep, MLPClassifier(hidden_layer_sizes=(50, 25), max_iter=500, random_state=42, early_stopping=True)),
        "RandomForest": make_pipeline(prep, RandomForestClassifier(class_weight="balanced", random_state=42, n_jobs=-1)),
        "CatBoost": make_pipeline(prep, CatBoostClassifier(scale_pos_weight=scale_pos, random_state=42, verbose=0, thread_count=-1, allow_writing_files=False)),
    }
    return {nom: tous[nom] for nom in MODELES_A_TESTER}

# ------------------------------------------------------------------------------
# Alertes et tableaux de scores (ceux des scénarios)
SEUIL_SURAPPRENTISSAGE = 0.07   # écart relatif train - val du critère : 7 % pour cet essai (5 % dans les scénarios) ; le double : surapprentissage fort
SEUIL_INSTABILITE = 0.02        # écart-type du critère sur les plis au-delà duquel on alerte (alerte seule, pas une contrainte)
METRIQUES = {"average_precision": "Précision moyenne", "roc_auc": "ROC AUC"}
LIBELLE_SCORE = "Précision des défauts prédits"
TAUX_DEFAUT = y_train.mean()    # précision, et précision moyenne, d'un tri au hasard

def apprend(score_val, std_val):
    # Plancher contre le sous-apprentissage : le critère doit dépasser le hasard (taux de défaut) de plus d'un écart-type
    return score_val - TAUX_DEFAUT > std_val

def alerte(ecart):
    if ecart > 2 * SEUIL_SURAPPRENTISSAGE:
        return "⚠️⚠️ SURAPPRENTISSAGE FORT"
    if ecart > SEUIL_SURAPPRENTISSAGE:
        return "⚠️ SURAPPRENTISSAGE"
    return "✅ OK"

def ligne_scores(nom, moy_val, std_val, moy_train):
    # Une ligne de tableau : chaque métrique en entraînement et en validation, le critère, son écart-type et l'alerte
    ligne = {"Modèle": nom}
    for cle, libelle in METRIQUES.items():
        ligne[f"{libelle} (train)"] = moy_train[cle]
        ligne[f"{libelle} (val)"] = moy_val[cle]
    ligne["Critère (val)"], ligne["Critère (train)"] = moy_val[CRITERE], moy_train[CRITERE]
    ligne["Écart-type critère (val)"] = std_val
    ligne["Écart train - val"] = moy_train[CRITERE] - moy_val[CRITERE]
    ligne["Écart relatif"] = ligne["Écart train - val"] / moy_val[CRITERE]
    ligne["Apprend"] = apprend(moy_val[CRITERE], std_val)
    ligne["Alerte"] = alerte(ligne["Écart relatif"]) if ligne["Apprend"] else "⚠️ N'APPREND RIEN (niveau du hasard)"
    if std_val > SEUIL_INSTABILITE:
        ligne["Alerte"] += " ; ⚠️ INSTABLE"
    return ligne

def pct(serie):
    return (serie * 100).round(1)

def parametres(params):
    # Paramètres sur une ligne : « depth 4, 5, 6 ; l2_leaf_reg 15 »
    return " ; ".join(f"{p} {', '.join(map(str, v)) if isinstance(v, list) else v}" for p, v in params.items())

def montrer(df, titre):
    display(Markdown(f"**{titre}**"))
    display(df.set_index(df.columns[0]))

In [9]:
from itertools import product
from sklearn.model_selection import GridSearchCV

TOURS_SECURITE = 15   # garde-fou contre une boucle sans fin : la boucle s'arrête d'elle-même avant ; s'il est atteint, revoir les grilles ou les bornes

# Grilles du premier tour : celles des scénarios
grilles = {
    "LogisticRegression": {"logisticregression__C": [0.01, 0.1, 1.0, 10.0]},
    "MLPClassifier": {"mlpclassifier__hidden_layer_sizes": [(32, 16), (64, 32), (32,)], "mlpclassifier__alpha": [0.01, 0.1, 1.0]},
    "RandomForest": {"randomforestclassifier__max_depth": [6, 8, 10], "randomforestclassifier__min_samples_leaf": [20, 50, 100], "randomforestclassifier__n_estimators": [200, 300]},
    "CatBoost": {"catboostclassifier__depth": [4, 6], "catboostclassifier__l2_leaf_reg": [5, 10, 15], "catboostclassifier__learning_rate": [0.03, 0.05],
                 "catboostclassifier__iterations": [1000]},   # 1 000 arbres : valeur par défaut, réduite par la boucle en cas de surapprentissage
}

# Comment faire évoluer chaque paramètre numérique d'un tour à l'autre (ceux des scénarios) :
# - simplifier : sens qui réduit le surapprentissage (+1 = augmenter, -1 = diminuer) ;
# - pas : écart entre deux valeurs (« x » = multiplier, « + » = ajouter) ;
# - bornes : valeurs minimale et maximale autorisées.
# Les paramètres absents de ce tableau (architecture du MLP, nombre d'arbres du RandomForest) sont fixés à leur meilleure valeur après le premier tour.
REGLAGES_PARAMETRES = {
    "logisticregression__C":                    {"simplifier": -1, "pas": ("x", 3),   "bornes": (1e-4, 1e4),  "entier": False},
    "mlpclassifier__alpha":                     {"simplifier": +1, "pas": ("x", 3),   "bornes": (1e-5, 100),  "entier": False},
    "randomforestclassifier__max_depth":        {"simplifier": -1, "pas": ("+", 2),   "bornes": (2, 30),      "entier": True},
    "randomforestclassifier__min_samples_leaf": {"simplifier": +1, "pas": ("x", 1.5), "bornes": (1, 2000),    "entier": True},
    "catboostclassifier__depth":                {"simplifier": -1, "pas": ("+", 1),   "bornes": (2, 10),      "entier": True},
    "catboostclassifier__l2_leaf_reg":          {"simplifier": +1, "pas": ("x", 1.5), "bornes": (1, 200),     "entier": False},
    "catboostclassifier__learning_rate":        {"simplifier": -1, "pas": ("x", 1.5), "bornes": (0.003, 0.3), "entier": False},
    "catboostclassifier__iterations":           {"simplifier": -1, "pas": ("x", 1.5), "bornes": (100, 3000),  "entier": True},
}

def nom_court(parametre):
    return parametre.split("__")[-1]

def arrondir(valeur, entier):
    return int(round(valeur)) if entier else float(f"{valeur:.3g}")

def voisin(valeur, reglage, sens):
    # Valeur suivante dans un sens (+1 = plus grande, -1 = plus petite), dans les bornes
    mode, pas = reglage["pas"]
    if mode == "x":
        nouvelle = valeur * pas if sens > 0 else valeur / pas
    else:
        nouvelle = valeur + pas if sens > 0 else valeur - pas
    bas, haut = reglage["bornes"]
    nouvelle = arrondir(min(max(nouvelle, bas), haut), reglage["entier"])
    return None if nouvelle == valeur else nouvelle

def choisir_index(r):
    # Choix sous contrainte, parmi les réglages qui battent le hasard : le meilleur critère sans surapprentissage ;
    # sinon le moins surappris ; si aucun ne bat le hasard, le meilleur score
    val, std = r[f"mean_test_{CRITERE}"], r[f"std_test_{CRITERE}"]
    ecarts = (r[f"mean_train_{CRITERE}"] - val) / val   # écarts relatifs
    utiles = apprend(val, std)
    sous_seuil = np.where(utiles & (ecarts <= SEUIL_SURAPPRENTISSAGE))[0]
    if len(sous_seuil):
        return int(sous_seuil[np.argmax(val[sous_seuil])])
    if utiles.any():
        idx = np.where(utiles)[0]
        return int(idx[np.argmin(ecarts[idx])])
    return int(np.argmax(val))

def bords_de_grille(grille, meilleurs):
    # Paramètres numériques dont la meilleure valeur est la plus petite ou la plus grande de la grille (+1 = maximum, -1 = minimum)
    bords = {}
    for p, valeurs in grille.items():
        if p in REGLAGES_PARAMETRES and len(valeurs) > 1:
            if meilleurs[p] == max(valeurs):
                bords[p] = +1
            elif meilleurs[p] == min(valeurs):
                bords[p] = -1
    return bords

def grille_suivante(grille, meilleurs, bords, surapprend):
    # Grille du tour suivant et explication des corrections ; None si plus rien ne peut bouger
    nouvelle, actions = {}, []
    for p, valeurs in grille.items():
        v = meilleurs[p]
        reglage = REGLAGES_PARAMETRES.get(p)
        if reglage is None:
            nouvelle[p] = [v]                            # catégorie ou paramètre sans effet : fixé
            continue
        sens = None
        if surapprend and reglage["simplifier"] != 0:
            sens = reglage["simplifier"]                 # pousser vers un modèle plus simple
            raison = "surapprentissage"
        elif p in bords:
            sens = bords[p]                              # prolonger la grille du côté du bord
            raison = "bord de grille"
        if sens is None:
            nouvelle[p] = [v]
            continue
        v1 = voisin(v, reglage, sens)
        v2 = voisin(v1, reglage, sens) if v1 is not None else None
        valeurs_tour = [x for x in (v, v1, v2) if x is not None]
        nouvelle[p] = sorted(set(valeurs_tour))
        if len(nouvelle[p]) > 1:
            actions.append(f"{nom_court(p)} {v} → {nouvelle[p]} ({raison})")
    if not actions:
        return None, ["bornes atteintes : la grille ne peut plus bouger"]
    return nouvelle, actions

def lancer_grille(nom, modele, grille, X):
    grid = GridSearchCV(modele, grille, cv=cv, scoring=scorers, refit=choisir_index, return_train_score=True, n_jobs=-1)
    grid.fit(X, y_train)
    r, i = grid.cv_results_, grid.best_index_
    ligne = ligne_scores(nom,
                         {k: r[f"mean_test_{k}"][i] for k in METRIQUES},
                         r[f"std_test_{CRITERE}"][i],
                         {k: r[f"mean_train_{k}"][i] for k in METRIQUES})
    ligne["Meilleurs paramètres"] = {nom_court(k): v for k, v in grid.best_params_.items()}
    return grid, ligne

def cle_reglage(params):
    # Identifiant d'une combinaison de paramètres, pour savoir si elle a déjà été testée
    return str(sorted(params.items()))

def reglages_nouveaux(grille, deja_testes):
    # Combinaisons de la grille qui n'ont encore été testées à aucun tour
    combinaisons = [dict(zip(grille, valeurs)) for valeurs in product(*grille.values())]
    return [c for c in combinaisons if cle_reglage(c) not in deja_testes]

def choisir_tour(tours):
    # Version retenue parmi les tours joués : d'abord ceux qui battent le hasard et sans surapprentissage
    # (sinon ceux qui battent le hasard, sinon tous) ; parmi eux, ceux à moins d'un écart-type du meilleur score
    # (à égalité avec lui) ; et parmi ces derniers, celui qui surapprend le moins
    for garder in (lambda l: l["Apprend"] and l["Écart relatif"] <= SEUIL_SURAPPRENTISSAGE, lambda l: l["Apprend"], lambda l: True):
        groupe = [t for t in tours if garder(t[1])]
        if groupe:
            break
    meilleur = max(groupe, key=lambda t: t[1]["Critère (val)"])[1]
    egaux = [t for t in groupe if meilleur["Critère (val)"] - t[1]["Critère (val)"] <= meilleur["Écart-type critère (val)"]]
    return min(egaux, key=lambda t: t[1]["Écart relatif"])

def boucle(variante):
    # Boucle des scénarios, pour un jeu de variables : version retenue de chaque modèle, lignes de scores et historique
    X = original[COLONNES_VARIANTE[variante]].reset_index(drop=True)
    best_models, lignes_retenues, historique = {}, [], []
    for nom, modele in modeles_de_base(variante).items():
        grille, retenu, fin, deja_testes, reglage_precedent, tours = grilles[nom], None, None, set(), None, []
        for tour in range(1, TOURS_SECURITE + 1):
            grid, ligne = lancer_grille(nom, modele, grille, X)
            ligne["Tour"] = tour
            deja_testes |= {cle_reglage(c) for c in grid.cv_results_["params"]}
            surapprend = ligne["Écart relatif"] > SEUIL_SURAPPRENTISSAGE
            bords = bords_de_grille(grille, grid.best_params_)
            precedent = retenu
            tours.append((grid, ligne))
            retenu = choisir_tour(tours)
            grille_tour = {nom_court(p): v for p, v in grille.items()}
            reglage = ligne["Meilleurs paramètres"]
            # Stagnation : seulement entre deux tours sans surapprentissage
            stagne = (precedent is not None and not surapprend
                      and precedent[1]["Écart relatif"] <= SEUIL_SURAPPRENTISSAGE
                      and ligne["Critère (val)"] - precedent[1]["Critère (val)"] <= precedent[1]["Écart-type critère (val)"])
            if not ligne["Apprend"]:
                fin = "sous-apprentissage : le réglage choisi ne bat plus le hasard"
            elif not surapprend and not bords:
                fin = "optimisé : ni surapprentissage ni paramètre au bord"
            elif reglage == reglage_precedent:
                fin = "convergé : le réglage choisi ne change plus"
            elif stagne:
                fin = "stagnation : gain plus petit que l'écart-type, entre deux tours sans surapprentissage"
            elif tour == TOURS_SECURITE:
                fin = "⚠️ garde-fou atteint : grilles ou bornes à revoir"
            else:
                grille, actions = grille_suivante(grille, grid.best_params_, bords, surapprend)
                if grille is None:
                    fin = actions[0]
                elif not reglages_nouveaux(grille, deja_testes):
                    fin = "convergé : la grille suivante ne contient aucun réglage nouveau"
            reglage_precedent = reglage
            historique.append({
                "Modèle": nom, "Tour": tour, "Grille testée": grille_tour, "Réglage choisi": reglage,
                "Critère (val)": ligne["Critère (val)"], "Écart-type": ligne["Écart-type critère (val)"],
                "Écart relatif": ligne["Écart relatif"], "Alerte": ligne["Alerte"],
                "Suite": fin if fin else "; ".join(actions),
            })
            if fin:
                break
        best_models[nom] = retenu[0].best_estimator_
        lignes_retenues.append(dict(retenu[1], **{"Arrêt": fin, "Tours joués": tour}))
        print(f"  {nom} : {tour} tour(s), {fin} ; version retenue : tour {retenu[1]['Tour']}")
    return best_models, pd.DataFrame(lignes_retenues), pd.DataFrame(historique)

## 3. Boucle d'optimisation et seuil optimisé, pour chaque population

Pour chaque population : la boucle règle les 4 modèles dans chaque variante (une ligne par modèle pendant le calcul), puis chaque version retenue est réentraînée sur chaque pli avec son **seuil par la règle marginale** (validation croisée interne), et jugée sur le pli de validation. Le tableau de chaque population donne, en validation (moyenne ± écart-type sur les 5 plis) : le réglage retenu, la précision moyenne et le ROC AUC (sans seuil), puis, au seuil optimisé, le rappel, la précision des défauts prédits, la précision marginale (contrôle de la règle, visée 50 %) et la part des clients signalés. **Plis sans tri** : nombre de plis où le modèle donne la même probabilité à tous les clients (il n'apprend rien) ; aucun seuil ne peut alors se chercher, et la décision se prend au seuil de la règle marginale lu sur cette probabilité (10 % dans les populations de la règle, 50 % pour les autres clients).

In [10]:
import time
from sklearn.base import clone
from sklearn.metrics import average_precision_score, make_scorer, precision_score, recall_score, roc_auc_score
from sklearn.model_selection import TunedThresholdClassifierCV

cv_interne = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)   # plis internes, pour le choix du seuil
PART_MARGE = 0.10

def gain_net(y_vrai, y_pred, tolerance):
    # Défauts détectés moins « tolérance » × bons clients signalés : maximal au seuil où le risque des derniers clients signalés
    # vaut tolerance / (1 + tolerance) (50 % pour une tolérance de 1, 10 % pour 1/9)
    y_vrai, y_pred = np.asarray(y_vrai), np.asarray(y_pred).astype(bool)
    return ((y_pred & (y_vrai == 1)).sum() - tolerance * (y_pred & (y_vrai == 0)).sum()) / len(y_vrai)

def precision_marginale(y_vrai, proba, signales):
    idx = np.where(signales)[0]
    if len(idx) == 0:
        return np.nan
    derniers = idx[np.argsort(proba[idx])[:max(1, int(np.ceil(PART_MARGE * len(idx))))]]
    return y_vrai[derniers].mean()

def moy_et(valeurs, en_pct=False):
    facteur = 100 if en_pct else 1
    return f"{np.nanmean(valeurs) * facteur:.{1 if en_pct else 3}f} ± {np.nanstd(valeurs) * facteur:.{1 if en_pct else 3}f}"

def activer(population):
    # Rend une population active pour les fonctions reprises de l'essai (elles lisent ces variables globales)
    global original, y_train, scale_pos, TAUX_DEFAUT, y, plis, SCORE_SEUIL
    original = POPULATIONS[population]
    SCORE_SEUIL = make_scorer(gain_net, tolerance=TOLERANCE[population])   # tolérance de la règle marginale propre à la population
    y_train = original["dpnm"].reset_index(drop=True)
    y = y_train.to_numpy()
    scale_pos = (y_train == 0).sum() / (y_train == 1).sum()
    TAUX_DEFAUT = y_train.mean()
    plis = list(cv.split(original, y_train))

ETUDE = {}   # population -> {"probas", "decisions", "mesures", "modeles_plis", "plis", "retenus"}
for population in POPULATIONS:
    activer(population)
    debut = time.time()
    display(Markdown(f"### {population} : {len(original)} clients, taux de défaut {TAUX_DEFAUT * 100:.1f} % ; "
                     f"tolérance {TOLERANCE[population]:.3g} (signalé en défaut dès {TOLERANCE[population] / (1 + TOLERANCE[population]):.0%} de risque à la marge)"))
    probas, decisions, mesures, modeles_plis, retenus = {}, {}, {}, {}, {}
    for variante in VARIANTES:
        print(f"Variante « {variante} »")
        best_models, df_retenus, _ = boucle(variante)
        retenus[variante] = df_retenus.set_index("Modèle")
        X = original[COLONNES_VARIANTE[variante]].reset_index(drop=True)
        for nom, modele in best_models.items():
            p, d, entraines = np.zeros(len(y)), np.zeros(len(y), dtype=int), []
            m_plis = {"Rappel": [], "Précision": [], "Précision marginale": [], "Signalés": [], "Précision moyenne": [], "ROC AUC": [], "Sans tri": 0}
            for entrainement, validation in plis:
                try:
                    seuil_auto = TunedThresholdClassifierCV(clone(modele), scoring=SCORE_SEUIL, cv=cv_interne, n_jobs=-1)
                    seuil_auto.fit(X.iloc[entrainement], y[entrainement])
                    p[validation] = seuil_auto.predict_proba(X.iloc[validation])[:, 1]
                    d[validation] = seuil_auto.predict(X.iloc[validation])
                except ValueError as erreur:
                    if "constant predictions" not in str(erreur):
                        raise
                    # Le modèle donne la même probabilité à tous les clients des plis internes : il ne trie pas, aucun seuil ne se cherche.
                    # Repli : seuil de la règle marginale lu sur la probabilité elle-même (tolérance / (1 + tolérance))
                    seuil_auto = clone(modele).fit(X.iloc[entrainement], y[entrainement])
                    p[validation] = seuil_auto.predict_proba(X.iloc[validation])[:, 1]
                    d[validation] = (p[validation] >= TOLERANCE[population] / (1 + TOLERANCE[population])).astype(int)
                    m_plis["Sans tri"] += 1
                y_val, dec = y[validation], d[validation].astype(bool)
                m_plis["Rappel"].append(recall_score(y_val, dec))
                m_plis["Précision"].append(precision_score(y_val, dec, zero_division=0))
                m_plis["Précision marginale"].append(precision_marginale(y_val, p[validation], dec))
                m_plis["Signalés"].append(dec.mean())
                m_plis["Précision moyenne"].append(average_precision_score(y_val, p[validation]))
                m_plis["ROC AUC"].append(roc_auc_score(y_val, p[validation]))
                entraines.append(seuil_auto)
            probas[(variante, nom)], decisions[(variante, nom)], mesures[(variante, nom)], modeles_plis[(variante, nom)] = p, d, m_plis, entraines
    ETUDE[population] = {"probas": probas, "decisions": decisions, "mesures": mesures, "modeles_plis": modeles_plis, "plis": plis, "retenus": retenus}
    lignes = []
    for (variante, nom), m in mesures.items():
        r = retenus[variante].loc[nom]
        lignes.append({"Variante": variante, "Modèle": nom, "Réglage retenu": parametres(r["Meilleurs paramètres"]),
                       "Écart relatif (%)": round(r["Écart relatif"] * 100, 1),
                       "Précision moyenne": moy_et(m["Précision moyenne"]), "ROC AUC": moy_et(m["ROC AUC"]),
                       "Rappel (%)": moy_et(m["Rappel"], True), "Précision (%)": moy_et(m["Précision"], True),
                       "Précision marginale (%)": moy_et(m["Précision marginale"], True), "Clients signalés (%)": moy_et(m["Signalés"], True),
                       "Plis sans tri": m["Sans tri"]})
    display(Markdown(f"**{population} : détection en validation, au seuil de la règle marginale** (précision marginale visée : "
                     f"{TOLERANCE[population] / (1 + TOLERANCE[population]):.0%} de défauts parmi les derniers signalés ; {(time.time() - debut) / 60:.1f} min)"))
    display(pd.DataFrame(lignes).set_index(["Variante", "Modèle"]))

### En incident : 3754 clients, taux de défaut 59.2 % ; tolérance 0.111 (signalé en défaut dès 10% de risque à la marge)

Variante « Complet »
  LogisticRegression : 1 tour(s), optimisé : ni surapprentissage ni paramètre au bord ; version retenue : tour 1
  MLPClassifier : 2 tour(s), convergé : le réglage choisi ne change plus ; version retenue : tour 1
  RandomForest : 2 tour(s), stagnation : gain plus petit que l'écart-type, entre deux tours sans surapprentissage ; version retenue : tour 2
  CatBoost : 3 tour(s), convergé : le réglage choisi ne change plus ; version retenue : tour 2
Variante « PAY_n seuls »
  LogisticRegression : 1 tour(s), optimisé : ni surapprentissage ni paramètre au bord ; version retenue : tour 1
  MLPClassifier : 2 tour(s), stagnation : gain plus petit que l'écart-type, entre deux tours sans surapprentissage ; version retenue : tour 2
  RandomForest : 2 tour(s), stagnation : gain plus petit que l'écart-type, entre deux tours sans surapprentissage ; version retenue : tour 1
  CatBoost : 3 tour(s), stagnation : gain plus petit que l'écart-type, entre deux tours sans surapprentissage ; version retenue : tour 2
Variante « Sans les PAY_n »
  LogisticRegression : 2 tour(s), convergé : le réglage choisi ne change plus ; version retenue : tour 1
  MLPClassifier : 2 tour(s), optimisé : ni surapprentissage ni paramètre au bord ; version retenue : tour 2
  RandomForest : 3 tour(s), convergé : le réglage choisi ne change plus ; version retenue : tour 2
  CatBoost : 3 tour(s), convergé : le réglage choisi ne change plus ; version retenue : tour 2

**En incident : détection en validation, au seuil de la règle marginale** (précision marginale visée : 10% de défauts parmi les derniers signalés ; 3.7 min)

                                                                                       Réglage retenu  Écart relatif (%) Précision moyenne        ROC AUC   Rappel (%) Précision (%) Précision marginale (%) Clients signalés (%)  Plis sans tri
Variante       Modèle
Complet        LogisticRegression                                                               C 0.1                3.2     0.705 ± 0.019  0.629 ± 0.020  100.0 ± 0.0    59.2 ± 0.1              40.1 ± 6.1          100.0 ± 0.0              0
               MLPClassifier                                 alpha 0.01 ; hidden_layer_sizes (64, 32)                6.8     0.708 ± 0.019  0.630 ± 0.020   99.7 ± 0.3    59.2 ± 0.1              40.7 ± 6.1           99.7 ± 0.3              0
               RandomForest                     max_depth 4 ; min_samples_leaf 100 ; n_estimators 300                4.4     0.707 ± 0.016  0.628 ± 0.017  100.0 ± 0.0    59.2 ± 0.1              39.8 ± 2.3          100.0 ± 0.0              0
               CatBoost            depth 3 ; iterations 445 ; l2_leaf_reg 22.5 ; learning_rate 0.0133                7.0     0.714 ± 0.018  0.635 ± 0.020  100.0 ± 0.0    59.2 ± 0.1              38.1 ± 4.6           99.9 ± 0.1              0
PAY_n seuls    LogisticRegression                                                               C 0.1                1.9     0.692 ± 0.020  0.626 ± 0.023   99.9 ± 0.2    59.2 ± 0.1              41.0 ± 5.2           99.9 ± 0.1              0
               MLPClassifier                              alpha 0.00111 ; hidden_layer_sizes (64, 32)                1.9     0.691 ± 0.019  0.625 ± 0.020  100.0 ± 0.1    59.2 ± 0.1              40.4 ± 5.2          100.0 ± 0.1              0
               RandomForest                     max_depth 10 ; min_samples_leaf 20 ; n_estimators 200                1.8     0.689 ± 0.018  0.624 ± 0.018  100.0 ± 0.0    59.2 ± 0.1              41.2 ± 2.0          100.0 ± 0.0              0
               CatBoost              depth 2 ; iterations 667 ; l2_leaf_reg 15 ; learning_rate 0.0133                2.6     0.691 ± 0.020  0.624 ± 0.023   99.9 ± 0.2    59.2 ± 0.1              40.0 ± 6.3           99.9 ± 0.1              0
Sans les PAY_n LogisticRegression                                                              C 0.01                1.1     0.674 ± 0.012  0.594 ± 0.013  100.0 ± 0.0    59.2 ± 0.1              46.4 ± 2.9          100.0 ± 0.0              0
               MLPClassifier                                  alpha 3.0 ; hidden_layer_sizes (32, 16)                3.1     0.671 ± 0.019  0.586 ± 0.020  100.0 ± 0.0    59.2 ± 0.0              48.4 ± 6.9          100.0 ± 0.1              0
               RandomForest                     max_depth 4 ; min_samples_leaf 100 ; n_estimators 200                6.3     0.685 ± 0.007  0.599 ± 0.018  100.0 ± 0.0    59.2 ± 0.1              44.6 ± 7.4          100.0 ± 0.0              0
               CatBoost              depth 2 ; iterations 445 ; l2_leaf_reg 22.5 ; learning_rate 0.02                6.8     0.692 ± 0.009  0.606 ± 0.016   99.9 ± 0.2    59.3 ± 0.1              44.7 ± 6.2           99.7 ± 0.2              0

### Retard imminent : 989 clients, taux de défaut 65.6 % ; tolérance 0.111 (signalé en défaut dès 10% de risque à la marge)

Variante « Complet »
  LogisticRegression : 2 tour(s), convergé : le réglage choisi ne change plus ; version retenue : tour 1
  MLPClassifier : 2 tour(s), convergé : le réglage choisi ne change plus ; version retenue : tour 1
  RandomForest : 3 tour(s), convergé : le réglage choisi ne change plus ; version retenue : tour 2
  CatBoost : 4 tour(s), bornes atteintes : la grille ne peut plus bouger ; version retenue : tour 4
Variante « PAY_n seuls »
  LogisticRegression : 1 tour(s), optimisé : ni surapprentissage ni paramètre au bord ; version retenue : tour 1
  MLPClassifier : 1 tour(s), optimisé : ni surapprentissage ni paramètre au bord ; version retenue : tour 1
  RandomForest : 2 tour(s), convergé : le réglage choisi ne change plus ; version retenue : tour 1
  CatBoost : 3 tour(s), convergé : le réglage choisi ne change plus ; version retenue : tour 2
Variante « Sans les PAY_n »
  LogisticRegression : 1 tour(s), optimisé : ni surapprentissage ni paramètre au bord ; version retenue : tour 1
  MLPClassifier : 2 tour(s), stagnation : gain plus petit que l'écart-type, entre deux tours sans surapprentissage ; version retenue : tour 2
  RandomForest : 3 tour(s), convergé : le réglage choisi ne change plus ; version retenue : tour 2
  CatBoost : 5 tour(s), convergé : le réglage choisi ne change plus ; version retenue : tour 4

**Retard imminent : détection en validation, au seuil de la règle marginale** (précision marginale visée : 10% de défauts parmi les derniers signalés ; 4.4 min)

                                                                                       Réglage retenu  Écart relatif (%) Précision moyenne        ROC AUC   Rappel (%) Précision (%) Précision marginale (%) Clients signalés (%)  Plis sans tri
Variante       Modèle
Complet        LogisticRegression                                                              C 0.01                5.5     0.717 ± 0.026  0.578 ± 0.033  100.0 ± 0.0    65.6 ± 0.1             39.0 ± 10.7          100.0 ± 0.0              0
               MLPClassifier                                  alpha 1.0 ; hidden_layer_sizes (64, 32)                4.7     0.744 ± 0.033  0.627 ± 0.033   99.5 ± 0.9    65.7 ± 0.1              38.0 ± 6.8           99.5 ± 1.0              0
               RandomForest                     max_depth 2 ; min_samples_leaf 225 ; n_estimators 300                4.0     0.692 ± 0.031  0.530 ± 0.034  100.0 ± 0.0    65.6 ± 0.1              55.0 ± 5.5          100.0 ± 0.0              5
               CatBoost            depth 2 ; iterations 100 ; l2_leaf_reg 114.0 ; learning_rate 0.003                7.0     0.719 ± 0.022  0.582 ± 0.034   99.1 ± 1.5    65.7 ± 0.3             41.5 ± 10.9           99.0 ± 1.8              0
PAY_n seuls    LogisticRegression                                                               C 0.1                2.0     0.718 ± 0.019  0.598 ± 0.037  100.0 ± 0.0    65.6 ± 0.1             40.0 ± 13.0          100.0 ± 0.0              0
               MLPClassifier                                  alpha 0.1 ; hidden_layer_sizes (64, 32)               -0.2     0.723 ± 0.025  0.596 ± 0.051   98.5 ± 1.9    66.0 ± 0.7             41.0 ± 17.0           98.0 ± 2.5              0
               RandomForest                      max_depth 8 ; min_samples_leaf 20 ; n_estimators 300                1.4     0.720 ± 0.018  0.599 ± 0.033  100.0 ± 0.0    65.6 ± 0.1             40.0 ± 10.0          100.0 ± 0.0              0
               CatBoost              depth 2 ; iterations 445 ; l2_leaf_reg 22.5 ; learning_rate 0.02                4.7     0.716 ± 0.026  0.591 ± 0.043  100.0 ± 0.0    65.6 ± 0.1             37.0 ± 13.6          100.0 ± 0.0              0
Sans les PAY_n LogisticRegression                                                               C 0.1                5.9     0.705 ± 0.030  0.570 ± 0.031  100.0 ± 0.0    65.6 ± 0.1             40.0 ± 10.5          100.0 ± 0.0              0
               MLPClassifier                              alpha 0.00111 ; hidden_layer_sizes (64, 32)                5.4     0.702 ± 0.015  0.551 ± 0.031   99.4 ± 0.6    65.8 ± 0.3              50.0 ± 3.2           99.1 ± 0.9              0
               RandomForest                     max_depth 2 ; min_samples_leaf 225 ; n_estimators 300                4.0     0.694 ± 0.028  0.530 ± 0.031  100.0 ± 0.0    65.6 ± 0.1              56.0 ± 6.6          100.0 ± 0.0              5
               CatBoost            depth 2 ; iterations 100 ; l2_leaf_reg 114.0 ; learning_rate 0.003               10.2     0.693 ± 0.019  0.565 ± 0.022  100.0 ± 0.0    65.6 ± 0.1             43.0 ± 10.3          100.0 ± 0.0              0

### Autres clients : 24108 clients, taux de défaut 14.1 % ; tolérance 1 (signalé en défaut dès 50% de risque à la marge)

Variante « Complet »
  LogisticRegression : 2 tour(s), convergé : le réglage choisi ne change plus ; version retenue : tour 1
  MLPClassifier : 2 tour(s), convergé : le réglage choisi ne change plus ; version retenue : tour 1
  RandomForest : 3 tour(s), stagnation : gain plus petit que l'écart-type, entre deux tours sans surapprentissage ; version retenue : tour 2
  CatBoost : 3 tour(s), convergé : le réglage choisi ne change plus ; version retenue : tour 2
Variante « PAY_n seuls »
  LogisticRegression : 1 tour(s), optimisé : ni surapprentissage ni paramètre au bord ; version retenue : tour 1
  MLPClassifier : 2 tour(s), convergé : le réglage choisi ne change plus ; version retenue : tour 1
  RandomForest : 2 tour(s), convergé : le réglage choisi ne change plus ; version retenue : tour 1
  CatBoost : 3 tour(s), stagnation : gain plus petit que l'écart-type, entre deux tours sans surapprentissage ; version retenue : tour 2
Variante « Sans les PAY_n »
  LogisticRegression : 2 tour(s), convergé : le réglage choisi ne change plus ; version retenue : tour 1
  MLPClassifier : 2 tour(s), stagnation : gain plus petit que l'écart-type, entre deux tours sans surapprentissage ; version retenue : tour 1
  RandomForest : 3 tour(s), convergé : le réglage choisi ne change plus ; version retenue : tour 2
  CatBoost : 3 tour(s), stagnation : gain plus petit que l'écart-type, entre deux tours sans surapprentissage ; version retenue : tour 2

C:\Users\johan\AppData\Local\Temp\ipykernel_6148\685219610.py:24: RuntimeWarning: Mean of empty slice
  return f"{np.nanmean(valeurs) * facteur:.{1 if en_pct else 3}f} ± {np.nanstd(valeurs) * facteur:.{1 if en_pct else 3}f}"
c:\Users\johan\VS Code Wild 2\PROJET_DEFAULT_CREDIT_CARD_ML\.venv\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1997: RuntimeWarning: Degrees of freedom <= 0 for slice.
  var = nanvar(a, axis=axis, dtype=dtype, out=out, ddof=ddof,

**Autres clients : détection en validation, au seuil de la règle marginale** (précision marginale visée : 50% de défauts parmi les derniers signalés ; 18.0 min)

                                                                                     Réglage retenu  Écart relatif (%) Précision moyenne        ROC AUC Rappel (%) Précision (%) Précision marginale (%) Clients signalés (%)  Plis sans tri
Variante       Modèle
Complet        LogisticRegression                                                            C 0.01                1.4     0.262 ± 0.012  0.667 ± 0.007  0.1 ± 0.2   17.5 ± 21.8             100.0 ± 0.0            0.0 ± 0.1              0
               MLPClassifier                                   alpha 1.0 ; hidden_layer_sizes (32,)                3.9     0.253 ± 0.014  0.662 ± 0.011  0.5 ± 0.4   41.0 ± 33.2             45.8 ± 36.1            0.2 ± 0.2              0
               RandomForest                   max_depth 2 ; min_samples_leaf 100 ; n_estimators 300                4.6     0.245 ± 0.007  0.647 ± 0.009  0.0 ± 0.0     0.0 ± 0.0               0.0 ± 0.0            0.0 ± 0.0              0
               CatBoost            depth 3 ; iterations 445 ; l2_leaf_reg 33.8 ; learning_rate 0.02                5.8     0.268 ± 0.012  0.679 ± 0.009  0.0 ± 0.0     0.0 ± 0.0               0.0 ± 0.0            0.0 ± 0.0              0
PAY_n seuls    LogisticRegression                                                             C 1.0                3.1     0.231 ± 0.010  0.614 ± 0.005  0.1 ± 0.3    7.7 ± 15.4             16.7 ± 23.6            0.1 ± 0.1              0
               MLPClassifier                               alpha 0.01 ; hidden_layer_sizes (32, 16)                3.6     0.231 ± 0.006  0.615 ± 0.005  0.0 ± 0.1   20.0 ± 40.0             50.0 ± 50.0            0.0 ± 0.0              0
               RandomForest                    max_depth 6 ; min_samples_leaf 50 ; n_estimators 200                2.9     0.229 ± 0.013  0.615 ± 0.006  0.1 ± 0.1   10.0 ± 20.0               0.0 ± 0.0            0.0 ± 0.0              0
               CatBoost              depth 2 ; iterations 445 ; l2_leaf_reg 15 ; learning_rate 0.03                4.5     0.232 ± 0.012  0.618 ± 0.005  0.2 ± 0.4    7.0 ± 14.0               0.0 ± 0.0            0.1 ± 0.2              0
Sans les PAY_n LogisticRegression                                                            C 10.0                0.9     0.239 ± 0.008  0.651 ± 0.009  0.6 ± 0.4   36.4 ± 21.2             50.0 ± 35.4            0.2 ± 0.1              0
               MLPClassifier                                  alpha 0.01 ; hidden_layer_sizes (32,)                1.6     0.224 ± 0.023  0.632 ± 0.020  0.4 ± 0.4   25.7 ± 34.3             50.0 ± 50.0            0.1 ± 0.1              0
               RandomForest                   max_depth 2 ; min_samples_leaf 225 ; n_estimators 200                3.6     0.210 ± 0.007  0.627 ± 0.009  0.0 ± 0.0     0.0 ± 0.0               nan ± nan            0.0 ± 0.0              0
               CatBoost            depth 2 ; iterations 667 ; l2_leaf_reg 33.8 ; learning_rate 0.02                6.1     0.251 ± 0.009  0.668 ± 0.009  0.2 ± 0.1   70.0 ± 24.5             40.0 ± 49.0            0.0 ± 0.0              0

**Comment lire** : chaque population a son propre taux de défaut, qui est aussi la précision d'un tri au hasard. Dans la population en incident et dans le retard imminent, la question est de reconnaître ceux qui **ne feront pas** défaut, pour les sortir de la règle : avec la tolérance stricte (9 chances sur 10 d'être sain), seuls les clients au risque très bas sont sortis ; si la part des clients signalés reste proche de 100 %, le modèle ne sait pas trancher et la règle (toute la population en défaut) reste la bonne décision. Pour les autres clients, la règle marginale ne signale que la tête de liste. La précision marginale vérifie la règle (proche de 10 % dans les populations de la règle : risque des derniers clients gardés en défaut ; proche de 50 % pour les autres clients).

## 4. Ce qui porte les prédictions, dans chaque population

Importance par permutation (perte de précision moyenne quand une famille de colonnes est mélangée, sur les plis de validation), comme dans `essai_jeu_corrige.ipynb` : part de chaque famille dans la perte totale, par population, variante et modèle.

In [11]:
FAMILLES = {
    "Codifications (PAY_n)": PAY,
    "Factures (BILL_AMTn)": [f"BILL_AMT{n}" for n in range(1, 7)],
    "Paiements (PAY_AMTn)": [f"PAY_AMT{n}" for n in range(1, 7)],
    "Plafond (LIMIT_BAL)": ["LIMIT_BAL"],
    "Démographie": ["SEX", "EDUCATION", "MARRIAGE", "AGE"],
}
REPETITIONS = 5
generateur = np.random.default_rng(42)

def perte_par_permutation(modeles, X, colonnes):
    # Perte de précision moyenne sur chaque pli de validation quand les colonnes sont mélangées d'un bloc (même tirage pour toutes),
    # moyennée sur les répétitions
    pertes = []
    for m, (_, validation) in zip(modeles, plis):
        X_val, y_val = X.iloc[validation], y[validation]
        reference = average_precision_score(y_val, m.predict_proba(X_val)[:, 1])
        perte = []
        for _ in range(REPETITIONS):
            melange = X_val.copy()
            ordre_melange = generateur.permutation(len(melange))
            melange[colonnes] = melange[colonnes].to_numpy()[ordre_melange]
            perte.append(reference - average_precision_score(y_val, m.predict_proba(melange)[:, 1]))
        pertes.append(np.mean(perte))
    return pertes


for population, e in ETUDE.items():
    activer(population)
    pertes = {}
    for (variante, nom), modeles in e["modeles_plis"].items():
        X = original[COLONNES_VARIANTE[variante]].reset_index(drop=True)
        for famille, colonnes in FAMILLES.items():
            presentes = [c for c in colonnes if c in X.columns]
            if presentes:
                pertes[(variante, nom, famille)] = np.mean(perte_par_permutation(modeles, X, presentes))
    cles = list(dict.fromkeys((v, n) for v, n, _ in pertes))
    tableau = pd.DataFrame({cle: {f: pertes[(*cle, f)] for f in FAMILLES if (*cle, f) in pertes} for cle in cles})
    part = tableau.clip(lower=0) / tableau.clip(lower=0).sum() * 100
    display(Markdown(f"**{population} : part de chaque famille dans la perte de précision moyenne (%)**"))
    display(part.round(1).rename_axis(index="Famille", columns=["Variante", "Modèle"]))

**En incident : part de chaque famille dans la perte de précision moyenne (%)**

Variante                         Complet                                            PAY_n seuls                                         Sans les PAY_n
Modèle                LogisticRegression MLPClassifier RandomForest CatBoost LogisticRegression MLPClassifier RandomForest CatBoost LogisticRegression MLPClassifier RandomForest CatBoost
Famille
Codifications (PAY_n)               83.5          57.0         69.7     71.9              100.0         100.0        100.0    100.0                NaN           NaN          NaN      NaN
Factures (BILL_AMTn)                 1.1           5.4         10.9      7.3                NaN           NaN          NaN      NaN               10.2          11.7         34.5     27.7
Paiements (PAY_AMTn)                 6.7          21.8          9.7     13.5                NaN           NaN          NaN      NaN               77.3          75.0         55.7     64.0
Plafond (LIMIT_BAL)                  0.0           3.0          0.8      0.1                NaN           NaN          NaN      NaN                0.5           0.0          0.3      0.1
Démographie                          8.7          12.8          8.9      7.1                NaN           NaN          NaN      NaN               12.0          13.3          9.5      8.2

**Retard imminent : part de chaque famille dans la perte de précision moyenne (%)**

Variante                         Complet                                            PAY_n seuls                                         Sans les PAY_n
Modèle                LogisticRegression MLPClassifier RandomForest CatBoost LogisticRegression MLPClassifier RandomForest CatBoost LogisticRegression MLPClassifier RandomForest CatBoost
Famille
Codifications (PAY_n)               25.4          15.8          0.0     66.6              100.0         100.0        100.0    100.0                NaN           NaN          NaN      NaN
Factures (BILL_AMTn)                23.9          22.1         76.3      8.9                NaN           NaN          NaN      NaN               56.7          42.1         53.2     51.5
Paiements (PAY_AMTn)                38.7          33.9          0.0     19.2                NaN           NaN          NaN      NaN               27.2          32.8          7.6     48.5
Plafond (LIMIT_BAL)                  2.9          13.0          2.6      1.0                NaN           NaN          NaN      NaN                0.0           9.9          7.3      0.0
Démographie                          9.1          15.2         21.1      4.3                NaN           NaN          NaN      NaN               16.1          15.3         31.9      0.0

**Autres clients : part de chaque famille dans la perte de précision moyenne (%)**

Variante                         Complet                                            PAY_n seuls                                         Sans les PAY_n
Modèle                LogisticRegression MLPClassifier RandomForest CatBoost LogisticRegression MLPClassifier RandomForest CatBoost LogisticRegression MLPClassifier RandomForest CatBoost
Famille
Codifications (PAY_n)               29.3          27.5         50.9     49.3              100.0         100.0        100.0    100.0                NaN           NaN          NaN      NaN
Factures (BILL_AMTn)                10.8           9.6          2.1      9.7                NaN           NaN          NaN      NaN               21.3          22.2         12.0     25.1
Paiements (PAY_AMTn)                40.6          44.7         38.2     20.7                NaN           NaN          NaN      NaN               57.3          55.6         66.8     51.7
Plafond (LIMIT_BAL)                 15.3          15.4          8.4     17.0                NaN           NaN          NaN      NaN               15.8          17.9         18.2     19.8
Démographie                          4.1           2.9          0.3      3.3                NaN           NaN          NaN      NaN                5.6           4.2          3.0      3.4

## 5. Comparaison unitaire : le modèle des autres clients face aux scénarios, sur les mêmes clients

Seule comparaison directe avec le travail mené dans les scénarios : les probabilités hors pli du modèle des autres clients, restreintes aux **clients du train ML** et découpées selon **les 5 plis des scénarios**, face aux probabilités hors pli enregistrées par `ml_4` (référence des scénarios) et `ml_17` (entraînement final). Mesure des scénarios : le **score décisionnel F2 au rappel minimal de 60 %**, pli par pli ; même verdict. Les deux côtés n'ont ni population en incident ni retard imminent ; le modèle de l'essai a cependant appris aussi sur les clients du test du ML et sur ceux hors du périmètre du ML, avec les 23 colonnes d'origine seulement, quand les scénarios ajoutent des colonnes construites. Les populations de la règle n'ont pas d'équivalent dans les scénarios : leur comparaison unitaire se lit avec la règle, en section 6.

In [12]:
from sklearn.metrics import fbeta_score

def f2_au_rappel_minimal(y_vrai, proba):
    return fbeta_score(y_vrai, proba >= seuil_pour_rappel(y_vrai, proba), beta=2)

def verdict(gains):
    moyenne, ecart_type = np.mean(gains), np.std(gains)
    return "✅ gain réel" if moyenne > ecart_type else ("❌ perte" if moyenne < -ecart_type else "➖ dans le bruit")

activer("Autres clients")
probas = ETUDE["Autres clients"]["probas"]
# ==============================================================================
# SCÉNARIOS COMPARÉS : numéros des scénarios dont les probabilités hors pli (méthode v9) sont lues
# ==============================================================================
SCENARIOS_COMPARES = ["4", "17"]   # ml_4 : référence des scénarios ; ml_17 : entraînement final
VERSION_METHODE = "v9"

dossier_probas = root_dir / "data" / "ML" / "probas_hors_pli"
train_ml = pd.read_csv(root_dir / "data" / "ML" / "train_dataset.csv", usecols=["ID", "dpnm"])
y_ml = train_ml["dpnm"].to_numpy()
plis_ml = list(cv.split(train_ml, train_ml["dpnm"]))   # les 5 plis des scénarios (même ordre des clients, même graine)

# Probabilités hors pli du jeu des autres clients, restreintes aux clients du train ML, dans l'ordre du train ML
position = pd.Series(np.arange(len(original)), index=original["ID"])
assert train_ml["ID"].isin(position.index).all(), "Des clients du train ML manquent dans le jeu des autres clients"
lignes_ml = position.loc[train_ml["ID"]].to_numpy()
assert (y[lignes_ml] == y_ml).all(), "Cible différente entre le jeu des autres clients et le train ML"

f2_ml = {}   # (source, modèle) -> F2 sur les 5 plis des scénarios
for (variante, nom), p in probas.items():
    p_ml = p[lignes_ml]
    f2_ml[(f"Autres clients, {variante}", nom)] = [f2_au_rappel_minimal(y_ml[val], p_ml[val]) for _, val in plis_ml]

for numero in SCENARIOS_COMPARES:
    ref = pd.read_csv(dossier_probas / f"ml_{numero}_{VERSION_METHODE}.csv").set_index("ID").loc[train_ml["ID"]]
    assert (ref["dpnm"].to_numpy() == y_ml).all(), f"Probabilités de ml_{numero} non alignées sur le train ML"
    for nom in [m for m in MODELES_A_TESTER if m in ref.columns]:
        f2_ml[(f"ml_{numero}", nom)] = [f2_au_rappel_minimal(y_ml[val], ref[nom].to_numpy()[val]) for _, val in plis_ml]

sources = list(dict.fromkeys(source for source, _ in f2_ml))
tableau = pd.DataFrame({source: {nom: f"{np.mean(f2_ml[(source, nom)]):.3f} ± {np.std(f2_ml[(source, nom)]):.3f}"
                                 for nom in MODELES_A_TESTER if (source, nom) in f2_ml} for source in sources}).T
display(Markdown(f"**Lecture 1 : sur les {len(train_ml)} clients du train ML, plis des scénarios** (score décisionnel F2 ± écart-type sur les plis ; "
                 f"taux de défaut {y_ml.mean() * 100:.1f} %)"))
display(tableau.rename_axis("Source"))

**Lecture 1 : sur les 17967 clients du train ML, plis des scénarios** (score décisionnel F2 ± écart-type sur les plis ; taux de défaut 13.8 %)

                               LogisticRegression  MLPClassifier   RandomForest       CatBoost
Source
Autres clients, Complet             0.442 ± 0.005  0.437 ± 0.005  0.429 ± 0.011  0.445 ± 0.007
Autres clients, PAY_n seuls         0.410 ± 0.011  0.414 ± 0.003  0.410 ± 0.007  0.409 ± 0.010
Autres clients, Sans les PAY_n      0.435 ± 0.004  0.426 ± 0.005  0.420 ± 0.010  0.438 ± 0.005
ml_4                                0.449 ± 0.007  0.446 ± 0.010  0.444 ± 0.009  0.452 ± 0.009
ml_17                               0.449 ± 0.010  0.446 ± 0.012            NaN  0.451 ± 0.009

In [13]:
def meilleur_de(source):
    return max([nom for s, nom in f2_ml if s == source], key=lambda nom: np.mean(f2_ml[(source, nom)]))

lignes = []
for variante in VARIANTES:
    source = f"Autres clients, {variante}"
    for numero in SCENARIOS_COMPARES:
        scenario = f"ml_{numero}"
        paires = [(nom, nom) for nom in MODELES_A_TESTER if (scenario, nom) in f2_ml] + [(meilleur_de(scenario), meilleur_de(source))]
        for i, (nom_ref, nom_base) in enumerate(paires):
            gains = np.array(f2_ml[(source, nom_base)]) - np.array(f2_ml[(scenario, nom_ref)])
            lignes.append({
                "Autres clients": variante,
                "Face à": scenario,
                "Modèle": nom_ref if i < len(paires) - 1 else f"Meilleur contre meilleur ({nom_ref} → {nom_base})",
                "F2 scénario": round(np.mean(f2_ml[(scenario, nom_ref)]), 3),
                "F2 jeu des autres clients": round(np.mean(f2_ml[(source, nom_base)]), 3),
                "Gain du jeu des autres clients": f"{gains.mean():+.3f} ± {gains.std():.3f}",
                "Plis gagnés": f"{(gains > 0).sum()} sur 5",
                "Verdict": verdict(gains),
            })
display(Markdown("**Lecture 1 : le jeu des autres clients face aux scénarios, pli par pli, sur les mêmes clients**"))
display(pd.DataFrame(lignes).set_index(["Autres clients", "Face à", "Modèle"]))

**Lecture 1 : le jeu des autres clients face aux scénarios, pli par pli, sur les mêmes clients**

                                                                           F2 scénario  F2 jeu des autres clients Gain du jeu des autres clients Plis gagnés          Verdict
Autres clients Face à Modèle
Complet        ml_4   LogisticRegression                                         0.449                      0.442                 -0.007 ± 0.008     1 sur 5  ➖ dans le bruit
                      MLPClassifier                                              0.446                      0.437                 -0.009 ± 0.011     1 sur 5  ➖ dans le bruit
                      RandomForest                                               0.444                      0.429                 -0.015 ± 0.009     0 sur 5          ❌ perte
                      CatBoost                                                   0.452                      0.445                 -0.007 ± 0.004     0 sur 5          ❌ perte
                      Meilleur contre meilleur (CatBoost → CatBoost)             0.452                      0.445                 -0.007 ± 0.004     0 sur 5          ❌ perte
               ml_17  LogisticRegression                                         0.449                      0.442                 -0.007 ± 0.011     1 sur 5  ➖ dans le bruit
                      MLPClassifier                                              0.446                      0.437                 -0.008 ± 0.013     2 sur 5  ➖ dans le bruit
                      CatBoost                                                   0.451                      0.445                 -0.006 ± 0.005     1 sur 5          ❌ perte
                      Meilleur contre meilleur (CatBoost → CatBoost)             0.451                      0.445                 -0.006 ± 0.005     1 sur 5          ❌ perte
PAY_n seuls    ml_4   LogisticRegression                                         0.449                      0.410                 -0.039 ± 0.014     0 sur 5          ❌ perte
                      MLPClassifier                                              0.446                      0.414                 -0.032 ± 0.012     0 sur 5          ❌ perte
                      RandomForest                                               0.444                      0.410                 -0.033 ± 0.005     0 sur 5          ❌ perte
                      CatBoost                                                   0.452                      0.409                 -0.042 ± 0.009     0 sur 5          ❌ perte
                      Meilleur contre meilleur (CatBoost → MLPClassifier)        0.452                      0.414                 -0.038 ± 0.009     0 sur 5          ❌ perte
               ml_17  LogisticRegression                                         0.449                      0.410                 -0.039 ± 0.017     0 sur 5          ❌ perte
                      MLPClassifier                                              0.446                      0.414                 -0.032 ± 0.015     0 sur 5          ❌ perte
                      CatBoost                                                   0.451                      0.409                 -0.042 ± 0.012     0 sur 5          ❌ perte
                      Meilleur contre meilleur (CatBoost → MLPClassifier)        0.451                      0.414                 -0.037 ± 0.010     0 sur 5          ❌ perte
Sans les PAY_n ml_4   LogisticRegression                                         0.449                      0.435                 -0.014 ± 0.007     0 sur 5          ❌ perte
                      MLPClassifier                                              0.446                      0.426                 -0.020 ± 0.007     0 sur 5          ❌ perte
                      RandomForest                                               0.444                      0.420                 -0.024 ± 0.008     0 sur 5          ❌ perte
                      CatBoost                                                   0.452                      0.438                 -0.013 ± 0.008     1 sur 5          ❌ perte
                      Meilleur contre meilleur (CatBoost → CatBoost)             0.452                      0.438                 -0.013 ± 0.008     1 sur 5          ❌ perte
               ml_17  LogisticRegression                                         0.449                      0.435                 -0.013 ± 0.009     1 sur 5          ❌ perte
                      MLPClassifier                                              0.446                      0.426                 -0.019 ± 0.011     1 sur 5          ❌ perte
                      CatBoost                                                   0.451                      0.438                 -0.013 ± 0.008     1 sur 5          ❌ perte
                      Meilleur contre meilleur (CatBoost → CatBoost)             0.451                      0.438                 -0.013 ± 0.008     1 sur 5          ❌ perte

## 6. Synthèse globale : résultats accumulés sur tous les clients du niveau 3

Chaque client reçoit la décision (et la probabilité) de sa population, hors pli. Le **meilleur modèle** de chaque population est celui de la variante choisie qui a la plus haute précision moyenne hors pli (règle fixée avant de lancer). Les mesures portent sur **tous les clients** : défauts détectés (nombre et part de tous les défauts), clients signalés, précision des défauts prédits, fausses alertes, défauts manqués, taux d'erreur (fausses alertes et défauts manqués, sur tous les clients), et ratio d'aire (Yeh et Lien : aire entre la courbe de gain et la diagonale, rapportée à celle de la courbe parfaite ; il vaut 2 × ROC AUC − 1).

Pour le ratio d'aire, les clients sont triés par une note : la règle place la population en incident et le retard imminent en tête ; « trois ML » trie tous les clients par la probabilité de leur modèle (trois modèles différents : probabilités pas tout à fait comparables, ratio indicatif).

In [14]:
from sklearn.metrics import roc_auc_score

def meilleur_modele(population, variante):
    e = ETUDE[population]
    return max([n for v, n in e["probas"] if v == variante], key=lambda n: average_precision_score(POPULATIONS[population]["dpnm"], e["probas"][(variante, n)]))

def vecteurs(population, variante):
    # Probabilités et décisions hors pli du meilleur modèle d'une population, rangées par identifiant client
    nom = meilleur_modele(population, variante)
    ids = POPULATIONS[population]["ID"].to_numpy()
    return nom, pd.Series(ETUDE[population]["probas"][(variante, nom)], index=ids), pd.Series(ETUDE[population]["decisions"][(variante, nom)], index=ids)

ids_tous = niveau_3["ID"].to_numpy()
y_tous = niveau_3["dpnm"].to_numpy()

MODELE = {population: vecteurs(population, "Complet") for population in POPULATIONS}   # population -> (nom, probas, décisions)
nom_autres, p_autres, d_autres = MODELE["Autres clients"]
nom_autres_sp, p_autres_sp, d_autres_sp = vecteurs("Autres clients", "Sans les PAY_n")

def assembler(dec, note):
    # dec, note : population -> série rangée par identifiant client ; renvoie une décision et une note par client, dans l'ordre de niveau_3
    return (pd.concat(dec.values()).reindex(ids_tous).to_numpy().astype(int),
            pd.concat(note.values()).reindex(ids_tous).to_numpy())

ids = {population: d["ID"] for population, d in POPULATIONS.items()}
un = lambda i: pd.Series(1, index=i)
zero = lambda i: pd.Series(0, index=i)
dec_regle = {p: un(ids[p]) for p in STATUTS_REGLE}
note_regle = {p: un(ids[p]) * 2.0 for p in STATUTS_REGLE}   # la règle en tête du tri
STRATEGIES = {
    "1. Règle seule (en incident et retard imminent en défaut)": assembler({**dec_regle, "Autres clients": zero(ids["Autres clients"])},
                                                                         {**note_regle, "Autres clients": zero(ids["Autres clients"]) * 1.0}),
    f"2. Règle + ML autres clients ({nom_autres})": assembler({**dec_regle, "Autres clients": d_autres}, {**note_regle, "Autres clients": p_autres}),
    f"3. Règle + ML autres clients sans les PAY_n ({nom_autres_sp})": assembler({**dec_regle, "Autres clients": d_autres_sp},
                                                                               {**note_regle, "Autres clients": p_autres_sp}),
    "4. Trois ML (" + ", ".join(f"{MODELE[p][0]} {p.lower()}" for p in POPULATIONS) + ")": assembler({p: MODELE[p][2] for p in POPULATIONS},
                                                                                                  {p: MODELE[p][1] for p in POPULATIONS}),
}
# 5. Un seul ML sur tous les clients : décisions enregistrées par essai_jeu_corrige.ipynb (cellule d'enregistrement)
fichier_un_ml = root_dir / "data" / "ML" / "comparatif_global" / "jeu_corrige.csv"
if fichier_un_ml.exists():
    un_ml = pd.read_csv(fichier_un_ml).set_index("ID").loc[ids_tous]
    noms = sorted({c.split(" | ")[2] for c in un_ml.columns if c.startswith("proba | Complet |")})
    nom_un = max(noms, key=lambda n: average_precision_score(y_tous, un_ml[f"proba | Complet | {n}"]))
    STRATEGIES[f"5. Un seul ML sur tous les clients ({nom_un})"] = (un_ml[f"decision | Complet | {nom_un}"].to_numpy().astype(int), un_ml[f"proba | Complet | {nom_un}"].to_numpy())
else:
    display(Markdown("⚠️ Stratégie 5 absente : lancer `essai_jeu_corrige.ipynb` avec sa cellule d'enregistrement (fin de la section 4)."))

def ratio_aire(y_vrai, note):
    n, d = len(y_vrai), y_vrai.sum()
    cumul = np.cumsum(y_vrai[np.argsort(-note, kind="mergesort")])
    diagonale = d * (n + 1) / 2
    return (cumul.sum() - diagonale) / (np.minimum(np.arange(1, n + 1), d).sum() - diagonale)

lignes = []
for nom, (dec, note) in STRATEGIES.items():
    signale = dec == 1
    detectes = (signale & (y_tous == 1)).sum()
    fausses = (signale & (y_tous == 0)).sum()
    manques = (~signale & (y_tous == 1)).sum()
    lignes.append({"Stratégie": nom, "Défauts détectés": detectes, "Part des défauts (%)": round(detectes / y_tous.sum() * 100, 1),
                   "Clients signalés": signale.sum(), "Part des clients signalés (%)": round(signale.mean() * 100, 1),
                   "Précision des défauts prédits (%)": round(detectes / signale.sum() * 100, 1) if signale.sum() else np.nan,
                   "Fausses alertes": fausses, "Défauts manqués": manques,
                   "Taux d'erreur": round((fausses + manques) / len(y_tous), 3), "Ratio d'aire": round(ratio_aire(y_tous, note), 3)})
lignes.append({"Stratégie": "Personne n'est signalé (repère)", "Défauts détectés": 0, "Part des défauts (%)": 0.0, "Clients signalés": 0,
               "Part des clients signalés (%)": 0.0, "Précision des défauts prédits (%)": np.nan, "Fausses alertes": 0,
               "Défauts manqués": y_tous.sum(), "Taux d'erreur": round(y_tous.mean(), 3), "Ratio d'aire": 0.0})
display(Markdown(f"**Résultats accumulés sur tous les clients du niveau 3** ({len(y_tous)} clients, {y_tous.sum()} défauts, taux de défaut {y_tous.mean() * 100:.1f} %)"))
display(pd.DataFrame(lignes).set_index("Stratégie"))

# Détail par population : d'où viennent les défauts détectés et les fausses alertes
detail = []
for nom, (dec, _) in STRATEGIES.items():
    for population, masque in MASQUES.items():
        s, yy = dec[masque] == 1, y_tous[masque]
        detail.append({"Stratégie": nom, "Population": population, "Défauts détectés": (s & (yy == 1)).sum(), "sur": yy.sum(),
                       "Fausses alertes": (s & (yy == 0)).sum(), "Précision (%)": round((s & (yy == 1)).sum() / s.sum() * 100, 1) if s.sum() else np.nan})
display(Markdown("**Détail par population**"))
display(pd.DataFrame(detail).set_index(["Stratégie", "Population"]))

# Comparatif avec l'étude d'origine : ses 6 méthodes (Tableau 1, en validation) et nos stratégies globales, sur les deux mesures qu'elle publie
YEH_LIEN = {   # méthode : (taux d'erreur, ratio d'aire), en validation
    "Réseau de neurones": (0.17, 0.54), "Arbre de classification": (0.17, 0.536), "Bayésien naïf": (0.21, 0.53),
    "KNN": (0.16, 0.45), "Régression logistique": (0.18, 0.44), "Analyse discriminante": (0.26, 0.43),
}
comparatif = [{"Source": "Yeh et Lien (2009)", "Méthode ou stratégie": m, "Taux d'erreur": e, "Ratio d'aire": a,
               "Périmètre": "fichier brut, tous les clients", "Découpage": "un seul (entraînement / validation)"} for m, (e, a) in YEH_LIEN.items()]
comparatif += [{"Source": "Cet essai", "Méthode ou stratégie": l["Stratégie"], "Taux d'erreur": l["Taux d'erreur"], "Ratio d'aire": l["Ratio d'aire"],
                "Périmètre": f"niveau 3 ({len(y_tous)} clients)", "Découpage": "validation croisée à 5 plis (décisions hors pli)"} for l in lignes]
display(Markdown("**Comparatif avec l'étude d'origine (Yeh et Lien, 2009, Tableau 1, en validation)** : taux d'erreur et ratio d'aire, "
                 "les deux seules mesures qu'elle publie (ni rappel ni précision)"))
display(pd.DataFrame(comparatif).set_index(["Source", "Méthode ou stratégie"]))
display(Markdown(
    "**Périmètres différents, et pourquoi c'est défendable** : l'étude d'origine travaille sur le fichier brut ; cet essai, sur le niveau 3 du nettoyage, "
    "qui retire les paiements géants (montants hors de toute proportion avec le plafond), les comptes inactifs (aucune facture positive sur les six mois "
    "et aucun paiement de mai à septembre : rien à prédire sur leur comportement de paiement) et les plafonds atypiques (au-delà de 500 000 NT$, "
    "une clientèle à part), et corrige les codifications `PAY_n`. Ces retraits sont justifiés par le métier au nettoyage, jamais par leur effet sur un score. "
    "La comparaison reste **indicative** : clients, découpage et taux de défaut diffèrent, et les chiffres de l'étude sont arrondis au centième. "
    "Elle montre où se situe chaque stratégie par rapport à la référence publiée sur ces données."))

# Décisions client par client, pour l'accumulation ultérieure
# population : celle de chaque client ; regle : 1 si la règle métier le déclare en défaut (en incident à M ou retard imminent)
sortie = pd.DataFrame({"ID": ids_tous, "dpnm": y_tous, "population": statut.where(regle, "Autres clients").to_numpy(), "regle": regle.astype(int)})
for nom, (dec, note) in STRATEGIES.items():
    sortie[f"decision | {nom}"] = dec
    sortie[f"note | {nom}"] = note
dossier_sortie = root_dir / "data" / "ML" / "comparatif_global"
dossier_sortie.mkdir(parents=True, exist_ok=True)
sortie.to_csv(dossier_sortie / "jeu_corrige_deux_populations.csv", index=False)
print(f"Décisions enregistrées : {dossier_sortie / 'jeu_corrige_deux_populations.csv'}")

**Résultats accumulés sur tous les clients du niveau 3** (28851 clients, 6272 défauts, taux de défaut 21.7 %)

,Défauts détectés,Part des défauts (%),Clients signalés,Part des clients signalés (%),Précision des défauts prédits (%),Fausses alertes,Défauts manqués,Taux d'erreur,Ratio d'aire
Stratégie,,,,,,,,,
1. Règle seule (en incident et retard imminent en défaut),2871,45.8,4743,16.4,60.5,1872,3401,0.183,0.394
2. Règle + ML autres clients (CatBoost),2871,45.8,4745,16.4,60.5,1874,3401,0.183,0.550
3. Règle + ML autres clients sans les PAY_n (CatBoost),2877,45.9,4753,16.5,60.5,1876,3395,0.183,0.539
"4. Trois ML (CatBoost en incident, MLPClassifier retard imminent, CatBoost autres clients)",2868,45.7,4738,16.4,60.5,1870,3404,0.183,0.389
5. Un seul ML sur tous les clients (CatBoost),2527,40.3,4010,13.9,63.0,1483,3745,0.181,0.565
Personne n'est signalé (repère),0,0.0,0,0.0,NaN,0,6272,0.217,0.000

**Détail par population**

                                                                                                            Défauts détectés   sur  Fausses alertes  Précision (%)
Stratégie                                                                                  Population
1. Règle seule (en incident et retard imminent en défaut)                                  En incident                  2222  2222             1532           59.2
                                                                                           Retard imminent               649   649              340           65.6
                                                                                           Autres clients                  0  3401                0            NaN
2. Règle + ML autres clients (CatBoost)                                                    En incident                  2222  2222             1532           59.2
                                                                                           Retard imminent               649   649              340           65.6
                                                                                           Autres clients                  0  3401                2            0.0
3. Règle + ML autres clients sans les PAY_n (CatBoost)                                     En incident                  2222  2222             1532           59.2
                                                                                           Retard imminent               649   649              340           65.6
                                                                                           Autres clients                  6  3401                4           60.0
4. Trois ML (CatBoost en incident, MLPClassifier retard imminent, CatBoost autres clients) En incident                  2222  2222             1530           59.2
                                                                                           Retard imminent               646   649              338           65.7
                                                                                           Autres clients                  0  3401                2            0.0
5. Un seul ML sur tous les clients (CatBoost)                                              En incident                  1913  2222             1153           62.4
                                                                                           Retard imminent               567   649              276           67.3
                                                                                           Autres clients                 47  3401               54           46.5

**Comparatif avec l'étude d'origine (Yeh et Lien, 2009, Tableau 1, en validation)** : taux d'erreur et ratio d'aire, les deux seules mesures qu'elle publie (ni rappel ni précision)

                                                                                                               Taux d'erreur  Ratio d'aire                       Périmètre                                         Découpage
Source             Méthode ou stratégie
Yeh et Lien (2009) Réseau de neurones                                                                                  0.170         0.540  fichier brut, tous les clients               un seul (entraînement / validation)
                   Arbre de classification                                                                             0.170         0.536  fichier brut, tous les clients               un seul (entraînement / validation)
                   Bayésien naïf                                                                                       0.210         0.530  fichier brut, tous les clients               un seul (entraînement / validation)
                   KNN                                                                                                 0.160         0.450  fichier brut, tous les clients               un seul (entraînement / validation)
                   Régression logistique                                                                               0.180         0.440  fichier brut, tous les clients               un seul (entraînement / validation)
                   Analyse discriminante                                                                               0.260         0.430  fichier brut, tous les clients               un seul (entraînement / validation)
Cet essai          1. Règle seule (en incident et retard imminent en défaut)                                           0.183         0.394        niveau 3 (28851 clients)  validation croisée à 5 plis (décisions hors pli)
                   2. Règle + ML autres clients (CatBoost)                                                             0.183         0.550        niveau 3 (28851 clients)  validation croisée à 5 plis (décisions hors pli)
                   3. Règle + ML autres clients sans les PAY_n (CatBoost)                                              0.183         0.539        niveau 3 (28851 clients)  validation croisée à 5 plis (décisions hors pli)
                   4. Trois ML (CatBoost en incident, MLPClassifier retard imminent, CatBoost autres clients)          0.183         0.389        niveau 3 (28851 clients)  validation croisée à 5 plis (décisions hors pli)
                   5. Un seul ML sur tous les clients (CatBoost)                                                       0.181         0.565        niveau 3 (28851 clients)  validation croisée à 5 plis (décisions hors pli)
                   Personne n'est signalé (repère)                                                                     0.217         0.000        niveau 3 (28851 clients)  validation croisée à 5 plis (décisions hors pli)

**Périmètres différents, et pourquoi c'est défendable** : l'étude d'origine travaille sur le fichier brut ; cet essai, sur le niveau 3 du nettoyage, qui retire les paiements géants (montants hors de toute proportion avec le plafond), les comptes inactifs (aucune facture positive sur les six mois et aucun paiement de mai à septembre : rien à prédire sur leur comportement de paiement) et les plafonds atypiques (au-delà de 500 000 NT$, une clientèle à part), et corrige les codifications `PAY_n`. Ces retraits sont justifiés par le métier au nettoyage, jamais par leur effet sur un score. La comparaison reste **indicative** : clients, découpage et taux de défaut diffèrent, et les chiffres de l'étude sont arrondis au centième. Elle montre où se situe chaque stratégie par rapport à la référence publiée sur ces données.

Décisions enregistrées : c:\Users\johan\VS Code Wild 2\PROJET_DEFAULT_CREDIT_CARD_ML\data\ML\comparatif_global\jeu_corrige_deux_populations.csv

**Comment lire** :
- **Défauts détectés et précision** : combien de défauts chaque stratégie récupère en tout, et à quel prix (fausses alertes). La règle seule donne le repère : les défauts de la population en incident et du retard imminent, sans modèle.
- **Règle + ML** (2 et 3) : ce que le modèle ajoute aux défauts de la règle, en ne signalant parmi les autres clients que la tête de liste (règle marginale). La stratégie 3 montre ce que le **comportement seul** (les montants, sans codification) ajoute à la règle.
- **Trois ML et un seul ML** (4 et 5) : si un modèle fait aussi bien que la règle dans ses deux populations, et si séparer les populations change quelque chose.
- **Comparatif avec l'étude d'origine** : nos stratégies face à ses 6 méthodes, sur ses deux mesures (taux d'erreur, ratio d'aire) ; indicatif (périmètre, découpage et taux de défaut différents), mais défendable : les clients retirés le sont pour des raisons métier. Le taux d'erreur ne dit pas combien de défauts sont trouvés : « personne n'est signalé » en donne le repère.

## 7. Conclusion : séparer la règle métier du reste

*Lancement du 12/10/2026 : `cleaned3`, trois populations lues dans `STATUT_INCIDENT`, encodage des scénarios actuels (codifications en catégories, plafond au logarithme).*

**1. Dans la population en incident à M et dans le retard imminent, aucun client ne peut être sorti de la règle** (section 3). Avec l'exigence métier (on ne sort un client que s'il a au moins 9 chances sur 10 d'être sain), tous les modèles, dans les trois variantes, gardent la quasi-totalité de chaque population en défaut. Ils y trient à peine mieux que le hasard : ROC AUC d'environ 0,6 en incident, de 0,53 à 0,63 en retard imminent. Le peu qu'ils trouvent passe surtout par les codifications ; sans elles, par les paiements en incident, et par les factures et les paiements en retard imminent, avec des parts qui changent beaucoup d'un modèle à l'autre (section 4). **La règle « toute la population en défaut » est la seule décision défendable avec ces données** ; les modèles la retrouvent d'eux-mêmes.

**2. Pour les autres clients, la règle « 1 pour 1 » ne signale presque personne** (section 3) : très peu de clients ont plus d'une chance sur deux de faire défaut ; les modèles signalent moins de 1 % des clients et n'attrapent qu'une très faible part des défauts. Le modèle **classe** ces clients (ROC AUC d'environ 0,65 à 0,68 dans la variante complète), mais à ce seuil il ne change presque aucune décision. Sur les clients du train ML (section 5), le meilleur modèle des autres clients, avec les seules 23 colonnes d'origine, reste un peu sous la version finale des scénarios (écart de quelques millièmes, régulier pour CatBoost, dans le bruit pour la régression logistique et le MLP) ; sans les `PAY_n`, l'écart grandit un peu ; avec les `PAY_n` seuls, la perte est nette.

**3. Résultats accumulés (sections 6 et 8).** La règle seule récupère déjà près de la moitié des défauts, avec environ six prédictions justes sur dix, en signalant environ un client sur six. Règle + ML (2 et 3) et trois ML (4) donnent presque exactement les mêmes décisions : le taux d'erreur ne bouge pas. Ce qui change, c'est la **qualité du tri** (ratio d'aire), nettement meilleure dès qu'un modèle range les autres clients. Le ratio d'aire de « trois ML » est indicatif : il trie ensemble les probabilités de trois modèles différents. **Un seul ML sur tous les clients** (5) trie un peu mieux encore et se trompe un peu moins souvent, mais trouve moins de défauts : il laisse partir une partie des clients de la règle en défaut, et n'en signale que peu parmi les autres.

**4. Face à l'étude d'origine** (comparaison indicative : périmètre, découpage, arrondis) : ratio d'aire au niveau de leur meilleure méthode ou un peu au-dessus dès qu'un modèle trie les autres clients ; taux d'erreur au niveau de leur régression logistique, un peu au-dessus de leurs meilleures méthodes.

**Ce que ça veut dire** : séparer les populations de la règle métier ne fait pas mieux prédire, mais c'est la décision la plus défendable pour elles : aucun modèle ne sait en sortir un client. Pour les autres clients, le modèle sert à les classer par niveau de risque, pas à décider à ce seuil.

**Réserves** : les modèles ont appris sur les clients du test du ML ; « dans le bruit » veut dire qu'on ne peut pas départager, pas que les scores sont identiques. Ces résultats éclairent la problématique, ils ne servent pas à choisir le modèle final. La comparaison avec la codification de la banque (`PAY_1` ≥ 2) est dans `essai_jeu_de_base_deux_populations.ipynb`, section 6.

## 8. Complément : la stratégie 5 (un seul ML), lue dans les fichiers enregistrés

Cette cellule est **autonome** : elle ne réentraîne rien et fonctionne même après une réinitialisation du noyau. Elle lit les décisions enregistrées par ce notebook et par l'essai à un seul modèle (`essai_jeu_corrige.ipynb`, cellule d'enregistrement), ajoute la stratégie 5 (meilleur modèle unique de la variante complète, choisi sur la précision moyenne hors pli) aux décisions enregistrées, puis refait la synthèse globale, le détail par population et le comparatif avec l'étude d'origine. **À lancer avant la cellule équivalente de `essai_jeu_de_base_deux_populations.ipynb`**, qui relit ce fichier.

La stratégie 5 garde sa propre règle : un seul modèle, une seule tolérance (1 pour 1) pour tous les clients ; sans séparation, la règle métier n'existe pas, et le modèle répond à la seule question « qui paiera, qui ne paiera pas ? ».

In [15]:
FICHIER_DEUX, FICHIER_UN, NOTEBOOK_UN = "jeu_corrige_deux_populations.csv", "jeu_corrige.csv", "essai_jeu_corrige.ipynb"
COLONNE_REGLE, NOMS_POPULATIONS = "regle", ("Règle (en incident à M, retard imminent)", "Autres clients")
PERIMETRE = "niveau 3, comparaison indicative : l'étude travaille sur le fichier brut"
# Complément : stratégie 5 (un seul ML sur tous les clients), lue dans les fichiers enregistrés ; cellule autonome, ne réentraîne rien
import numpy as np
import pandas as pd
from pathlib import Path
from IPython.display import Markdown, display
from sklearn.metrics import average_precision_score

root_dir = next(p for p in [Path.cwd()] + list(Path.cwd().parents) if (p / "data").exists())
dossier = root_dir / "data" / "ML" / "comparatif_global"
deux = pd.read_csv(dossier / FICHIER_DEUX).set_index("ID")
assert (dossier / FICHIER_UN).exists(), f"{FICHIER_UN} absent : lancer {NOTEBOOK_UN} avec sa cellule d'enregistrement"
un = pd.read_csv(dossier / FICHIER_UN).set_index("ID").loc[deux.index]
assert (un["dpnm"] == deux["dpnm"]).all(), "Cible différente entre les deux fichiers"

# Meilleur modèle unique de la variante complète : la plus haute précision moyenne hors pli (même règle que pour les autres stratégies)
noms = sorted({c.split(" | ")[2] for c in un.columns if c.startswith("proba | Complet |")})
nom_un = max(noms, key=lambda n: average_precision_score(un["dpnm"], un[f"proba | Complet | {n}"]))
libelle_5 = f"5. Un seul ML sur tous les clients ({nom_un})"
for c in [c for c in deux.columns if c.startswith(("decision | 5.", "note | 5."))]:
    deux = deux.drop(columns=c)
deux[f"decision | {libelle_5}"] = un[f"decision | Complet | {nom_un}"].astype(int)
deux[f"note | {libelle_5}"] = un[f"proba | Complet | {nom_un}"]
deux.reset_index().to_csv(dossier / FICHIER_DEUX, index=False)   # décisions enregistrées, stratégie 5 comprise

def ratio_aire(y_vrai, note):
    n, d = len(y_vrai), y_vrai.sum()
    cumul = np.cumsum(y_vrai[np.argsort(-note, kind="mergesort")])
    diagonale = d * (n + 1) / 2
    return (cumul.sum() - diagonale) / (np.minimum(np.arange(1, n + 1), d).sum() - diagonale)

def mesures(y, dec, note):
    signale = dec == 1
    detectes, fausses, manques = (signale & (y == 1)).sum(), (signale & (y == 0)).sum(), (~signale & (y == 1)).sum()
    return {"Défauts détectés": detectes, "Part des défauts (%)": round(detectes / y.sum() * 100, 1), "Clients signalés": signale.sum(),
            "Part des clients signalés (%)": round(signale.mean() * 100, 1),
            "Précision des défauts prédits (%)": round(detectes / signale.sum() * 100, 1) if signale.sum() else np.nan,
            "Fausses alertes": fausses, "Défauts manqués": manques, "Taux d'erreur": round((fausses + manques) / len(y), 3),
            "Ratio d'aire": round(ratio_aire(y, note), 3)}

y = deux["dpnm"].to_numpy()
strategies = [c.removeprefix("decision | ") for c in deux.columns if c.startswith("decision | ")]
lignes = [{"Stratégie": s, **mesures(y, deux[f"decision | {s}"].to_numpy(), deux[f"note | {s}"].to_numpy())} for s in strategies]
display(Markdown(f"**Résultats accumulés, stratégie 5 comprise** ({len(y)} clients, {y.sum()} défauts, taux de défaut {y.mean() * 100:.1f} %)"))
display(pd.DataFrame(lignes).set_index("Stratégie"))

regle = deux[COLONNE_REGLE].to_numpy() == 1
detail = []
for s in strategies:
    dec = deux[f"decision | {s}"].to_numpy() == 1
    for population, masque in ((NOMS_POPULATIONS[0], regle), (NOMS_POPULATIONS[1], ~regle)):
        ss, yy = dec[masque], y[masque]
        detail.append({"Stratégie": s, "Population": population, "Défauts détectés": (ss & (yy == 1)).sum(), "sur": yy.sum(),
                       "Fausses alertes": (ss & (yy == 0)).sum(), "Précision (%)": round((ss & (yy == 1)).sum() / ss.sum() * 100, 1) if ss.sum() else np.nan})
display(Markdown("**Détail par population, stratégie 5 comprise**"))
display(pd.DataFrame(detail).set_index(["Stratégie", "Population"]))

YEH_LIEN = {"Réseau de neurones": (0.17, 0.54), "Arbre de classification": (0.17, 0.536), "Bayésien naïf": (0.21, 0.53),
            "KNN": (0.16, 0.45), "Régression logistique": (0.18, 0.44), "Analyse discriminante": (0.26, 0.43)}
comparatif = [{"Source": "Yeh et Lien (2009)", "Méthode ou stratégie": m, "Taux d'erreur": e, "Ratio d'aire": a} for m, (e, a) in YEH_LIEN.items()]
comparatif += [{"Source": "Cet essai", "Méthode ou stratégie": l["Stratégie"], "Taux d'erreur": l["Taux d'erreur"], "Ratio d'aire": l["Ratio d'aire"]} for l in lignes]
display(Markdown(f"**Comparatif avec l'étude d'origine, stratégie 5 comprise** ({PERIMETRE})"))
display(pd.DataFrame(comparatif).set_index(["Source", "Méthode ou stratégie"]))

**Résultats accumulés, stratégie 5 comprise** (28851 clients, 6272 défauts, taux de défaut 21.7 %)

,Défauts détectés,Part des défauts (%),Clients signalés,Part des clients signalés (%),Précision des défauts prédits (%),Fausses alertes,Défauts manqués,Taux d'erreur,Ratio d'aire
Stratégie,,,,,,,,,
1. Règle seule (en incident et retard imminent en défaut),2871,45.8,4743,16.4,60.5,1872,3401,0.183,0.394
2. Règle + ML autres clients (CatBoost),2871,45.8,4745,16.4,60.5,1874,3401,0.183,0.550
3. Règle + ML autres clients sans les PAY_n (CatBoost),2877,45.9,4753,16.5,60.5,1876,3395,0.183,0.539
"4. Trois ML (CatBoost en incident, MLPClassifier retard imminent, CatBoost autres clients)",2868,45.7,4738,16.4,60.5,1870,3404,0.183,0.389
5. Un seul ML sur tous les clients (CatBoost),2527,40.3,4010,13.9,63.0,1483,3745,0.181,0.565

**Détail par population, stratégie 5 comprise**

                                                                                                                                     Défauts détectés   sur  Fausses alertes  Précision (%)
Stratégie                                                                                  Population
1. Règle seule (en incident et retard imminent en défaut)                                  Règle (en incident à M, retard imminent)              2871  2871             1872           60.5
                                                                                           Autres clients                                           0  3401                0            NaN
2. Règle + ML autres clients (CatBoost)                                                    Règle (en incident à M, retard imminent)              2871  2871             1872           60.5
                                                                                           Autres clients                                           0  3401                2            0.0
3. Règle + ML autres clients sans les PAY_n (CatBoost)                                     Règle (en incident à M, retard imminent)              2871  2871             1872           60.5
                                                                                           Autres clients                                           6  3401                4           60.0
4. Trois ML (CatBoost en incident, MLPClassifier retard imminent, CatBoost autres clients) Règle (en incident à M, retard imminent)              2868  2871             1868           60.6
                                                                                           Autres clients                                           0  3401                2            0.0
5. Un seul ML sur tous les clients (CatBoost)                                              Règle (en incident à M, retard imminent)              2480  2871             1429           63.4
                                                                                           Autres clients                                          47  3401               54           46.5

**Comparatif avec l'étude d'origine, stratégie 5 comprise** (niveau 3, comparaison indicative : l'étude travaille sur le fichier brut)

                                                                                                               Taux d'erreur  Ratio d'aire
Source             Méthode ou stratégie
Yeh et Lien (2009) Réseau de neurones                                                                                  0.170         0.540
                   Arbre de classification                                                                             0.170         0.536
                   Bayésien naïf                                                                                       0.210         0.530
                   KNN                                                                                                 0.160         0.450
                   Régression logistique                                                                               0.180         0.440
                   Analyse discriminante                                                                               0.260         0.430
Cet essai          1. Règle seule (en incident et retard imminent en défaut)                                           0.183         0.394
                   2. Règle + ML autres clients (CatBoost)                                                             0.183         0.550
                   3. Règle + ML autres clients sans les PAY_n (CatBoost)                                              0.183         0.539
                   4. Trois ML (CatBoost en incident, MLPClassifier retard imminent, CatBoost autres clients)          0.183         0.389
                   5. Un seul ML sur tous les clients (CatBoost)                                                       0.181         0.565