# Niveaux de risque sur tout le portefeuille : version finale et essais, sur la même grille

**But** : présenter, sur la **même grille de lecture**, les niveaux de risque de trois approches, chacune sur **tous ses clients** (et non sur un échantillon), puis sur les **clients communs aux trois** :
1. **version finale du ML** (`ml_17`) : règle métier (population en incident à M, retard imminent), puis CatBoost de `ml_17` pour les autres clients (`evaluation_finale_test.ipynb`, section 6 : train en hors pli, test par le modèle de décision) ;
2. **séparation par la règle métier, jeu corrigé** (`essai_jeu_corrige_deux_populations.ipynb`) : population en incident à M et retard imminent en défaut, puis le modèle des autres clients (23 colonnes d'origine) ;
3. **séparation par la codification de la banque, jeu de base** (`essai_jeu_de_base_deux_populations.ipynb`) : `PAY_1` ≥ 2 en défaut, puis le modèle pour les autres.

Pour les deux essais, deux versions : le modèle sur les 23 colonnes, et le modèle **sans les `PAY_n`** (le comportement seul).

**Niveaux** : 1. la règle (population en incident à M et retard imminent, ou `PAY_1` ≥ 2) ; 2. **haut risque** : au-dessus du seuil qui détecte 30 % des défauts des autres clients ; 3. **risque modéré** : jusqu'au seuil qui en détecte 60 % ; 4. **risque faible** : le reste. Pour `ml_17`, les seuils sont ceux du train (évaluation finale : ses tranches de 10 % des défauts sont regroupées, 0 à 30 % en haut risque, 30 à 60 % en risque modéré) ; pour les essais, ils sont calculés sur leurs probabilités hors pli. Tableaux **descriptifs** : chaque client est classé par un modèle qui ne l'a pas vu, mais seule l'évaluation finale (section 5) est une mesure sur un test jamais utilisé.

**Ce notebook ne réentraîne rien** : il lit les fichiers enregistrés par les trois notebooks (`data/ML/comparatif_global/`). Les périmètres diffèrent (périmètre du ML, niveau 3, fichier brut) : d'où la seconde partie, sur les clients communs.

In [1]:
import numpy as np
import pandas as pd
from pathlib import Path
from IPython.display import Markdown, display

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 250)
current_dir = Path.cwd()
root_dir = next(p for p in [current_dir] + list(current_dir.parents) if (p / "data").exists())
dossier = root_dir / "data" / "ML" / "comparatif_global"

def seuil_pour_rappel(y, p, rappel):
    proba_defauts = np.sort(p[y == 1])[::-1]
    return proba_defauts[int(np.ceil(rappel * len(proba_defauts))) - 1]

def niveaux_essai(fichier, colonne_regle, prefixe_strategie):
    # Niveaux d'un essai : la règle, puis les notes du modèle (probabilités hors pli) pour les autres clients, bornes à 30 % et 60 % de rappel
    d = pd.read_csv(dossier / fichier)
    col = next(c for c in d.columns if c.startswith(f"note | {prefixe_strategie}"))
    regle = d[colonne_regle] == 1
    y_autres, p_autres = d.loc[~regle, "dpnm"].to_numpy(), d.loc[~regle, col].to_numpy()
    s30, s60 = seuil_pour_rappel(y_autres, p_autres, 0.30), seuil_pour_rappel(y_autres, p_autres, 0.60)
    niveau = np.where(regle, "1. Règle", np.where(d[col] >= s30, "2. Haut risque", np.where(d[col] >= s60, "3. Risque modéré", "4. Risque faible")))
    return pd.DataFrame({"ID": d["ID"], "dpnm": d["dpnm"], "niveau": niveau}), col.removeprefix("note | ")

SOURCES = {}
f17 = dossier / "ml_17_global.csv"
if f17.exists():
    g = pd.read_csv(f17)
    # Niveaux de l'évaluation finale (deux règles, six tranches de 10 % des défauts du train, non signalés) regroupés sur la grille de ce notebook
    GRILLE_ML_17 = {"1. En incident (règle)": "1. Règle", "2. Retard imminent (règle)": "1. Règle",
                    "3. Tranche 1 (0 à 10 % des défauts)": "2. Haut risque", "4. Tranche 2 (10 à 20 % des défauts)": "2. Haut risque",
                    "5. Tranche 3 (20 à 30 % des défauts)": "2. Haut risque", "6. Tranche 4 (30 à 40 % des défauts)": "3. Risque modéré",
                    "7. Tranche 5 (40 à 50 % des défauts)": "3. Risque modéré", "8. Tranche 6 (50 à 60 % des défauts)": "3. Risque modéré",
                    "9. Non signalés": "4. Risque faible"}
    assert set(g["niveau"]) <= set(GRILLE_ML_17), f"Niveaux inattendus dans ml_17_global.csv : {set(g['niveau']) - set(GRILLE_ML_17)}"
    SOURCES["Version finale ml_17 (règle métier + CatBoost de ml_17)"] = pd.DataFrame(
        {"ID": g["ID"], "dpnm": g["dpnm"], "niveau": g["niveau"].map(GRILLE_ML_17)})
else:
    display(Markdown("⚠️ `ml_17_global.csv` absent : exécuter la section 6 de `evaluation_finale_test.ipynb`."))
for fichier, colonne, libelle in (("jeu_corrige_deux_populations.csv", "regle", "Règle métier (en incident à M, retard imminent), jeu corrigé"),
                                  ("jeu_de_base_deux_populations.csv", "pay1_retard", "Codification de la banque (PAY_1 ≥ 2), jeu de base")):
    if not (dossier / fichier).exists():
        display(Markdown(f"⚠️ `{fichier}` absent : lancer le notebook en deux populations correspondant."))
        continue
    for prefixe, version in (("2.", "23 colonnes"), ("3.", "sans les PAY_n")):
        niveaux, strategie = niveaux_essai(fichier, colonne, prefixe)
        SOURCES[f"{libelle}, ML {version}"] = niveaux

def tableau_niveaux(d):
    t = d.groupby("niveau")["dpnm"].agg(Clients="size", Défauts="sum")
    t["Précision du niveau seul (taux de défaut, %)"] = (t["Défauts"] / t["Clients"] * 100).round(1)
    t["Part de tous les défauts (%)"] = (t["Défauts"] / t["Défauts"].sum() * 100).round(1)
    t["Défauts cumulés (%)"] = (t["Défauts"].cumsum() / t["Défauts"].sum() * 100).round(1)
    t["Précision cumulée (%)"] = (t["Défauts"].cumsum() / t["Clients"].cumsum() * 100).round(1)
    t["Part des clients (%)"] = (t["Clients"] / t["Clients"].sum() * 100).round(1)
    return t

## 1. Chaque approche sur tous ses clients

Un tableau par approche, sur son propre périmètre : comment se répartissent les clients et les défauts entre les niveaux, et quelle précision on obtient en signalant jusqu'à chaque niveau.

In [2]:
for nom, d in SOURCES.items():
    display(Markdown(f"**{nom}** ({len(d)} clients, {d['dpnm'].sum()} défauts, taux de défaut {d['dpnm'].mean() * 100:.1f} %)"))
    display(tableau_niveaux(d))

**Version finale ml_17 (règle métier + CatBoost de ml_17)** (27202 clients, 5972 défauts, taux de défaut 22.0 %)

                  Clients  Défauts  Précision du niveau seul (taux de défaut, %)  Part de tous les défauts (%)  Défauts cumulés (%)  Précision cumulée (%)  Part des clients (%)
niveau
1. Règle             4743     2871                                          60.5                          48.1                 48.1                   60.5                  17.4
2. Haut risque       3179      942                                          29.6                          15.8                 63.8                   48.1                  11.7
3. Risque modéré     4996      893                                          17.9                          15.0                 78.8                   36.4                  18.4
4. Risque faible    14284     1266                                           8.9                          21.2                100.0                   22.0                  52.5

**Règle métier (en incident à M, retard imminent), jeu corrigé, ML 23 colonnes** (28851 clients, 6272 défauts, taux de défaut 21.7 %)

                  Clients  Défauts  Précision du niveau seul (taux de défaut, %)  Part de tous les défauts (%)  Défauts cumulés (%)  Précision cumulée (%)  Part des clients (%)
niveau
1. Règle             4743     2871                                          60.5                          45.8                 45.8                   60.5                  16.4
2. Haut risque       3366     1021                                          30.3                          16.3                 62.1                   48.0                  11.7
3. Risque modéré     6012     1020                                          17.0                          16.3                 78.3                   34.8                  20.8
4. Risque faible    14730     1360                                           9.2                          21.7                100.0                   21.7                  51.1

**Règle métier (en incident à M, retard imminent), jeu corrigé, ML sans les PAY_n** (28851 clients, 6272 défauts, taux de défaut 21.7 %)

                  Clients  Défauts  Précision du niveau seul (taux de défaut, %)  Part de tous les défauts (%)  Défauts cumulés (%)  Précision cumulée (%)  Part des clients (%)
niveau
1. Règle             4743     2871                                          60.5                          45.8                 45.8                   60.5                  16.4
2. Haut risque       3690     1021                                          27.7                          16.3                 62.1                   46.2                  12.8
3. Risque modéré     5930     1020                                          17.2                          16.3                 78.3                   34.2                  20.6
4. Risque faible    14488     1360                                           9.4                          21.7                100.0                   21.7                  50.2

**Codification de la banque (PAY_1 ≥ 2), jeu de base, ML 23 colonnes** (30000 clients, 6636 défauts, taux de défaut 22.1 %)

                  Clients  Défauts  Précision du niveau seul (taux de défaut, %)  Part de tous les défauts (%)  Défauts cumulés (%)  Précision cumulée (%)  Part des clients (%)
niveau
1. Règle             3130     2177                                          69.6                          32.8                 32.8                   69.6                  10.4
2. Haut risque       3176     1338                                          42.1                          20.2                 53.0                   55.7                  10.6
3. Risque modéré     6151     1338                                          21.8                          20.2                 73.1                   39.0                  20.5
4. Risque faible    17543     1783                                          10.2                          26.9                100.0                   22.1                  58.5

**Codification de la banque (PAY_1 ≥ 2), jeu de base, ML sans les PAY_n** (30000 clients, 6636 défauts, taux de défaut 22.1 %)

                  Clients  Défauts  Précision du niveau seul (taux de défaut, %)  Part de tous les défauts (%)  Défauts cumulés (%)  Précision cumulée (%)  Part des clients (%)
niveau
1. Règle             3130     2177                                          69.6                          32.8                 32.8                   69.6                  10.4
2. Haut risque       3484     1338                                          38.4                          20.2                 53.0                   53.1                  11.6
3. Risque modéré     6004     1338                                          22.3                          20.2                 73.1                   38.5                  20.0
4. Risque faible    17382     1783                                          10.3                          26.9                100.0                   22.1                  57.9

## 2. Sur les clients communs aux trois approches

Mêmes niveaux qu'en partie 1, mais restreints aux clients présents dans les trois fichiers (le périmètre du ML, le plus petit), pour comparer sur exactement les mêmes clients.

In [3]:
communs = set.intersection(*(set(d["ID"]) for d in SOURCES.values()))
resume = {}
for nom, d in SOURCES.items():
    c = d[d["ID"].isin(communs)]
    t = tableau_niveaux(c)
    resume[nom] = t[["Défauts cumulés (%)", "Précision cumulée (%)", "Part des clients (%)"]]
display(Markdown(f"**Clients communs aux trois approches** : {len(communs)}"))
display(pd.concat(resume, names=["Approche"]))

**Clients communs aux trois approches** : 27202

                                                                     Défauts cumulés (%)  Précision cumulée (%)  Part des clients (%)
Approche                                           niveau
Version finale ml_17 (règle métier + CatBoost d... 1. Règle                         48.1                   60.5                  17.4
                                                   2. Haut risque                   63.8                   48.1                  11.7
                                                   3. Risque modéré                 78.8                   36.4                  18.4
                                                   4. Risque faible                100.0                   22.0                  52.5
Règle métier (en incident à M, retard imminent)... 1. Règle                         48.1                   60.5                  17.4
                                                   2. Haut risque                   63.4                   48.9                  11.0
                                                   3. Risque modéré                 78.2                   36.0                  19.2
                                                   4. Risque faible                100.0                   22.0                  52.4
Règle métier (en incident à M, retard imminent)... 1. Règle                         48.1                   60.5                  17.4
                                                   2. Haut risque                   63.1                   47.7                  11.6
                                                   3. Risque modéré                 78.1                   35.5                  19.3
                                                   4. Risque faible                100.0                   22.0                  51.7
Codification de la banque (PAY_1 ≥ 2), jeu de b... 1. Règle                         36.3                   69.5                  11.5
                                                   2. Haut risque                   54.2                   58.2                   9.0
                                                   3. Risque modéré                 71.4                   41.2                  17.6
                                                   4. Risque faible                100.0                   22.0                  62.0
Codification de la banque (PAY_1 ≥ 2), jeu de b... 1. Règle                         36.3                   69.5                  11.5
                                                   2. Haut risque                   53.2                   56.2                   9.3
                                                   3. Risque modéré                 71.5                   40.4                  18.1
                                                   4. Risque faible                100.0                   22.0                  61.1

**Comment lire** : pour chaque approche, les lignes se lisent de haut en bas comme une décision de la banque (« je signale jusqu'à ce niveau ») : part des défauts attrapés et précision obtenue. La comparaison entre approches se fait à niveau égal, sur les clients communs : une approche fait mieux si, au même niveau, elle attrape plus de défauts avec une précision au moins égale.