# EDA contentieux : recherche du périmètre idéal de la population CTX

**Objectif** : définir une règle métier qui détecte et isole les clients en gestion « contentieuse » (codification PAY_n = 2 figée, faux rétrogradages), afin de :
- les sortir du périmètre du ML et les traiter par une règle métier (prédits en défaut),
- entraîner les modèles sur une population au comportement homogène.

**Méthodologie**
- Les règles candidates sont définies **a priori, par logique métier**, à partir des constats de l'EDA lab. Aucun seuil n'est optimisé sur la cible.
- Le jeu est découpé **avant toute analyse** en train / test (80/20, stratifié sur `dpnm`, `random_state=42`). Toutes les analyses sont faites sur le **train**.
- Les règles sont d'abord décrites par leur **comportement** (volumes, recouvrements, paiements, dette), sans `dpnm`.
- `dpnm` n'est utilisé sur le train que pour **valider** qu'un périmètre a un sens métier. Le **test** n'est utilisé **qu'une seule fois**, à la fin, pour la règle retenue.

**Données** : `cleaned3_creditcard.csv` (niveau de correction 3 v2), restreint au périmètre ML `S12` (`BILL_AMT1 > 0` et `LIMIT_BAL <= 500 000`).
La population contentieuse est quasi inchangée entre les niveaux de correction 0 et 3 : aucune correction ne crée ni ne modifie de codes PAY_n >= 2.

**Plan** : la règle 1 (« un seul >= 2 suffit ») est définie en section 3 et évaluée en sections 4 et 5. La **définition 2 (deux codes >= 2 successifs), retenue in fine**, est présentée en section 6 : elle reprend toutes les règles de la section 3 et affine la lecture de l'historique. Elle est validée sur le test en section 7, et les indicateurs pour le ML sont listés en section 8. Les règles exploratoires qui y ont mené (R1 à R8, versions bis et ter, statuts détaillés) sont conservées en annexe.

## 1. Chargement et périmètre

In [116]:
import pandas as pd
import numpy as np
from pathlib import Path

# Retrouve la racine du projet (là où se trouve le dossier 'data')
current_dir = Path.cwd()
root_dir = next(p for p in [current_dir] + list(current_dir.parents) if (p / "data").exists())

df = pd.read_csv(root_dir / "data" / "cleaned3_creditcard.csv")
print(f"Dataset complet : {len(df)} lignes | taux de défaut : {df['dpnm'].mean() * 100:.2f}%")

# Périmètre ML S12 : encours positif à M-1 et plafond <= 500 000 NT$
df = df[(df['BILL_AMT1'] > 0) & (df['LIMIT_BAL'] <= 500000)].copy()
print(f"Périmètre S12   : {len(df)} lignes | taux de défaut : {df['dpnm'].mean() * 100:.2f}%")

pay_cols = [f'PAY_{i}' for i in range(1, 7)]
bill_cols = [f'BILL_AMT{i}' for i in range(1, 7)]
pay_amt_cols = [f'PAY_AMT{i}' for i in range(1, 7)]

Dataset complet : 29136 lignes | taux de défaut : 21.69%
Périmètre S12   : 27202 lignes | taux de défaut : 21.95%

## 2. Séparation train / test
Le split est fait avant toute analyse et ne dépend d'aucune définition du CTX. Les notebooks ML devront reproduire ce même split (même périmètre, `stratify=dpnm`, `random_state=42`).

In [117]:
from sklearn.model_selection import train_test_split

df_train, df_test = train_test_split(df, test_size=0.2, stratify=df['dpnm'], random_state=42)

print(f"Train : {len(df_train)} lignes | taux de défaut : {df_train['dpnm'].mean() * 100:.2f}%")
print(f"Test  : {len(df_test)} lignes | taux de défaut : {df_test['dpnm'].mean() * 100:.2f}%")

Train : 21761 lignes | taux de défaut : 21.95%
Test  : 5441 lignes | taux de défaut : 21.96%

## 3. Définition du contentieux : entrée, maintien et sortie contrôlée par les paiements

**Nom de la règle : « un seul >= 2 suffit »**. Un seul mois avec un code PAY_n >= 2 suffit pour placer le client au CTX ce mois-là ; l'ensemble des règles ci-dessous (correction des faux 2, recodage du mois de transition, statuts et flags) s'appuie sur cette définition d'entrée.  
*Définition de départ. La définition retenue in fine est la définition 2 (section 6), qui reprend ces règles à l'identique et distingue en plus les retards isolés dans l'historique.*

**Principe** : les codifications PAY_n ne sont pas fiables, une sortie du contentieux doit être confirmée par les montants payés.

- **Au CTX le mois n** : PAY_n >= 2
- **Correction des faux 2** (appliquée en premier) : un « faux 2 » est une entrée au CTX (PAY_n >= 2 alors que PAY_(n+1) < 2) alors que la facture exigible ce mois-là (`BILL_AMT(n+1)`) est nulle ou négative. Deux cas, selon ce qui précède l'entrée :

| Cas | Condition | Traitement |
|---|---|---|
| Compte endormi | aucun paiement le mois précédant le 2 (`PAY_AMT(n+1) = 0`) et aucun encours 2 mois avant (`BILL_AMT(n+2) <= 0`) | code 2 conservé, flag `SURVEILLANCE_RECENTE` |
| Faux codage | paiement le mois précédant le 2 ou encours 2 mois avant | les codes >= 2 posés sur une facture nulle sont remplacés par le dernier code sain précédant l'entrée, flag `FAUX_CODAGE` |

Justification : un client qui vient de payer ou de solder sa dette ne peut pas être en retard sur une facture qui n'existe pas. Les codes >= 2 posés ensuite sur une vraie facture sont conservés : un vrai retard qui précède ou suit le faux codage reste pris en compte par les règles standards. Pour une entrée en M-5, seul le paiement en M-6 est vérifiable (encours en M-7 non observé).

- **Mois de transition** (PAY_2 >= 2 et PAY_1 <= 1) : PAY_1 est recodé selon les paiements, dans cet ordre :

| Condition | PAY_1 recodé | Sens |
|---|---|---|
| aucun paiement en M-1 ni en M-2 (`PAY_AMT1 = 0` et `PAY_AMT2 = 0`) alors qu'une facture était exigible les deux mois (`BILL_AMT3 > 0` et `BILL_AMT2 > 0`) | 2 | amélioration du code sans paiement de deux factures dues : maintien au CTX |
| ratio de paiement de M-1 (`PAY_AMT1 / BILL_AMT2`) >= 90 % | -2 | facture soldée : payeur au comptant, sortie du CTX |
| ratio de paiement de M-1 >= 10 % | -1 | paiement équivalent à 2 à 3 échéances (ratio de paiement courant de 3 à 5 %) : sortie du CTX |
| autres cas (paiement en M-2 seulement, ou inférieur à 10 % en M-1) | inchangé | un paiement existe sur les 2 derniers mois : le code de la banque est conservé |

Deux mois sont regardés pour le maintien au CTX car le paiement de régularisation peut être enregistré avec un mois de décalage. Une absence de paiement n'est retenue que si une facture était exigible : si rien n'était dû l'un des deux mois, la sortie décidée par la banque est conservée (voir section 3.3).

- **Statut à M** (calculé avec PAY_1 recodé) :

| Statut | Sous-statut | Définition | Traitement |
|---|---|---|---|
| `Retard considéré régularisé M-1` | `Retard considéré régularisé M-1` | PAY_1 >= 2 mais facture payée à 90 % ou plus en M-1 (`PAY_AMT1 / BILL_AMT2`) ou en M-2 (`PAY_AMT2 / BILL_AMT3`) | reste dans le ML avec le flag `RETARD_PAYE` : un client qui a réglé sa facture n'a pas deux échéances de retard réelles |
| `CTX` | `CTX 6 mois` | PAY_n >= 2 sur les 6 mois : au CTX sur toute la période observée | retiré du dataset ML : population contentieuse |
| `CTX` | `CTX entrée sur la période` | PAY_1 >= 2, entrée au CTX entre M-5 et M-1 et maintien jusqu'à M | retiré du dataset ML : population contentieuse |
| `Sorti` | `Sorti` | PAY_1 < 2 et au moins un PAY_n >= 2 sur M-2 à M-6 | reste dans le ML avec un flag d'antériorité |
| `Jamais CTX` | `Jamais CTX` | aucun PAY_n >= 2 | reste dans le ML |

- **Retard payé** : `RETARD_PAYE` = 1 pour un client codé >= 2 à M-1 qui a payé au moins 90 % de sa facture en M-1 ou en M-2. Dans l'historique, les clients codés 2 le mois où ils règlent leur facture en totalité reviennent le plus souvent sous 2 le mois suivant, sans nouveau paiement : le code 2 est vraisemblablement transitoire. Toutes les autres codifications >= 2 à M-1 placent le client au CTX.
- **Mois d'entrée** : `MOIS_ENTREE_CTX` = durée de la série continue de PAY_n >= 2 depuis M-1 pour les clients au CTX (1 = entrée en M-1, ..., 6 = au CTX sur les 6 mois).
- **Compte récent sous surveillance** : `SURVEILLANCE_RECENTE` = 1 pour un faux 2 sur un compte endormi (voir ci-dessus et section 3.1). Le code 2 est attribué avant qu'une facture ne soit exigible : ce n'est pas un retard au sens comptable, mais une mise sous surveillance, souvent justifiée par l'absence de remboursement qui suit. Le flag s'applique quel que soit le statut à M.
- **Faux codage** : `FAUX_CODAGE` = 1 pour un faux 2 neutralisé (client qui venait de payer ou avait un encours). Le flag est conservé pour que le ML puisse en tenir compte.
- **Flag d'antériorité** : `MOIS_SORTIE_CTX` = mois de la dernière sortie du CTX (1 = sortie en M-1, 2 = sortie en M-2, ...), -1 si jamais au CTX. Version alternative en 2 indicateurs si le mélange perturbe les modèles : `FLAG_CTX` (0/1) et `MOIS_SORTIE_CTX` à 0 si jamais au CTX.

In [118]:
def corriger_faux_codage(d):
    # Faux 2 : entrée au CTX (PAY_m >= 2 alors que PAY_(m+1) < 2) alors que la facture exigible,
    # BILL_AMT(m+1), est nulle ou négative
    # - compte endormi (ni paiement le mois précédent, ni encours 2 mois avant) : code 2 conservé, compte récent sous surveillance
    # - client qui venait de payer ou avait un encours : faux codage, les codes >= 2 posés sur une facture nulle
    #   sont remplacés par le dernier code sain précédant l'entrée
    codes = d[pay_cols].copy()
    faux_codage = pd.Series(False, index=d.index)
    surveillance = pd.Series(False, index=d.index)
    for m in range(1, 6):
        faux_2 = (d[f'PAY_{m}'] >= 2) & (d[f'PAY_{m+1}'] < 2) & (d[f'BILL_AMT{m+1}'] <= 0)
        paiement_avant = d[f'PAY_AMT{m+1}'] > 0
        # encours 2 mois avant le 2 non observable pour une entrée en M-5
        encours_avant = d[f'BILL_AMT{m+2}'] > 0 if m + 2 <= 6 else pd.Series(False, index=d.index)
        fc = faux_2 & (paiement_avant | encours_avant)
        surveillance |= faux_2 & ~fc
        faux_codage |= fc
        # Neutralisation de la série de codes >= 2 sur facture nulle, à partir du mois d'entrée
        a_corriger = fc.copy()
        for k in range(m, 0, -1):
            a_corriger &= (d[f'PAY_{k}'] >= 2) & (d[f'BILL_AMT{k+1}'] <= 0)
            codes.loc[a_corriger, f'PAY_{k}'] = d.loc[a_corriger, f'PAY_{m+1}']
    d_corrige = d.copy()
    d_corrige[pay_cols] = codes
    return d_corrige, faux_codage, surveillance

def recodage_pay1(d):
    # Ratio de paiement de M-1 sur la facture précédente (en %), 0 si pas de facture positive
    ratio = (d['PAY_AMT1'] / d['BILL_AMT2'].where(d['BILL_AMT2'] > 0) * 100).fillna(0)
    # Aucun paiement sur 2 mois (décalage d'enregistrement des paiements)
    sans_paiement_2_mois = (d['PAY_AMT1'] == 0) & (d['PAY_AMT2'] == 0)
    # Absence de paiement significative seulement si une facture était exigible les 2 mois (BILL_AMT3 en M-2, BILL_AMT2 en M-1)
    factures_exigibles = (d['BILL_AMT3'] > 0) & (d['BILL_AMT2'] > 0)

    # Mois de transition : sortie apparente du CTX entre M-2 et M-1
    transition = (d['PAY_2'] >= 2) & (d['PAY_1'] <= 1)
    pay1_recode = np.select(
        [transition & sans_paiement_2_mois & factures_exigibles, transition & (ratio >= 90), transition & (ratio >= 10)],
        [2, -2, -1],
        default=d['PAY_1'],
    )
    return pd.Series(pay1_recode, index=d.index)

def statut_ctx_final(d):
    # 1. Correction des faux codages, 2. recodage du mois de transition, 3. statuts
    d_corrige, faux_codage, surveillance = corriger_faux_codage(d)
    pay1 = recodage_pay1(d_corrige)
    passe_ctx = (d_corrige[['PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6']] >= 2).any(axis=1)

    # Retard payé : en retard à M-1 (PAY_1 >= 2) mais facture payée à 90 % ou plus en M-1 ou en M-2
    # -> pas de deux échéances de retard réelles : flag retard, le client reste dans le ML
    ratio_m1 = (d['PAY_AMT1'] / d['BILL_AMT2'].where(d['BILL_AMT2'] > 0) * 100).fillna(0)
    ratio_m2 = (d['PAY_AMT2'] / d['BILL_AMT3'].where(d['BILL_AMT3'] > 0) * 100).fillna(0)
    retard_paye = (pay1 >= 2) & ((ratio_m1 >= 90) | (ratio_m2 >= 90))

    statut = pd.Series(
        np.select([retard_paye, pay1 >= 2, passe_ctx], ['Retard considéré régularisé M-1', 'CTX', 'Sorti'], default='Jamais CTX'),
        index=d.index,
    )

    codes = d_corrige[pay_cols].copy()
    codes['PAY_1'] = pay1

    # Mois de la dernière sortie : mois n le plus récent où PAY_n < 2 et PAY_(n+1) >= 2
    sortie = (codes.iloc[:, :-1].values < 2) & (codes.iloc[:, 1:].values >= 2)
    mois_sortie = pd.Series(sortie.argmax(axis=1) + 1, index=d.index).astype(float)
    mois_sortie[statut == 'Jamais CTX'] = -1
    mois_sortie[statut == 'CTX'] = np.nan  # non applicable : retiré du dataset ML

    # Mois d'entrée au CTX pour les clients au CTX à M : durée de la série continue de PAY_n >= 2 depuis M-1
    # (6 = au CTX sur les 6 mois observés, entrée antérieure à la période)
    mois_entree = pd.Series((codes >= 2).cumprod(axis=1).sum(axis=1), index=d.index).astype(float)
    mois_entree[statut != 'CTX'] = np.nan

    sous_statut = statut.copy()
    sous_statut[mois_entree == 6] = 'CTX 6 mois'
    sous_statut[(statut == 'CTX') & (mois_entree < 6)] = 'CTX entrée sur la période'
    # Mois de sortie des clients en retard payé : dernière sortie antérieure éventuelle, sinon -1
    mois_sortie[(statut == 'Retard considéré régularisé M-1') & ~passe_ctx] = -1

    return pd.DataFrame({
        'PAY_1_recode': pay1,
        'STATUT_CTX': statut,
        'SOUS_STATUT_CTX': sous_statut,
        'MOIS_ENTREE_CTX': mois_entree,
        'MOIS_SORTIE_CTX': mois_sortie,
        'FLAG_CTX': ((statut == 'Sorti') | ((statut == 'Retard considéré régularisé M-1') & passe_ctx)).astype(int),
        'RETARD_PAYE': retard_paye.astype(int),
        'SURVEILLANCE_RECENTE': surveillance.astype(int),
        'FAUX_CODAGE': faux_codage.astype(int),
    })

final_train = statut_ctx_final(df_train)

# Recodage des mois de transition (après correction des faux codages)
d_corrige_train = corriger_faux_codage(df_train)[0]
transition_train = (d_corrige_train['PAY_2'] >= 2) & (d_corrige_train['PAY_1'] <= 1)
print(f"Mois de transition (PAY_2 >= 2 et PAY_1 <= 1) : {transition_train.sum()} clients")
display(pd.crosstab(
    d_corrige_train.loc[transition_train, 'PAY_1'].rename('PAY_1 initial'),
    final_train.loc[transition_train, 'PAY_1_recode'].rename('PAY_1 recodé'),
))

print("Statut à M :")
display(final_train['SOUS_STATUT_CTX'].value_counts().rename_axis('Statut à M').to_frame('Nb clients'))

print("Clients au CTX à M, selon le mois d'entrée (6 = au CTX sur les 6 mois) :")
display(final_train['MOIS_ENTREE_CTX'].value_counts().sort_index().rename_axis('MOIS_ENTREE_CTX').to_frame('Nb clients'))

print("Mois de la dernière sortie du CTX (clients sortis) :")
display(final_train.loc[final_train['STATUT_CTX'] == 'Sorti', 'MOIS_SORTIE_CTX']
        .value_counts().sort_index().rename_axis('MOIS_SORTIE_CTX').to_frame('Nb clients'))

print("Faux 2 : comptes récents sous surveillance et faux codages, selon le statut à M :")
display(pd.crosstab(
    final_train['SOUS_STATUT_CTX'],
    [final_train['SURVEILLANCE_RECENTE'].rename('SURVEILLANCE_RECENTE'), final_train['FAUX_CODAGE'].rename('FAUX_CODAGE')],
).rename_axis('Statut à M'))

Mois de transition (PAY_2 >= 2 et PAY_1 <= 1) : 1826 clients

PAY_1 recodé   -2   -1     1   2
PAY_1 initial
-2              4    1     0   0
-1              1  312     0  35
 1              1  133  1277  62

Statut à M :

                                 Nb clients
Statut à M
Jamais CTX                            15214
Sorti                                  3970
CTX entrée sur la période              1645
CTX 6 mois                              790
Retard considéré régularisé M-1         142

Clients au CTX à M, selon le mois d'entrée (6 = au CTX sur les 6 mois) :

                 Nb clients
MOIS_ENTREE_CTX
1.0                     666
2.0                     287
3.0                     355
4.0                     194
5.0                     143
6.0                     790

Mois de la dernière sortie du CTX (clients sortis) :

                 Nb clients
MOIS_SORTIE_CTX
1.0                    1729
2.0                     931
3.0                     578
4.0                     323
5.0                     409

Faux 2 : comptes récents sous surveillance et faux codages, selon le statut à M :

SURVEILLANCE_RECENTE                 0       1
FAUX_CODAGE                          0   1   0
Statut à M
CTX 6 mois                         790   0   0
CTX entrée sur la période         1595   1  49
Jamais CTX                       15193  21   0
Retard considéré régularisé M-1    140   1   1
Sorti                             3892   7  71

### 3.1 Étude des entrées au CTX et des « faux 2 »

**Rappel de la convention** : `PAY_n` et `PAY_AMTn` portent sur la facture `BILL_AMT(n+1)` (dette de fin de mois n+1, exigible au mois n).

Certains clients reçoivent un code PAY_n >= 2 alors que la facture exigible ce mois-là (`BILL_AMT(n+1)`) est nulle ou négative : ils ne peuvent pas être en retard sur une somme qui n'était pas due. Ces **« faux 2 »** ressemblent à des comptes récents ou réactivés, mis sous surveillance par la banque.

Chaque **entrée au CTX** observée (PAY_n >= 2 alors que PAY_(n+1) < 2, de M-5 à M-1, avec PAY_1 recodé) est classée en trois types :
- **Faux 2** : facture exigible au mois d'entrée nulle ou négative,
- **Passage -2 -> 2 sur facture positive** : code précédent -2 (pas d'utilisation à crédit) mais facture exigible positive,
- **Entrée sur facture positive (hors -2)** : entrée classique en retard.

Chaque entrée est décrite par :
- l'**inactivité du compte avant l'entrée** (aucune dette ni paiement sur tous les mois antérieurs),
- le **nombre de mois codés >= 2 sans facture exigible** depuis l'entrée,
- la **séquence des codes** du mois d'entrée jusqu'à M-1, la **durée** de la série de codes >= 2 et le **maintien au CTX jusqu'à M**,
- les **paiements depuis l'entrée** et la dette à M-1.

Les entrées en M-6 ne sont pas observables (pas de mois précédent). Un client peut avoir plusieurs entrées sur la période.

In [119]:
# Table des entrées au CTX : une ligne par entrée (client, mois n)
# Convention : PAY_n et PAY_AMTn portent sur la facture BILL_AMT(n+1) (dette de fin de mois n+1, exigible au mois n)
codes_train = df_train[pay_cols].copy()
# Étude faite sur les codes d'origine (avant correction des faux codages), PAY_1 recodé
codes_train['PAY_1'] = recodage_pay1(df_train)

def facture(d, k):
    # Facture exigible au mois k = BILL_AMT(k+1)
    return d[f'BILL_AMT{k+1}']

lignes = []
for n in range(1, 6):
    # Entrée au CTX le mois n : PAY_n >= 2 alors que PAY_(n+1) < 2
    entree = (codes_train[f'PAY_{n}'] >= 2) & (codes_train[f'PAY_{n+1}'] < 2)
    e = df_train[entree]
    c = codes_train[entree]
    mois_ctx = list(range(n, 0, -1))  # du mois d'entrée jusqu'à M-1
    serie_ctx = (c[[f'PAY_{k}' for k in mois_ctx]] >= 2).cumprod(axis=1)
    duree = serie_ctx.sum(axis=1)
    # Mois de la série de codes >= 2 portant sur une facture exigible nulle ou négative, depuis l'entrée
    sans_facture = pd.concat([facture(e, k) <= 0 for k in mois_ctx], axis=1).values
    nb_mois_2_sans_facture = (serie_ctx.values * sans_facture).cumprod(axis=1).sum(axis=1)
    # Paiements du mois d'entrée jusqu'à M-1
    paiements = e[[f'PAY_AMT{k}' for k in mois_ctx]]
    # Mois antérieurs à l'entrée : compte inactif si aucune dette ni paiement
    inactif_avant = (
        (e[[f'BILL_AMT{k}' for k in range(n + 1, 7)]] <= 0).all(axis=1)
        & (e[[f'PAY_AMT{k}' for k in range(n + 1, 7)]] == 0).all(axis=1)
    )
    lignes.append(pd.DataFrame({
        'mois_entree': n,
        'code_avant': c[f'PAY_{n+1}'],
        'facture_entree_nulle': facture(e, n) <= 0,
        'nb_mois_2_sans_facture': nb_mois_2_sans_facture,
        'inactif_avant': inactif_avant,
        'sequence': c[[f'PAY_{k}' for k in mois_ctx]].astype(int).astype(str).agg(' '.join, axis=1),
        'duree_ctx': duree,
        'ctx_jusqu_a_M': duree == n,
        'aucun_paiement_depuis': (paiements == 0).all(axis=1),
        'part_mois_payes': (paiements > 0).mean(axis=1) * 100,
        'dette_M1': e['BILL_AMT1'],
        'statut_M': final_train.loc[entree, 'STATUT_CTX'],
        'dpnm': e['dpnm'],
    }, index=e.index))

entrees = pd.concat(lignes)
entrees['type_entree'] = np.select(
    [entrees['facture_entree_nulle'], entrees['code_avant'] == -2],
    ['Faux 2 (facture exigible nulle)', 'Passage -2 -> 2 sur facture positive'],
    default='Entrée sur facture positive (hors -2)',
)
print(f"Entrées au CTX observées (M-5 à M-1) : {len(entrees)} pour {entrees.index.nunique()} clients")

Entrées au CTX observées (M-5 à M-1) : 4850 pour 4639 clients

In [120]:
def resume(g):
    return pd.Series({
        'Nb entrées': len(g),
        'Compte inactif avant (%)': g['inactif_avant'].mean() * 100,
        'Mois codés >= 2 sans facture exigible (moy.)': g['nb_mois_2_sans_facture'].mean(),
        'Durée moyenne au CTX (mois)': g['duree_ctx'].mean(),
        "Maintenu au CTX jusqu'à M (%)": g['ctx_jusqu_a_M'].mean() * 100,
        "Aucun paiement depuis l'entrée (%)": g['aucun_paiement_depuis'].mean() * 100,
        "Mois avec paiement depuis l'entrée (%)": g['part_mois_payes'].mean(),
        'Dette M-1 (min)': g['dette_M1'].min(),
        'Dette M-1 (médiane)': g['dette_M1'].median(),
        'Dette M-1 (max)': g['dette_M1'].max(),
        'Taux défaut (%)': g['dpnm'].mean() * 100,
    })

# 1. Comparatif des trois types d'entrée
print("1. Entrées au CTX selon le type d'entrée :")
display(entrees.groupby('type_entree').apply(resume).round(1).rename_axis("Type d'entrée"))

# 2. Faux 2 : nombre de mois codés >= 2 avant qu'une facture positive ne soit exigible
faux2 = entrees[entrees['facture_entree_nulle']]
print("2. Faux 2 selon le nombre de mois codés >= 2 sans facture exigible :")
display(faux2.groupby('nb_mois_2_sans_facture')['dpnm']
        .agg(Nb='count', Taux_defaut=lambda x: x.mean() * 100).round(1))

# 3. Séquences observées pour les faux 2 : code précédent -> codes du mois d'entrée jusqu'à M-1 (PAY_1 recodé)
print("3. Faux 2 : code précédent -> séquence du mois d'entrée jusqu'à M-1")
display(
    faux2.assign(sequence=faux2['code_avant'].astype(str) + ' -> ' + faux2['sequence'])
    .groupby(['mois_entree', 'sequence'])['dpnm']
    .agg(Nb='count', Taux_defaut=lambda x: x.mean() * 100)
    .round(1)
)

# 4. Faux 2 selon le maintien au CTX et le paiement depuis l'entrée
print("4. Faux 2 selon le maintien au CTX jusqu'à M et le paiement depuis l'entrée :")
display(faux2.groupby(['ctx_jusqu_a_M', 'aucun_paiement_depuis'])['dpnm']
        .agg(Nb='count', Taux_defaut=lambda x: x.mean() * 100).round(1))

# 5. Faux 2 selon l'inactivité du compte avant l'entrée
print("5. Faux 2 selon l'inactivité du compte avant l'entrée :")
display(faux2.assign(compte_avant=np.where(faux2['inactif_avant'], 'Inactif avant', 'Actif avant'))
        .groupby('compte_avant').apply(resume).round(1))

# 6. Profil des clients selon leur type d'entrée au CTX
def profil_client(idx):
    d = df_train.loc[idx]
    return pd.Series({
        'Nb clients': len(d),
        'Âge (médiane)': d['AGE'].median(),
        'LIMIT_BAL (médiane)': d['LIMIT_BAL'].median(),
        'Utilisation plafond M-1 (médiane %)': (d['BILL_AMT1'] / d['LIMIT_BAL'] * 100).median(),
        'Mois sans paiement (moy.)': (d[pay_amt_cols] == 0).sum(axis=1).mean(),
        'Statut CTX à M (%)': (final_train.loc[idx, 'STATUT_CTX'] == 'CTX').mean() * 100,
        'Taux défaut (%)': d['dpnm'].mean() * 100,
    })

types = ['Faux 2 (facture exigible nulle)', 'Passage -2 -> 2 sur facture positive', 'Entrée sur facture positive (hors -2)']
clients = {t: entrees.index[entrees['type_entree'] == t].unique() for t in types}
populations = {
    types[0]: clients[types[0]],
    types[1]: clients[types[1]].difference(clients[types[0]]),
    types[2]: clients[types[2]].difference(clients[types[0]]).difference(clients[types[1]]),
    'Jamais CTX': final_train.index[final_train['STATUT_CTX'] == 'Jamais CTX'],
}
print("6. Profil des clients selon leur type d'entrée au CTX :")
display(pd.DataFrame({nom: profil_client(idx) for nom, idx in populations.items()}).T.round(1).rename_axis('Population'))

# 7. Faux 2 selon ce qui précède l'entrée (mois relatifs au mois d'entrée m) et statut final à M
def cas_avant(row):
    m = row['mois_entree']
    paiement_avant = df_train.at[row.name, f'PAY_AMT{m+1}'] > 0
    if m + 2 > 6:
        return 'Entrée en M-5 : paiement en M-6' if paiement_avant else 'Entrée en M-5 : aucun paiement en M-6'
    encours_avant = df_train.at[row.name, f'BILL_AMT{m+2}'] > 0
    if paiement_avant and encours_avant:
        return 'Encours soldé le mois précédent'
    if paiement_avant:
        return 'Paiement sans encours'
    return 'Rien avant (ni encours, ni paiement)'

faux2 = faux2.assign(cas_avant=faux2.apply(cas_avant, axis=1),
                     statut_final=final_train.loc[faux2.index, 'SOUS_STATUT_CTX'].values,
                     flag=np.where(final_train.loc[faux2.index, 'FAUX_CODAGE'] == 1, 'FAUX_CODAGE', 'SURVEILLANCE_RECENTE'))
print("7. Faux 2 selon ce qui précède l'entrée : flag, taux de défaut et statut final à M (après correction)")
display(faux2.groupby(['flag', 'cas_avant'])['dpnm'].agg(Nb='count', Taux_defaut=lambda x: x.mean() * 100).round(1))
display(pd.crosstab([faux2['flag'], faux2['cas_avant']], faux2['statut_final'], margins=True, margins_name='Total'))

1. Entrées au CTX selon le type d'entrée :

,Nb entrées,Compte inactif avant (%),Mois codés >= 2 sans facture exigible (moy.),Durée moyenne au CTX (mois),Maintenu au CTX jusqu'à M (%),Aucun paiement depuis l'entrée (%),Mois avec paiement depuis l'entrée (%),Dette M-1 (min),Dette M-1 (médiane),Dette M-1 (max),Taux défaut (%)
Type d'entrée,,,,,,,,,,,
Entrée sur facture positive (hors -2),4676.0,0.0,0.0,1.7,36.9,0.4,72.9,3.0,27075.0,589654.0,44.6
Faux 2 (facture exigible nulle),151.0,70.9,2.0,2.3,37.1,53.6,18.7,1.0,2724.0,203843.0,41.7
Passage -2 -> 2 sur facture positive,23.0,0.0,0.0,3.1,39.1,4.3,64.1,882.0,19369.0,288585.0,34.8

2. Faux 2 selon le nombre de mois codés >= 2 sans facture exigible :

                         Nb  Taux_defaut
nb_mois_2_sans_facture
1                         3          0.0
2                       148         42.6

3. Faux 2 : code précédent -> séquence du mois d'entrée jusqu'à M-1

                                Nb  Taux_defaut
mois_entree sequence
2           -2 -> 2 2           39         51.3
3           -2 -> 2 2 -1        29         31.0
            -2 -> 2 2 1         19         36.8
            -2 -> 2 2 2          2        100.0
            -2 -> 2 2 3          5         80.0
4           -2 -> 2 2 -1 -1     12         33.3
            -2 -> 2 2 -1 2       1        100.0
            -2 -> 2 2 0 0        9         11.1
            -2 -> 2 2 2 -1       2         50.0
            -2 -> 2 2 2 1        2         50.0
            -2 -> 2 2 2 2        6         66.7
5           -2 -> 2 2 -1 -1 -1   6         16.7
            -2 -> 2 2 -1 -1 0    1          0.0
            -2 -> 2 2 -1 0 -1    1          0.0
            -2 -> 2 2 -1 2 -1    1          0.0
            -2 -> 2 2 0 0 0      3         33.3
            -2 -> 2 2 0 0 2      1        100.0
            -2 -> 2 2 2 2 -1     1          0.0
            -2 -> 2 2 2 2 1      4         25.0
            -2 -> 2 2 2 2 2      4        100.0
            -2 -> 2 2 2 3 -1     1        100.0
            -2 -> 2 2 3 -1 -1    1          0.0
            0 -> 2 0 0 0 0       1          0.0

4. Faux 2 selon le maintien au CTX jusqu'à M et le paiement depuis l'entrée :

                                     Nb  Taux_defaut
ctx_jusqu_a_M aucun_paiement_depuis
False         False                  58         27.6
              True                   37         35.1
True          False                  12         50.0
              True                   44         63.6

5. Faux 2 selon l'inactivité du compte avant l'entrée :

,Nb entrées,Compte inactif avant (%),Mois codés >= 2 sans facture exigible (moy.),Durée moyenne au CTX (mois),Maintenu au CTX jusqu'à M (%),Aucun paiement depuis l'entrée (%),Mois avec paiement depuis l'entrée (%),Dette M-1 (min),Dette M-1 (médiane),Dette M-1 (max),Taux défaut (%)
compte_avant,,,,,,,,,,,
Actif avant,44.0,0.0,2.0,2.2,38.6,43.2,28.0,1.0,2953.5,100000.0,27.3
Inactif avant,107.0,100.0,2.0,2.4,36.4,57.9,14.9,123.0,2500.0,203843.0,47.7

6. Profil des clients selon leur type d'entrée au CTX :

,Nb clients,Âge (médiane),LIMIT_BAL (médiane),Utilisation plafond M-1 (médiane %),Mois sans paiement (moy.),Statut CTX à M (%),Taux défaut (%)
Population,,,,,,,
Faux 2 (facture exigible nulle),151.0,35.0,150000.0,2.2,4.7,33.1,41.7
Passage -2 -> 2 sur facture positive,23.0,39.0,150000.0,88.5,1.9,34.8,34.8
Entrée sur facture positive (hors -2),4465.0,33.0,80000.0,61.0,1.4,35.5,44.0
Jamais CTX,15214.0,34.0,160000.0,29.7,0.7,0.0,11.5

7. Faux 2 selon ce qui précède l'entrée : flag, taux de défaut et statut final à M (après correction)

                                                             Nb  Taux_defaut
flag                 cas_avant
FAUX_CODAGE          Encours soldé le mois précédent         20         35.0
                     Entrée en M-5 : paiement en M-6          5          0.0
                     Paiement sans encours                    5         20.0
SURVEILLANCE_RECENTE Entrée en M-5 : aucun paiement en M-6   20         45.0
                     Rien avant (ni encours, ni paiement)   101         45.5

statut_final                                                CTX entrée sur la période  \
flag                 cas_avant
FAUX_CODAGE          Encours soldé le mois précédent                                1
                     Entrée en M-5 : paiement en M-6                                0
                     Paiement sans encours                                          0
SURVEILLANCE_RECENTE Entrée en M-5 : aucun paiement en M-6                          5
                     Rien avant (ni encours, ni paiement)                          44
Total                                                                              50

statut_final                                                Jamais CTX  \
flag                 cas_avant
FAUX_CODAGE          Encours soldé le mois précédent                13
                     Entrée en M-5 : paiement en M-6                 3
                     Paiement sans encours                           5
SURVEILLANCE_RECENTE Entrée en M-5 : aucun paiement en M-6           0
                     Rien avant (ni encours, ni paiement)            0
Total                                                               21

statut_final                                                Retard considéré régularisé M-1  \
flag                 cas_avant
FAUX_CODAGE          Encours soldé le mois précédent                                      1
                     Entrée en M-5 : paiement en M-6                                      0
                     Paiement sans encours                                                0
SURVEILLANCE_RECENTE Entrée en M-5 : aucun paiement en M-6                                0
                     Rien avant (ni encours, ni paiement)                                 1
Total                                                                                     2

statut_final                                                Sorti  Total
flag                 cas_avant
FAUX_CODAGE          Encours soldé le mois précédent            5     20
                     Entrée en M-5 : paiement en M-6            2      5
                     Paiement sans encours                      0      5
SURVEILLANCE_RECENTE Entrée en M-5 : aucun paiement en M-6     15     20
                     Rien avant (ni encours, ni paiement)      56    101
Total                                                          78    151

**Interprétation**  
Les « faux 2 » ne sont pas des retards au sens comptable : presque tous passent d'un code -2 à **deux mois codés 2 consécutifs alors qu'aucune facture n'est exigible**. La dette n'apparaît qu'à la fin du second mois. Il s'agit en grande majorité de comptes inactifs réactivés, avec de gros plafonds très peu utilisés et des dettes faibles.  
Ce schéma est trop régulier pour être une erreur aléatoire : cela s'apparente à une **procédure de mise sous surveillance d'un compte récent** par la banque. Un seul cas isolé (un code 2 unique suivi de paiements réguliers) ressemble à une véritable erreur de codification.

Les faux 2 se distinguent nettement :
- des **entrées classiques au CTX** : celles-ci portent sur des dettes importantes et les clients continuent presque tous à payer au moins partiellement, alors que la majorité des faux 2 ne remboursent rien depuis leur entrée ;
- des **passages de -2 à 2 sur facture positive** : ces clients utilisent fortement leur plafond et paient, leur comportement est celui d'une entrée classique au CTX et non celui des faux 2.

Pour une bonne partie d'entre eux, la surveillance est justifiée : ceux qui ne paient pas restent au contentieux avec un taux de défaut élevé, en particulier les comptes réactivés après une période d'inactivité.  
Ceux qui se remettent à payer sortent du CTX selon les règles standards et régularisent même mieux que la moyenne des clients sortis. Leurs dettes étant faibles, une meilleure régularisation est cohérente avec les normes de risque.  
Les effectifs sont faibles, les écarts restent donc indicatifs, mais la tendance est la même que sur l'ensemble de la population.

**Faux codages** : une partie des faux 2 ne concerne pas des comptes endormis mais des clients qui venaient de payer, souvent en soldant entièrement leur dette. Ils ne peuvent pas être en retard sur une facture inexistante : leurs codes 2 posés sur une facture nulle sont neutralisés (flag `FAUX_CODAGE`). Après correction, la plupart ne sont jamais passés par le contentieux ; ceux qui ont connu un vrai retard avant ou après restent pris en compte par les règles standards et font nettement plus défaut. Effectifs faibles, mais tendance nette.

Décision : ces clients suivent les mêmes règles de sortie que les autres. Les comptes endormis reçoivent en plus le flag `SURVEILLANCE_RECENTE` : un client sorti porte alors le double flag `FLAG_CTX` et `SURVEILLANCE_RECENTE`.

**Piste explorée et classée sans suite : ligne de crédit en apurement**  
Hypothèse : les faux 2 correspondraient à la création d'une ligne de crédit en apurement, sans possibilité d'utiliser l'encours (dette transférée puis figée, n'évoluant qu'avec les intérêts et les frais).

Test réalisé sur le train (hors notebook) : montant de la première dette apparue après l'entrée, puis évolution mensuelle de la dette hors remboursements.
- Compatible pour une partie des clients qui ne paient pas : la dette reste souvent stable ou n'augmente que faiblement.
- Réfutée pour le reste : les premières dettes sont très faibles au regard du plafond (peu compatible avec une reprise de dette), et les clients qui paient continuent visiblement d'utiliser leur carte.

Conclusion : hypothèse seulement partielle, sur une population de faible effectif. Piste classée sans suite. Le dataset ne détaille pas les transactions (achats, frais, intérêts) : l'origine exacte de ces premières dettes ne peut pas être établie.

**Piste explorée et écartée : généraliser la correction des faux 2 aux clients déjà au CTX**
Hypothèse : neutraliser aussi les séries de codes 2 posées sur une facture nulle chez des clients déjà au CTX sur une vraie dette, qui viennent de la solder entièrement (la banque les laisse à 2 alors qu'ils ne doivent plus rien).

Constats (simulation sur le train, hors notebook) :
- une neutralisation mois par mois crée des incohérences : dans une série `2 2`, le second 2 n'a jamais de paiement juste avant, puisque le client vient de tout solder. La correction doit porter sur toute la série ;
- appliquée à la série, elle ferait sortir du CTX quelques clients, sortis en M-1 ou M-2, au risque intermédiaire entre les sortis et le CTX.

Décision : **règle écartée**. Maintenir un code 2 tant que la dette n'est pas soldée, puis pendant un délai avant de rouvrir la ligne de crédit, relève vraisemblablement d'une procédure standard de la banque (délai de réhabilitation). Les codes de la banque ne sont pas modifiés ; seule la correction des faux 2 à l'entrée (faux codage) est conservée.

### 3.2 Codes 2 isolés

Un client peut n'avoir qu'un seul code >= 2 sur toute la période. On regarde si ce code isolé porte sur une vraie facture ou sur une facture nulle (codes d'origine, avant correction).

In [121]:
pay_hors_m1 = [f'PAY_{k}' for k in range(2, 7)]
nb_codes_2 = (df_train[pay_hors_m1] >= 2).sum(axis=1)
un_seul_2 = (nb_codes_2 == 1) & (df_train['PAY_1'] < 2)
print(f"Clients avec un seul code >= 2 sur toute la ligne (hors M-1, PAY_1 < 2) : {un_seul_2.sum()}")

mois_du_2 = df_train.loc[un_seul_2, pay_hors_m1].apply(lambda r: next(k for k in range(2, 7) if r[f'PAY_{k}'] >= 2), axis=1)
facture_du_2 = pd.Series(
    [df_train.at[i, f'BILL_AMT{mois_du_2[i] + 1}'] if mois_du_2[i] + 1 <= 6 else np.nan for i in mois_du_2.index],
    index=mois_du_2.index,
)
nature = pd.Series(np.select(
    [facture_du_2.isna(), facture_du_2 > 0],
    ['Non vérifiable (2 en M-6)', 'Facture exigible positive'],
    default='Facture exigible nulle',
), index=mois_du_2.index)

display(pd.crosstab(mois_du_2.map(lambda k: f'M-{k}').rename('Mois du 2'), nature.rename('Facture exigible')))
display(df_train.loc[un_seul_2].groupby(nature)['dpnm'].agg(Nb='count', Taux_defaut=lambda x: x.mean() * 100).round(1)
        .rename_axis('Facture exigible'))

Clients avec un seul code >= 2 sur toute la ligne (hors M-1, PAY_1 < 2) : 2146

Facture exigible,Facture exigible nulle,Facture exigible positive,Non vérifiable (2 en M-6)
Mois du 2,,,
M-2,0,652,0
M-3,0,524,0
M-4,0,361,0
M-5,1,201,0
M-6,0,0,407

                             Nb  Taux_defaut
Facture exigible
Facture exigible nulle        1          0.0
Facture exigible positive  1738         25.6
Non vérifiable (2 en M-6)   407         19.9

**Interprétation**
Un code 2 isolé porte presque toujours sur une vraie facture : c'est un retard réel suivi d'une régularisation, fonctionnement normal. Les codes 2 posés sur une facture nulle arrivent au contraire presque toujours par paires (`2 2`), aussi bien sur les comptes endormis que chez les clients venant de solder leur dette. Cette régularité va dans le sens d'une **procédure de la banque** (statut maintenu pendant un délai) plutôt que d'erreurs de codification aléatoires.

### 3.3 Règle de transition et factures non exigibles

Dans sa première version, la règle de transition (section 3) remettait PAY_1 à 2 lorsqu'un client passe de PAY_2 >= 2 à PAY_1 <= 1 sans aucun paiement en M-1 ni en M-2. Or une absence de paiement ne prouve un non-paiement que si une facture était exigible.
On distingue les clients remis à 2 selon que les deux factures exigibles (`BILL_AMT3` en M-2, `BILL_AMT2` en M-1) étaient positives ou non, puis on regarde comment ceux concernés étaient entrés au CTX.

In [122]:
d_corr = corriger_faux_codage(df_train)[0]
remis_a_2 = (d_corr['PAY_2'] >= 2) & (d_corr['PAY_1'] <= 1) & (d_corr['PAY_AMT1'] == 0) & (d_corr['PAY_AMT2'] == 0)
factures_exigibles = (d_corr['BILL_AMT3'] > 0) & (d_corr['BILL_AMT2'] > 0)
cas_remis = pd.Series(np.where(factures_exigibles, 'Deux factures exigibles impayées', 'Une facture exigible nulle'), index=df_train.index)

print("Clients sans paiement en M-1 ni en M-2 au mois de transition (remis à 2 par la première version de la règle) :")
display(df_train[remis_a_2].groupby(cas_remis[remis_a_2])['dpnm']
        .agg(Nb='count', Taux_defaut=lambda x: x.mean() * 100).round(1).rename_axis('Factures M-2 / M-1'))

# Comment les clients concernés (une facture exigible nulle) sont entrés au CTX
concernes = remis_a_2 & ~factures_exigibles
facture_entree = df_train['BILL_AMT4']       # facture exigible en M-3, mois du premier 2
paiement_entree = df_train['PAY_AMT3']       # paiement effectué en M-3
entree = pd.Series(np.select(
    [final_train['SURVEILLANCE_RECENTE'] == 1,
     (d_corr['PAY_3'] >= 2) & (facture_entree > 0) & (paiement_entree >= facture_entree)],
    ['Faux 2 sur compte endormi (surveillance)', 'Code 2 posé le mois où la facture est payée en totalité'],
    default='Autre',
), index=df_train.index)
print("Clients concernés (une facture exigible nulle), selon leur entrée au CTX :")
display(df_train[concernes].groupby(entree[concernes])['dpnm']
        .agg(Nb='count', Taux_defaut=lambda x: x.mean() * 100).round(1).rename_axis("Entrée au CTX"))

Clients sans paiement en M-1 ni en M-2 au mois de transition (remis à 2 par la première version de la règle) :

                                  Nb  Taux_defaut
Factures M-2 / M-1
Deux factures exigibles impayées  97         50.5
Une facture exigible nulle        59         35.6

Clients concernés (une facture exigible nulle), selon leur entrée au CTX :

                                                    Nb  Taux_defaut
Entrée au CTX
Code 2 posé le mois où la facture est payée en ...  25         40.0
Faux 2 sur compte endormi (surveillance)            34         32.4

**Constats**
- Une partie des clients remis au CTX par la règle de transition n'avait **rien à payer en M-2** (dette soldée ou compte endormi) : la preuve de non-paiement ne repose alors que sur M-1, soit un seul mois, alors que la convention du projet impose d'observer deux mois (décalage d'enregistrement des paiements).
- Ces clients se sont bien resservis de leur carte : une nouvelle dette apparaît en fin de M-2, exigible en M-1, et n'est pas payée en M-1.
- Ils sont entrés au CTX soit par un faux 2 sur compte endormi, soit par un **code 2 posé le mois même où ils paient leur facture en totalité**, ce qui est incohérent avec un retard de deux échéances (décalage de mise à jour du code ou paiement rejeté : non vérifiable). Cette anomalie n'est pas corrigée : les codes de la banque ne sont pas modifiés.

**Correction appliquée** : PAY_1 n'est remis à 2 que si **deux factures exigibles consécutives** (`BILL_AMT3 > 0` et `BILL_AMT2 > 0`) sont restées impayées. Il ne s'agit pas de modifier un code de la banque, mais de ne plus annuler une sortie décidée par la banque sur la base d'un seul mois observé.
Les clients concernés deviennent des sortis en M-1. Les comptes endormis gardent le flag `SURVEILLANCE_RECENTE`, l'information reste donc disponible pour le ML.

## 4. Description des statuts (sans la cible)

In [123]:
def profil_comportement(d):
    # Nombre de mois sans aucun paiement
    mois_sans_paiement = (d[pay_amt_cols] == 0).sum(axis=1)
    # Évolution de la dette de M-6 à M-1
    evolution_dette = d['BILL_AMT1'] - d['BILL_AMT6']
    # Utilisation du plafond à M-1
    utilisation = d['BILL_AMT1'] / d['LIMIT_BAL'] * 100
    return pd.Series({
        'Nb clients': len(d),
        'Mois sans paiement (moy.)': mois_sans_paiement.mean(),
        '% avec 6 mois sans paiement': (mois_sans_paiement == 6).mean() * 100,
        '% dette en hausse M-6 -> M-1': (evolution_dette > 0).mean() * 100,
        'Utilisation plafond M-1 (médiane %)': utilisation.median(),
        'LIMIT_BAL (médiane)': d['LIMIT_BAL'].median(),
    })

statuts_finaux = ['CTX', 'Retard considéré régularisé M-1', 'Sorti', 'Jamais CTX']
sous_statuts = ['CTX 6 mois', 'CTX entrée sur la période', 'Retard considéré régularisé M-1', 'Sorti', 'Jamais CTX']
display(pd.DataFrame(
    {s: profil_comportement(df_train[final_train['SOUS_STATUT_CTX'] == s]) for s in sous_statuts}
).T.round(1).rename_axis('Statut à M'))

,Nb clients,Mois sans paiement (moy.),% avec 6 mois sans paiement,% dette en hausse M-6 -> M-1,Utilisation plafond M-1 (médiane %),LIMIT_BAL (médiane)
Statut à M,,,,,,
CTX 6 mois,790.0,2.4,16.1,19.4,63.8,70000.0
CTX entrée sur la période,1645.0,1.3,2.2,58.2,81.2,70000.0
Retard considéré régularisé M-1,142.0,1.5,0.0,45.1,0.7,140000.0
Sorti,3970.0,1.6,0.8,47.2,51.0,80000.0
Jamais CTX,15214.0,0.7,1.7,67.0,29.7,160000.0

**Interprétation**  
Les statuts ont des comportements nettement distincts :
- les clients au CTX utilisent fortement leur plafond, qui est plus bas, et paient moins souvent. Plus le contentieux est installé, moins le client paie : les clients au CTX sur les 6 mois sont les moins payeurs ;
- les clients sortis se situent entre les deux ;
- les clients en retard payé (code >= 2 à M-1 mais facture réglée) forment un petit groupe à part, à décrire avec prudence vu son effectif ;
- les clients jamais passés au CTX ont les plafonds les plus élevés, les utilisent peu et paient presque tous les mois.

Cette description, faite sans la cible, montre que la règle isole un comportement de paiement réellement dégradé et pas seulement une codification.

## 5. Validation sur le train avec la cible
Pour chaque périmètre :
- **taux de défaut** dans le périmètre (précision de la règle « tous en défaut »),
- **part des défauts captés dans tout le jeu de données** (recall de la règle),
- **taux de défaut du reste du jeu de données** : population laissée au ML.

In [124]:
def validation(d, masque):
    y = d['dpnm']
    return pd.Series({
        'Nb clients': masque.sum(),
        'Part (%)': masque.mean() * 100,
        'Taux défaut périmètre (%)': y[masque].mean() * 100,
        'Défauts captés (%)': y[masque].sum() / y.sum() * 100,
        'Taux défaut reste (%)': y[~masque].mean() * 100,
    })

print(f"Taux de défaut global (train) : {df_train['dpnm'].mean() * 100:.2f}%")

Taux de défaut global (train) : 21.95%

In [125]:
# Validation de la règle retenue (section 3)
print("Validation de la règle retenue, par statut à M :")
display(pd.DataFrame(
    {s: validation(df_train, final_train['STATUT_CTX'] == s) for s in statuts_finaux}
).T.round(2).rename_axis('Statut à M'))

print("Détail du CTX : au CTX sur les 6 mois / entrée au CTX sur la période et maintenu jusqu'à M :")
display(pd.DataFrame(
    {s: validation(df_train, final_train['SOUS_STATUT_CTX'] == s) for s in ['CTX 6 mois', 'CTX entrée sur la période']}
).T.round(2).rename_axis('Statut à M'))

# Clients au CTX selon le mois d'entrée
ctx = final_train['STATUT_CTX'] == 'CTX'
print("Clients au CTX, selon le mois d'entrée (6 = au CTX sur les 6 mois) :")
display(
    df_train[ctx].groupby(final_train.loc[ctx, 'MOIS_ENTREE_CTX'])['dpnm']
    .agg(Nb_clients='count', Taux_defaut=lambda x: x.mean() * 100)
    .round(2).rename_axis('MOIS_ENTREE_CTX')
)

# Clients sortis selon le mois de la dernière sortie
sortis = final_train['STATUT_CTX'] == 'Sorti'
print("Clients sortis, selon le mois de la dernière sortie :")
display(
    df_train[sortis].groupby(final_train.loc[sortis, 'MOIS_SORTIE_CTX'])['dpnm']
    .agg(Nb_clients='count', Taux_defaut=lambda x: x.mean() * 100)
    .round(2).rename_axis('MOIS_SORTIE_CTX')
)

Validation de la règle retenue, par statut à M :

,Nb clients,Part (%),Taux défaut périmètre (%),Défauts captés (%),Taux défaut reste (%)
Statut à M,,,,,
CTX,2435.0,11.19,70.14,35.75,15.88
Retard considéré régularisé M-1,142.0,0.65,40.85,1.21,21.83
Sorti,3970.0,18.24,31.81,26.44,19.75
Jamais CTX,15214.0,69.91,11.49,36.59,46.27

Détail du CTX : au CTX sur les 6 mois / entrée au CTX sur la période et maintenu jusqu'à M :

,Nb clients,Part (%),Taux défaut périmètre (%),Défauts captés (%),Taux défaut reste (%)
Statut à M,,,,,
CTX 6 mois,790.0,3.63,76.96,12.73,19.88
CTX entrée sur la période,1645.0,7.56,66.87,23.03,18.28

Clients au CTX, selon le mois d'entrée (6 = au CTX sur les 6 mois) :

                 Nb_clients  Taux_defaut
MOIS_ENTREE_CTX
1.0                     666        68.92
2.0                     287        64.81
3.0                     355        67.04
4.0                     194        64.43
5.0                     143        64.34
6.0                     790        76.96

Clients sortis, selon le mois de la dernière sortie :

                 Nb_clients  Taux_defaut
MOIS_SORTIE_CTX
1.0                    1729        40.60
2.0                     931        27.82
3.0                     578        26.47
4.0                     323        20.43
5.0                     409        20.29

**Durée du passage au CTX chez les clients sortis**
Nombre de mois à >= 2 entre M-2 et M-6 (codes corrigés), seul puis croisé avec le mois de sortie. Plus un client a de mois à >= 2, plus sa sortie est forcément récente : le croisement permet de séparer les deux effets.

In [126]:
sortis = final_train['STATUT_CTX'] == 'Sorti'
d_corr = corriger_faux_codage(df_train)[0]
nb_mois_ctx = (d_corr.loc[sortis, [f'PAY_{k}' for k in range(2, 7)]] >= 2).sum(axis=1).rename('Nb mois >= 2 (M-2 à M-6)')
mois_sortie = final_train.loc[sortis, 'MOIS_SORTIE_CTX'].rename('Mois de sortie')

print("Clients sortis selon le nombre de mois passés au CTX :")
display(df_train[sortis].groupby(nb_mois_ctx)['dpnm'].agg(Nb='count', Taux_defaut=lambda x: x.mean() * 100).round(1))

print("Taux de défaut (%) selon le nombre de mois au CTX et le mois de sortie :")
display(pd.crosstab(nb_mois_ctx, mois_sortie, values=df_train.loc[sortis, 'dpnm'] * 100, aggfunc='mean').round(1))
print("Effectifs :")
display(pd.crosstab(nb_mois_ctx, mois_sortie))

Clients sortis selon le nombre de mois passés au CTX :

                            Nb  Taux_defaut
Nb mois >= 2 (M-2 à M-6)
1                         2150         24.6
2                          780         31.3
3                          490         45.1
4                          226         42.5
5                          324         53.7

Taux de défaut (%) selon le nombre de mois au CTX et le mois de sortie :

Mois de sortie             1.0   2.0   3.0   4.0   5.0
Nb mois >= 2 (M-2 à M-6)
1                         31.7  23.5  21.6  18.3  20.3
2                         34.8  28.0  33.8  24.0   NaN
3                         51.2  40.6  35.0   NaN   NaN
4                         50.6  37.8   NaN   NaN   NaN
5                         53.7   NaN   NaN   NaN   NaN

Effectifs :

Mois de sortie            1.0  2.0  3.0  4.0  5.0
Nb mois >= 2 (M-2 à M-6)
1                         654  524  361  202  409
2                         385  200   74  121    0
3                         283   64  143    0    0
4                          83  143    0    0    0
5                         324    0    0    0    0

**Interprétation**
Chez les clients sortis, le risque augmente avec le nombre de mois passés au CTX. Une partie de cet effet vient de l'ancienneté de la sortie (un long passage au CTX implique une sortie récente), mais à mois de sortie égal, un passage plus long reste associé à un risque plus élevé.
Deux effets distincts coexistent donc : **la durée du passage au CTX** et **l'ancienneté de la sortie**. `MOIS_SORTIE_CTX` ne capte que le second.

Piste pour le ML : ajouter un indicateur du **nombre de mois passés au CTX** sur la période.

**Interprétation**  
- **CTX** : un seul critère, être en retard (PAY >= 2) à M-1 après recodage (hors retard payé), isole une population au taux de défaut très élevé, plusieurs fois supérieur à celui des clients jamais passés au CTX. Ce qui fait le contentieux, c'est d'y être encore à M-1, pas d'y être passé : avoir eu un retard à n'importe quel moment de la période donne un taux bien plus bas.
- Les clients au CTX sur les 6 mois sont les pires des pires ; ceux entrés au CTX sur la période restent très au-dessus de la moyenne. Retirer l'ensemble du CTX du ML est donc justifié. Contrepartie à assumer : une partie des clients CTX ne fera pas défaut mais sera prédite en défaut par la règle.
- **Sortis** : plus la sortie du CTX est ancienne, plus le taux de défaut baisse, ce qui est tout à fait logique.
- **Recodage de PAY_1** : transformer les PAY_1 = 1 qui suivent un code >= 2 en 2 était une erreur (raison de l'abandon de l'ancien niveau 3) : ils forment une population distincte, moins risquée que le vrai contentieux. Seules les améliorations du code sans aucun paiement sur 2 mois, alors que deux factures étaient exigibles, sont maintenues au CTX : regarder le seul mois M-1 renvoyait à tort au CTX de nombreux clients dont le paiement est enregistré avec un mois de décalage (section 3.3).
- **Retard payé** : un client codé >= 2 à M-1 qui a réglé sa facture présente un risque bien inférieur au CTX : il reste dans le ML avec un flag.
- La stabilité de la règle entre le train et le test est vérifiée une seule fois, en section 7, sur la définition retenue.

**Limite de la cible `dpnm`**  
La règle de calcul de `dpnm` n'est pas documentée (« default payment next month », Oui = 1, Non = 0). Deux constats sur le train montrent qu'elle n'est pas le simple report du code de retard du mois suivant :
- une partie des clients figés à PAY_n = 2 sur les 6 mois (`R1_chronique`) est notée saine, alors que leur code ne bouge jamais ;
- chez les clients à PAY_1 = 2, le taux de défaut ne varie pas selon la présence ou non de paiements en M-1 et en M-2.

Une partie des étiquettes peut donc être imprécise. C'est pourquoi le contentieux est défini ici par des règles métier : `dpnm` sert seulement à vérifier que ces règles isolent bien une population à risque.  
Si une partie des étiquettes est bruitée, les modèles ne pourront pas dépasser un certain niveau de performance.  
Le système prédit le défaut tel que la banque l'a noté en octobre 2005, pas forcément un impayé définitif.

## 6. Définition 2 (retenue) : deux codes >= 2 successifs

Définition alternative explorée : un passage au CTX dans l'historique nécessite **deux codifications >= 2 successives**. Les autres règles sont conservées à l'identique.

| Élément | Règle |
|---|---|
| Faux 2 | inchangé : faux codage neutralisé (`FAUX_CODAGE`), compte endormi conservé (`SURVEILLANCE_RECENTE`) |
| Recodage de PAY_1 (mois de transition) | inchangé : remis à 2 seulement si deux factures exigibles sont restées impayées |
| Historique (M-2 à M-6) | série d'au moins 2 mois à >= 2 : passage au CTX (`Sorti`, `FLAG_CTX`, `MOIS_SORTIE_CTX`) ; 2 isolé : **retard régularisé** (`FLAG_RETARD`, `MOIS_SORTIE_RETARD` = mois du retour sous 2, de 1 à 4) |
| 2 isolé en M-6 | considéré comme un passage au CTX par défaut : M-7 n'est pas observé, le 2 peut terminer une série plus longue |
| À M-1 | PAY_1 >= 2 : **CTX** (qu'il soit isolé ou non), sauf facture payée à 90 % ou plus en M-1 ou en M-2 : **retard payé**, traité comme une régularisation présumée au plus tard en M (`FLAG_RETARD` = 1, `MOIS_SORTIE_RETARD` = 0) |

Statuts à M : `CTX` (retiré du ML), `Retard considéré régularisé M-1`, `Sorti`, `Retard régularisé`, `Jamais CTX` (dans le ML).

Codage du CTX : `FLAG_CTX` est un **marqueur intemporel** : 1 si le client a eu, à un moment des 6 mois, deux codes >= 2 consécutifs. Par défaut, un 2 isolé en M-6 (M-7 inconnu) ou en M-1 (suite inconnue) compte aussi, sauf retard payé à M-1 (`FLAG_RETARD` = 1, `MOIS_SORTIE_RETARD` = 0). Le dataset ne donne pas d'état en M : « au CTX à M » est une décision de traitement fondée sur la dernière situation connue (M-1).  
`MOIS_SORTIE_CTX` = mois de la dernière sortie (1 à 5), -1 s'il n'y a pas de sortie (client encore au CTX, ou jamais au CTX).  
**Sont retirés du dataset ML tous les clients avec `FLAG_CTX` = 1 et `MOIS_SORTIE_CTX` = -1**, c'est-à-dire les clients au CTX à M.

Codage de `MOIS_SORTIE_RETARD` : 0 = retard payé à M-1 (régularisation présumée, non encore visible dans le code), 1 à 4 = mois du retour sous 2 observé, -1 = aucune régularisation. Une seule valeur est conservée par client, la plus récente. La valeur -1 regroupe des profils de risque très différents (jamais CTX, sortis d'un CTX) : elle doit toujours être lue avec les flags `FLAG_RETARD` et `FLAG_CTX`, et la variable traitée comme catégorielle pour la régression logistique.

**Décision : la définition 2 est retenue.** Elle retire du ML la même population CTX que la règle 1, mais **affine le grain des retards** transmis au ML : un vrai passage au CTX (au moins deux mois à >= 2) est distingué d'un retard isolé régularisé, deux situations au risque nettement différent.

In [127]:
def statut_ctx_regle2(d):
    # 1. Correction des faux codages, 2. recodage du mois de transition (identiques à la règle 1)
    d_corrige, faux_codage, surveillance = corriger_faux_codage(d)
    pay1 = recodage_pay1(d_corrige)
    codes = d_corrige[pay_cols].copy()
    codes['PAY_1'] = pay1

    # 3. Retard payé : PAY_1 >= 2 mais facture payée à 90 % ou plus en M-1 ou en M-2
    ratio_m1 = (d['PAY_AMT1'] / d['BILL_AMT2'].where(d['BILL_AMT2'] > 0) * 100).fillna(0)
    ratio_m2 = (d['PAY_AMT2'] / d['BILL_AMT3'].where(d['BILL_AMT3'] > 0) * 100).fillna(0)
    retard_paye = (pay1 >= 2) & ((ratio_m1 >= 90) | (ratio_m2 >= 90))

    # 4. Historique (séries de codes >= 2 terminées avant M-1) :
    #    série d'au moins 2 mois = passage au CTX ; 2 isolé = retard régularisé ;
    #    2 isolé en M-6 = passage au CTX par défaut (M-7 inconnu)
    retard = (codes >= 2).values
    passage_ctx = np.zeros(len(d), bool)
    retard_regularise = np.zeros(len(d), bool)
    mois_sortie = np.full(len(d), -1.0)
    mois_regularisation = np.full(len(d), -1.0)
    for i, r in enumerate(retard):
        k = 1
        while k < 6:
            if r[k] and not r[k - 1]:
                fin = k
                while fin + 1 < 6 and r[fin + 1]:
                    fin += 1
                # k = mois du retour sous 2 (1 = M-1), séries parcourues de la plus récente à la plus ancienne
                if fin > k or fin == 5:
                    if not passage_ctx[i]:
                        mois_sortie[i] = k
                    passage_ctx[i] = True
                else:
                    if not retard_regularise[i]:
                        mois_regularisation[i] = k
                    retard_regularise[i] = True
                k = fin + 1
            else:
                k += 1
    passage_ctx = pd.Series(passage_ctx, index=d.index)
    retard_regularise = pd.Series(retard_regularise, index=d.index)

    statut = pd.Series(np.select(
        [retard_paye, pay1 >= 2, passage_ctx, retard_regularise],
        ['Retard considéré régularisé M-1', 'CTX', 'Sorti', 'Retard régularisé'],
        default='Jamais CTX',
    ), index=d.index)

    duree = (codes >= 2).cumprod(axis=1).sum(axis=1)
    sous_statut = statut.copy()
    sous_statut[(statut == 'CTX') & (duree == 6)] = 'CTX 6 mois'
    sous_statut[(statut == 'CTX') & (duree.between(2, 5))] = 'CTX 2 à 5 mois'
    sous_statut[(statut == 'CTX') & (duree == 1)] = 'CTX entrée en M-1'

    # FLAG_CTX = 1 : client au CTX à M ou passé par le CTX ; MOIS_SORTIE_CTX = -1 : pas de sortie (au CTX à M ou jamais au CTX)
    # -> client au CTX à M = FLAG_CTX = 1 et MOIS_SORTIE_CTX = -1 (retiré du dataset ML)
    mois_sortie = pd.Series(mois_sortie, index=d.index)
    mois_sortie[statut == 'CTX'] = -1
    # Retard payé = régularisation présumée au plus tard en M : MOIS_SORTIE_RETARD = 0 (tête d'échelle)
    mois_regularisation = pd.Series(mois_regularisation, index=d.index)
    mois_regularisation[retard_paye] = 0
    mois_regularisation[statut == 'CTX'] = np.nan
    retard_regularise = retard_regularise | retard_paye

    return pd.DataFrame({
        'PAY_1_recode': pay1,
        'STATUT_CTX': statut,
        'SOUS_STATUT_CTX': sous_statut,
        'MOIS_SORTIE_CTX': mois_sortie,
        'FLAG_CTX': (passage_ctx | (statut == 'CTX')).astype(int),
        'MOIS_SORTIE_RETARD': mois_regularisation,
        'FLAG_RETARD': (retard_regularise & (statut != 'CTX')).astype(int),
        'SURVEILLANCE_RECENTE': surveillance.astype(int),
        'FAUX_CODAGE': faux_codage.astype(int),
    })

final2_train = statut_ctx_regle2(df_train)
statuts_r2 = ['CTX', 'Retard considéré régularisé M-1', 'Sorti', 'Retard régularisé', 'Jamais CTX']

print("Statut à M (définition 2) :")
display(final2_train['SOUS_STATUT_CTX'].value_counts().rename_axis('Statut à M').to_frame('Nb clients'))

# Contrôle : le couple FLAG_CTX = 1 / MOIS_SORTIE_CTX = -1 désigne exactement les clients au CTX à M
retires = (final2_train['FLAG_CTX'] == 1) & (final2_train['MOIS_SORTIE_CTX'] == -1)
print(f"Clients retirés du dataset ML (FLAG_CTX = 1 et MOIS_SORTIE_CTX = -1) : {retires.sum()} | "
      f"identiques au statut CTX : {(retires == (final2_train['STATUT_CTX'] == 'CTX')).all()}")

Statut à M (définition 2) :

                                 Nb clients
Statut à M
Jamais CTX                            15214
Sorti                                  2152
Retard régularisé                      1818
CTX 2 à 5 mois                          979
CTX 6 mois                              790
CTX entrée en M-1                       666
Retard considéré régularisé M-1         142

Clients retirés du dataset ML (FLAG_CTX = 1 et MOIS_SORTIE_CTX = -1) : 2435 | identiques au statut CTX : True

In [128]:
print("Validation par statut à M (définition 2) :")
display(pd.DataFrame({s: validation(df_train, final2_train['STATUT_CTX'] == s) for s in statuts_r2}).T.round(2).rename_axis('Statut à M'))

print("Détail du CTX :")
display(pd.DataFrame({s: validation(df_train, final2_train['SOUS_STATUT_CTX'] == s)
                      for s in ['CTX 6 mois', 'CTX 2 à 5 mois', 'CTX entrée en M-1']}).T.round(2).rename_axis('Sous-statut'))

sortis2 = final2_train['STATUT_CTX'] == 'Sorti'
print("Sortis selon le mois de sortie :")
display(df_train[sortis2].groupby(final2_train.loc[sortis2, 'MOIS_SORTIE_CTX'])['dpnm']
        .agg(Nb='count', Taux_defaut=lambda x: x.mean() * 100).round(1))

regul2 = final2_train['STATUT_CTX'] == 'Retard régularisé'
print("Retards régularisés selon le mois de retour sous 2 :")
display(df_train[regul2].groupby(final2_train.loc[regul2, 'MOIS_SORTIE_RETARD'])['dpnm']
        .agg(Nb='count', Taux_defaut=lambda x: x.mean() * 100).round(1))

print("Comparaison avec la règle 1 (« un seul >= 2 suffit ») :")
comparaison = {}
for nom, f in [('Règle 1', final_train), ('Définition 2', final2_train)]:
    ctx = f['STATUT_CTX'] == 'CTX'
    comparaison[nom] = {
        'Clients CTX': ctx.sum(),
        'Défaut CTX (%)': df_train.loc[ctx, 'dpnm'].mean() * 100,
        'Défauts captés (%)': df_train.loc[ctx, 'dpnm'].sum() / df_train['dpnm'].sum() * 100,
        'Faux positifs': int((df_train.loc[ctx, 'dpnm'] == 0).sum()),
        'Défaut population ML (%)': df_train.loc[~ctx, 'dpnm'].mean() * 100,
    }
display(pd.DataFrame(comparaison).T.round(2))
display(pd.crosstab(final_train['STATUT_CTX'].rename('Règle 1'), final2_train['STATUT_CTX'].rename('Définition 2'), margins=True))

Validation par statut à M (définition 2) :

,Nb clients,Part (%),Taux défaut périmètre (%),Défauts captés (%),Taux défaut reste (%)
Statut à M,,,,,
CTX,2435.0,11.19,70.14,35.75,15.88
Retard considéré régularisé M-1,142.0,0.65,40.85,1.21,21.83
Sorti,2152.0,9.89,36.80,16.58,20.32
Retard régularisé,1818.0,8.35,25.91,9.86,21.59
Jamais CTX,15214.0,69.91,11.49,36.59,46.27

Détail du CTX :

,Nb clients,Part (%),Taux défaut périmètre (%),Défauts captés (%),Taux défaut reste (%)
Sous-statut,,,,,
CTX 6 mois,790.0,3.63,76.96,12.73,19.88
CTX 2 à 5 mois,979.0,4.50,65.47,13.42,19.90
CTX entrée en M-1,666.0,3.06,68.92,9.61,20.47

Sortis selon le mois de sortie :

                  Nb  Taux_defaut
MOIS_SORTIE_CTX
1.0              875         46.4
2.0              328         34.5
3.0              218         34.9
4.0              179         38.5
5.0              552         23.2

Retards régularisés selon le mois de retour sous 2 :

                     Nb  Taux_defaut
MOIS_SORTIE_RETARD
1.0                 728         32.0
2.0                 527         23.3
3.0                 361         21.6
4.0                 202         18.3

Comparaison avec la règle 1 (« un seul >= 2 suffit ») :

,Clients CTX,Défaut CTX (%),Défauts captés (%),Faux positifs,Défaut population ML (%)
Règle 1,2435.0,70.14,35.75,727.0,15.88
Définition 2,2435.0,70.14,35.75,727.0,15.88

Définition 2,CTX,Jamais CTX,Retard considéré régularisé M-1,Retard régularisé,Sorti,All
Règle 1,,,,,,
CTX,2435,0,0,0,0,2435
Jamais CTX,0,15214,0,0,0,15214
Retard considéré régularisé M-1,0,0,142,0,0,142
Sorti,0,0,0,1818,2152,3970
All,2435,15214,142,1818,2152,21761

**Interprétation**  
- **Population CTX identique à la règle 1** : avec les décisions retenues à M-1 (tout code >= 2 en M-1 place au CTX, sauf retard payé), les deux définitions retirent exactement les mêmes clients du ML. Effectifs, taux de défaut, faux positifs et population laissée au ML sont donc identiques. La définition 2 ne change que **la lecture de l'historique** des clients restés dans le ML.
- **Sortis / retards régularisés** : les clients sortis de la règle 1 se répartissent entre un vrai passage au CTX (au moins deux mois à >= 2) et un retard isolé régularisé. Les deux groupes ont un risque nettement différent, et dans chacun le risque baisse avec l'ancienneté du retour sous 2 : la distinction apporte une information utile au ML.
- **2 isolés en M-6** : classés comme passage au CTX par défaut, faute de visibilité sur M-7. Leur taux de défaut se situe **entre** celui attendu pour des retards régularisés à cette ancienneté et celui des sortis, plus près des régularisés : c'est vraisemblablement un mélange de vrais 2 isolés et de fins de séries commencées avant M-6. La décision est prudente et assumée ; elle n'est pas revue sur la base de `dpnm`.
- Par construction, il n'y a aucun retard régularisé avec un retour sous 2 en M-5 : ce retour correspondrait à un 2 isolé en M-6, classé comme passage au CTX.
- **Lien avec la règle 1** : la règle 1 ne distinguait pas les 2 isolés dans l'historique (tout 2 comptait comme passage au CTX). Elle avait en revanche déjà posé deux corrections reprises telles quelles : la neutralisation des faux codages et le **retard payé** à M-1, qui est l'équivalent au dernier mois du retard régularisé (un 2 non confirmé par les montants).

## 7. Validation unique sur le test
Cette section n'est exécutée qu'une fois la règle figée : le test ne doit pas servir à ajuster la règle.
Elle porte sur la définition retenue (définition 2, section 6), dont la population CTX est identique à celle de la règle 1.

In [129]:
final2_test = statut_ctx_regle2(df_test)

display(pd.DataFrame({
    'Train': validation(df_train, final2_train['STATUT_CTX'] == 'CTX'),
    'Test': validation(df_test, final2_test['STATUT_CTX'] == 'CTX'),
}).T.round(2).rename_axis('Statut CTX'))

,Nb clients,Part (%),Taux défaut périmètre (%),Défauts captés (%),Taux défaut reste (%)
Statut CTX,,,,,
Train,2435.0,11.19,70.14,35.75,15.88
Test,614.0,11.28,71.50,36.74,15.66

## 8. Indicateurs à reporter dans les notebooks ML
Définition retenue : **définition 2** (section 6). Fonctions à recopier telles quelles dans les notebooks ML : `corriger_faux_codage`, `recodage_pay1` (section 3) et `statut_ctx_regle2` (section 6).
- les clients `CTX` (`FLAG_CTX` = 1 et `MOIS_SORTIE_CTX` = -1) sont retirés du dataset ML et prédits en défaut par la règle,
- les autres clients (`Retard considéré régularisé M-1`, `Sorti`, `Retard régularisé`, `Jamais CTX`) restent dans le ML avec `PAY_1_recode`, `FLAG_CTX`, `MOIS_SORTIE_CTX`, `FLAG_RETARD`, `MOIS_SORTIE_RETARD` (0 = retard payé), `SURVEILLANCE_RECENTE` et `FAUX_CODAGE`.

In [130]:
final2 = statut_ctx_regle2(df)
print("Statut à M sur le périmètre S12 (définition 2) :")
display(final2['STATUT_CTX'].value_counts().rename_axis('Statut à M').to_frame('Nb clients'))

Statut à M sur le périmètre S12 (définition 2) :

                                 Nb clients
Statut à M
Jamais CTX                            19063
CTX                                    3049
Sorti                                  2657
Retard régularisé                      2251
Retard considéré régularisé M-1         182

## 9. Mise à l'épreuve sur le dataset initial (30 000 lignes)

La définition retenue (section 6) est appliquée au **dataset initial complet** `creditcard_pret_ingestion.csv` : 30 000 lignes, **aucun filtre**, codes PAY_n bruts (seul le nettoyage structurel de `EDUCATION` et `MARRIAGE` est appliqué).

On se compare au « monde réel » du dataset : que se passe-t-il si l'on retire la population présumée contentieuse du dataset de base ?
- quelle part des clients et des défauts part avec le CTX,
- quel taux de défaut reste dans le dataset sans le CTX.

*Ce n'est pas un test indépendant : le dataset initial contient le train sur lequel la règle a été construite.*

In [ ]:
df_initial = pd.read_csv(root_dir / "data" / "creditcard_pret_ingestion.csv")
final_initial = statut_ctx_regle2(df_initial)
ctx_initial = (final_initial['FLAG_CTX'] == 1) & (final_initial['MOIS_SORTIE_CTX'] == -1)

def bilan(d):
    return pd.Series({
        'Nb clients': len(d),
        'Part des clients (%)': len(d) / len(df_initial) * 100,
        'Nb défauts': int(d['dpnm'].sum()),
        'Part des défauts (%)': d['dpnm'].sum() / df_initial['dpnm'].sum() * 100,
        'Taux défaut (%)': d['dpnm'].mean() * 100,
    })

print("Retrait de la population présumée contentieuse (FLAG_CTX = 1 et MOIS_SORTIE_CTX = -1) :")
display(pd.DataFrame({
    'Dataset initial': bilan(df_initial),
    'CTX retiré': bilan(df_initial[ctx_initial]),
    'Dataset sans CTX': bilan(df_initial[~ctx_initial]),
}).T.round(2))

In [ ]:
print("Statuts à M sur le dataset initial :")
display(pd.DataFrame({s: bilan(df_initial[final_initial['STATUT_CTX'] == s]) for s in statuts_r2}).T.round(2)
        .rename_axis('Statut à M'))

**Interprétation**
- Retirer la population présumée contentieuse enlève une petite part des clients mais une part bien plus grande des défauts : le taux de défaut de cette population reste très élevé sur l'ensemble du dataset, du même ordre que sur le train et le test.
- Le dataset sans le CTX a un taux de défaut nettement plus bas que le dataset initial : c'est la population que le ML aura à traiter, plus homogène mais avec moins de signal.
- La gradation du risque entre les statuts (CTX, retard considéré régularisé M-1, sorti, retard régularisé, jamais CTX) est la même que sur le train.
- Contrepartie à assumer : une partie des clients retirés ne fera pas défaut mais sera prédite en défaut par la règle.

---
## Annexe : règles exploratoires
Règles testées avant la définition retenue en section 3. Elles sont conservées pour tracer le raisonnement.

### A.1 Règles candidates

Rappel des constats de l'EDA lab (dataset complet, avant filtrage) :
- 530 clients avec PAY_n = 2 sur les 6 mois (1.77 %) : la codification ne bouge pas, que le client paie ou non, et la dette augmente dans 87 % des mois sans paiement
- 393 « faux rétrogradages » (1.31 %) : passage de PAY_(n+1) > 2 à PAY_n = 2 sans aucun paiement et avec une dette positive
- 1 193 clients avec au moins un PAY_n > 2 (3.98 %)

Règles candidates, chacune justifiée par une définition métier :

| Règle | Définition | Logique métier |
|---|---|---|
| `R1_chronique` | PAY_n = 2 sur les 6 mois | codification figée, gestion hors circuit normal |
| `R2_faux_retrogradage` | ∃n : PAY_n = 2, PAY_(n+1) > 2, BILL_AMTn > 0, PAY_AMTn = 0 | amélioration du code sans paiement : le code 2 n'est plus un retard réel |
| `R3_actuelle` | R1 ou R2 | règle utilisée dans `S12_7` |
| `R4_retard_6m` | PAY_n >= 2 sur les 6 mois | retard sur toute la période observée (inclut R1) |
| `R5_retard_profond` | au moins un PAY_n > 2 sur les 6 mois | un seul retard d'au moins 3 mois suffit (inclut R2, qui exige un PAY_(n+1) > 2) |
| `R6_retard_continu` | PAY_n >= 2 sans interruption de M-1 jusqu'à M-k, avec 2 <= k <= 5 | retard installé depuis au moins 2 mois et toujours en cours à M-1 (6 mois = R4) |
| `R7_R1_R2_R4` | R1 ou R2 ou R4 | retard figé ou permanent sur la période, ou faux rétrogradage (R1 étant inclus dans R4, équivaut à R2 ou R4) |
| `R8_elargie` | R1 ou R2 ou R4 ou R5 ou R6 | toutes les situations de retard profond, figé ou installé |

**Règles bis (`_bis`)** : PAY_1 = 1, PAY_2 >= 2 et même règle appliquée sur la fenêtre PAY_2 à PAY_6.  
Les règles R1, R4 et R6 exigent un retard à M-1 et excluent donc mécaniquement les PAY_1 = 1, alors qu'un passage de >= 2 à 1 après un contentieux ne signifie pas forcément une sortie.  
Le paiement en M-1 ou en M-2 (le paiement ayant fait passer le code à 1 peut être enregistré le mois précédent) est analysé via le statut à M-1 (section 3.1).  
Pour `R6_retard_continu_bis`, la série continue part de M-2 (2 à 4 mois, 5 mois = `R4_retard_6m_bis`).

**Règles ter (`_ter`)** : même règle appliquée sur la fenêtre PAY_2 à PAY_6, **sans regarder PAY_1**, dont la fiabilité est douteuse (code 1 quasi exclusif à ce mois).  
Si une règle ter a un taux de défaut proche de sa version de base, PAY_1 n'apporte rien pour détecter le contentieux. La ventilation des clients ter selon leur PAY_1 (section 5) montre ce que ce mois apporte réellement.

In [131]:
# Les règles s'appliquent sur une fenêtre de mois :
# - règles de base : PAY_1 à PAY_6
# - règles bis : PAY_1 == 1, PAY_2 >= 2 et même règle appliquée sur PAY_2 à PAY_6
# - règles ter : même règle appliquée sur PAY_2 à PAY_6, PAY_1 ignoré (fiabilité douteuse)
mois_base = [1, 2, 3, 4, 5, 6]
mois_bis = [2, 3, 4, 5, 6]

def cols(mois):
    return [f'PAY_{n}' for n in mois]

def regle_R1(d, mois):
    return (d[cols(mois)] == 2).all(axis=1)

def regle_R2(d, mois):
    masque = pd.Series(False, index=d.index)
    for n in mois[:-1]:
        masque |= (
            (d[f'PAY_{n}'] == 2)
            & (d[f'PAY_{n+1}'] > 2)
            & (d[f'BILL_AMT{n}'] > 0)
            & (d[f'PAY_AMT{n}'] == 0)
        )
    return masque

def regle_R4(d, mois):
    return (d[cols(mois)] >= 2).all(axis=1)

def regle_R5(d, mois):
    return (d[cols(mois)] > 2).any(axis=1)

def regle_R6(d, mois):
    # Durée de la série continue de PAY_n >= 2 en partant du mois le plus récent de la fenêtre
    duree_retard_continu = (d[cols(mois)] >= 2).cumprod(axis=1).sum(axis=1)
    # Au moins 2 mois, fenêtre complète exclue (= R4)
    return duree_retard_continu.between(2, len(mois) - 1)

regles_base = {
    'R1_chronique': regle_R1,
    'R2_faux_retrogradage': regle_R2,
    'R3_actuelle': lambda d, mois: regle_R1(d, mois) | regle_R2(d, mois),
    'R4_retard_6m': regle_R4,
    'R5_retard_profond': regle_R5,
    'R6_retard_continu': regle_R6,
    'R7_R1_R2_R4': lambda d, mois: regle_R1(d, mois) | regle_R2(d, mois) | regle_R4(d, mois),
    'R8_elargie': lambda d, mois: (
        regle_R1(d, mois) | regle_R2(d, mois) | regle_R4(d, mois) | regle_R5(d, mois) | regle_R6(d, mois)
    ),
}

def condition_bis(d):
    return (d['PAY_1'] == 1) & (d['PAY_2'] >= 2)

regles = {}
for nom, f in regles_base.items():
    regles[nom] = lambda d, f=f: f(d, mois_base)
for nom, f in regles_base.items():
    regles[f'{nom}_bis'] = lambda d, f=f: condition_bis(d) & f(d, mois_bis)
for nom, f in regles_base.items():
    regles[f'{nom}_ter'] = lambda d, f=f: f(d, mois_bis)

masques_train = pd.DataFrame({nom: f(df_train) for nom, f in regles.items()})

### A.2 Statuts détaillés à M-1

Les règles détectent un **passage** au CTX sur la période, mais le client peut en être sorti depuis. Chaque client ayant au moins un PAY_n >= 2 reçoit un statut à M-1, à partir du **dernier mois où PAY_n >= 2**.  
Le paiement de régularisation est recherché **du dernier mois à >= 2 inclus jusqu'à M-1** (au moins 2 mois) : le paiement qui fait sortir du retard est souvent enregistré le mois précédant le changement de code.

| Statut | Définition | Traitement envisagé |
|---|---|---|
| `Maintien M-1` | PAY_1 >= 2 : le client est toujours en retard à M-1 | règle métier, prédit en défaut |
| `PAY_1=1 paiement M-1 ou M-2` | PAY_2 >= 2 puis PAY_1 = 1, avec un paiement en M-1 ou en M-2 (PAY_AMT1 > 0 ou PAY_AMT2 > 0) | le passage à 1 s'explique par un paiement |
| `PAY_1=1 sans paiement M-1 ni M-2` | PAY_2 >= 2 puis PAY_1 = 1, sans aucun paiement en M-1 ni en M-2 | passage à 1 inexpliqué : sortie non prouvée |
| `Sortie` | autres cas avec PAY_1 < 2 et au moins un paiement visible (PAY_AMTn > 0) du dernier mois à >= 2 jusqu'à M-1 | retour au ML avec un flag d'antériorité CTX |
| `Indéterminé` | autres cas avec PAY_1 < 2 sans aucun paiement visible du dernier mois à >= 2 jusqu'à M-1 | sortie non prouvée : à trancher |
| `Jamais >= 2` | aucun PAY_n >= 2 sur les 6 mois | hors sujet |

In [132]:
def statut_ctx(d):
    retard = (d[pay_cols] >= 2).values
    a_eu_retard = retard.any(axis=1)
    # Position du dernier mois à >= 2 (0 = M-1, 5 = M-6)
    rang_dernier_retard = retard.argmax(axis=1)
    # Mois de régularisation recherchés : du dernier mois à >= 2 inclus jusqu'à M-1
    # (le paiement qui fait sortir du retard est souvent enregistré le mois précédent le changement de code)
    mois_depuis = np.arange(6) <= rang_dernier_retard[:, None]
    paiement_depuis = ((d[pay_amt_cols].values > 0) & mois_depuis).any(axis=1)
    # Passage de PAY_2 >= 2 à PAY_1 = 1 : paiement en M-1 ou en M-2
    passage_2_vers_1 = condition_bis(d).values
    paiement_m1_m2 = (d['PAY_AMT1'].values > 0) | (d['PAY_AMT2'].values > 0)

    statut = np.select(
        [
            ~a_eu_retard,
            rang_dernier_retard == 0,
            passage_2_vers_1 & paiement_m1_m2,
            passage_2_vers_1,
            paiement_depuis,
        ],
        ['Jamais >= 2', 'Maintien M-1', 'PAY_1=1 paiement M-1 ou M-2', 'PAY_1=1 sans paiement M-1 ni M-2', 'Sortie'],
        default='Indéterminé',
    )
    return pd.Series(statut, index=d.index)

statuts = ['Maintien M-1', 'PAY_1=1 paiement M-1 ou M-2', 'PAY_1=1 sans paiement M-1 ni M-2', 'Sortie', 'Indéterminé']
statut_train = statut_ctx(df_train)
print(statut_train.value_counts())

Jamais >= 2                         15193
Sortie                               2532
Maintien M-1                         2486
PAY_1=1 paiement M-1 ou M-2          1390
PAY_1=1 sans paiement M-1 ni M-2       84
Indéterminé                            76
Name: count, dtype: int64

### A.3 Description des règles (sans la cible)

In [133]:
volumes = pd.DataFrame({
    'Nb clients': masques_train.sum(),
    'Part train (%)': (masques_train.mean() * 100).round(2),
}).rename_axis('Règle')
display(volumes)

# Recouvrement : part des clients de la règle en ligne également captés par la règle en colonne
recouvrement = pd.DataFrame(
    {c: [(masques_train[l] & masques_train[c]).sum() / max(masques_train[l].sum(), 1) * 100 for l in regles] for c in regles},
    index=list(regles),
).round(1).rename_axis('Règle (ligne) captée par ->')
print("Recouvrement (% des clients de la ligne captés par la colonne) :")
display(recouvrement)

                          Nb clients  Part train (%)
Règle
R1_chronique                     424            1.95
R2_faux_retrogradage             318            1.46
R3_actuelle                      742            3.41
R4_retard_6m                     756            3.47
R5_retard_profond                949            4.36
R6_retard_continu                951            4.37
R7_R1_R2_R4                      896            4.12
R8_elargie                      2088            9.60
R1_chronique_bis                 232            1.07
R2_faux_retrogradage_bis          68            0.31
R3_actuelle_bis                  300            1.38
R4_retard_6m_bis                 338            1.55
R5_retard_profond_bis            201            0.92
R6_retard_continu_bis            485            2.23
R7_R1_R2_R4_bis                  357            1.64
R8_elargie_bis                   835            3.84
R1_chronique_ter                 706            3.24
R2_faux_retrogradage_ter         281            1.29
R3_actuelle_ter                  987            4.54
R4_retard_6m_ter                1116            5.13
R5_retard_profond_ter            798            3.67
R6_retard_continu_ter           1258            5.78
R7_R1_R2_R4_ter                 1181            5.43
R8_elargie_ter                  2525           11.60

Recouvrement (% des clients de la ligne captés par la colonne) :

,R1_chronique,R2_faux_retrogradage,R3_actuelle,R4_retard_6m,R5_retard_profond,R6_retard_continu,R7_R1_R2_R4,R8_elargie,R1_chronique_bis,R2_faux_retrogradage_bis,...,R7_R1_R2_R4_bis,R8_elargie_bis,R1_chronique_ter,R2_faux_retrogradage_ter,R3_actuelle_ter,R4_retard_6m_ter,R5_retard_profond_ter,R6_retard_continu_ter,R7_R1_R2_R4_ter,R8_elargie_ter
Règle (ligne) captée par ->,,,,,,,,,,,,,,,,,,,,,
R1_chronique,100.0,0.0,100.0,100.0,0.0,0.0,100.0,100.0,0.0,0.0,...,0.0,0.0,100.0,0.0,100.0,100.0,0.0,0.0,100.0,100.0
R2_faux_retrogradage,0.0,100.0,100.0,56.0,100.0,11.0,100.0,100.0,0.0,21.4,...,21.4,21.4,0.0,88.4,88.4,72.3,100.0,16.4,92.8,100.0
R3_actuelle,57.1,42.9,100.0,81.1,42.9,4.7,100.0,100.0,0.0,9.2,...,9.2,9.2,57.1,37.9,95.0,88.1,42.9,7.0,96.9,100.0
R4_retard_6m,56.1,23.5,79.6,100.0,43.9,0.0,100.0,100.0,0.0,0.0,...,0.0,0.0,61.2,21.7,82.9,100.0,38.8,0.0,100.0,100.0
R5_retard_profond,0.0,33.5,33.5,35.0,100.0,24.9,49.7,100.0,0.0,7.2,...,13.2,21.2,4.1,29.6,33.7,47.3,84.1,31.8,54.2,95.0
R6_retard_continu,0.0,3.7,3.7,0.0,24.8,100.0,3.7,100.0,0.0,0.0,...,0.0,0.0,0.0,1.3,1.3,0.0,13.0,66.8,1.3,67.4
R7_R1_R2_R4,47.3,35.5,82.8,84.4,52.7,3.9,100.0,100.0,0.0,7.6,...,7.6,7.6,51.7,31.4,83.0,90.2,48.3,5.8,97.4,100.0
R8_elargie,20.3,15.2,35.5,36.2,45.5,45.5,42.9,100.0,0.0,3.3,...,6.0,9.6,22.2,13.5,35.6,41.8,38.2,36.1,44.9,85.2
R1_chronique_bis,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,100.0,0.0,...,100.0,100.0,100.0,0.0,100.0,100.0,0.0,0.0,100.0,100.0
R2_faux_retrogradage_bis,0.0,100.0,100.0,0.0,100.0,0.0,100.0,100.0,0.0,100.0,...,100.0,100.0,0.0,100.0,100.0,72.1,100.0,26.5,100.0,100.0
R3_actuelle_bis,0.0,22.7,22.7,0.0,22.7,0.0,22.7,22.7,77.3,22.7,...,100.0,100.0,77.3,22.7,100.0,93.7,22.7,6.0,100.0,100.0
R4_retard_6m_bis,0.0,14.5,14.5,0.0,31.4,0.0,14.5,31.4,68.6,14.5,...,100.0,100.0,68.6,14.5,83.1,100.0,31.4,0.0,100.0,100.0
R5_retard_profond_bis,0.0,33.8,33.8,0.0,100.0,0.0,33.8,100.0,0.0,33.8,...,62.2,100.0,0.0,33.8,33.8,52.7,100.0,41.3,62.2,100.0
R6_retard_continu_bis,0.0,3.7,3.7,0.0,17.1,0.0,3.7,17.1,0.0,3.7,...,3.7,100.0,0.0,3.7,3.7,0.0,17.1,100.0,3.7,100.0
R7_R1_R2_R4_bis,0.0,19.0,19.0,0.0,35.0,0.0,19.0,35.0,65.0,19.0,...,100.0,100.0,65.0,19.0,84.0,94.7,35.0,5.0,100.0,100.0
R8_elargie_bis,0.0,8.1,8.1,0.0,24.1,0.0,8.1,24.1,27.8,8.1,...,42.8,100.0,27.8,8.1,35.9,40.5,24.1,58.1,42.8,100.0
R1_chronique_ter,60.1,0.0,60.1,65.6,5.5,0.0,65.6,65.6,32.9,0.0,...,32.9,32.9,100.0,0.0,100.0,100.0,0.0,0.0,100.0,100.0
R2_faux_retrogradage_ter,0.0,100.0,100.0,58.4,100.0,4.3,100.0,100.0,0.0,24.2,...,24.2,24.2,0.0,100.0,100.0,76.9,100.0,10.3,100.0,100.0
R3_actuelle_ter,43.0,28.5,71.4,63.5,32.4,1.2,75.4,75.4,23.5,6.9,...,30.4,30.4,71.5,28.5,100.0,93.4,28.5,2.9,100.0,100.0
R4_retard_6m_ter,38.0,20.6,58.6,67.7,40.2,0.0,72.4,78.2,20.8,4.4,...,30.3,30.3,63.3,19.4,82.6,100.0,36.7,0.0,100.0,100.0
R5_retard_profond_ter,0.0,39.8,39.8,36.7,100.0,15.5,54.3,100.0,0.0,8.5,...,15.7,25.2,0.0,35.2,35.2,51.4,100.0,29.7,59.5,100.0
R6_retard_continu_ter,0.0,4.1,4.1,0.0,24.0,50.5,4.1,59.9,0.0,1.4,...,1.4,38.6,0.0,2.3,2.3,0.0,18.8,100.0,2.3,100.0
R7_R1_R2_R4_ter,35.9,25.0,60.9,64.0,43.5,1.0,73.9,79.4,19.6,5.8,...,30.2,30.2,59.8,23.8,83.6,94.5,40.2,2.5,100.0,100.0
R8_elargie_ter,16.8,12.6,29.4,29.9,35.7,25.4,35.5,70.4,9.2,2.7,...,14.1,33.1,28.0,11.1,39.1,44.2,31.6,49.8,46.8,100.0

In [134]:
# Ventilation de chaque règle par statut à M-1
ventilation_statut = pd.DataFrame(
    {s: [(masques_train[nom] & (statut_train == s)).sum() for nom in regles] for s in statuts},
    index=list(regles),
).rename_axis('Règle')
print("Ventilation des clients de chaque règle par statut à M-1 :")
display(ventilation_statut)

Ventilation des clients de chaque règle par statut à M-1 :

,Maintien M-1,PAY_1=1 paiement M-1 ou M-2,PAY_1=1 sans paiement M-1 ni M-2,Sortie,Indéterminé
Règle,,,,,
R1_chronique,424,0,0,0,0
R2_faux_retrogradage,215,65,3,34,1
R3_actuelle,639,65,3,34,1
R4_retard_6m,756,0,0,0,0
R5_retard_profond,579,140,61,134,35
R6_retard_continu,951,0,0,0,0
R7_R1_R2_R4,793,65,3,34,1
R8_elargie,1718,140,61,134,35
R1_chronique_bis,0,231,1,0,0
R2_faux_retrogradage_bis,0,65,3,0,0
R3_actuelle_bis,0,296,4,0,0
R4_retard_6m_bis,0,309,29,0,0
R5_retard_profond_bis,0,140,61,0,0
R6_retard_continu_bis,0,430,55,0,0
R7_R1_R2_R4_bis,0,328,29,0,0
R8_elargie_bis,0,751,84,0,0
R1_chronique_ter,463,231,1,10,1
R2_faux_retrogradage_ter,178,65,3,34,1
R3_actuelle_ter,641,296,4,44,2
R4_retard_6m_ter,756,309,29,14,8
R5_retard_profond_ter,428,140,61,134,35
R6_retard_continu_ter,635,430,55,71,67
R7_R1_R2_R4_ter,770,328,29,46,8
R8_elargie_ter,1408,751,84,207,75

In [135]:
profils = {nom: profil_comportement(df_train[masques_train[nom]]) for nom in regles}
tous_ctx = masques_train.any(axis=1)
profils['Hors toutes règles'] = profil_comportement(df_train[~tous_ctx])
display(pd.DataFrame(profils).T.round(1).rename_axis('Règle'))

,Nb clients,Mois sans paiement (moy.),% avec 6 mois sans paiement,% dette en hausse M-6 -> M-1,Utilisation plafond M-1 (médiane %),LIMIT_BAL (médiane)
Règle,,,,,,
R1_chronique,424.0,1.4,2.8,13.7,66.6,90000.0
R2_faux_retrogradage,318.0,3.7,27.4,17.3,47.7,30000.0
R3_actuelle,742.0,2.4,13.3,15.2,60.7,60000.0
R4_retard_6m,756.0,2.4,16.1,17.5,63.8,70000.0
R5_retard_profond,949.0,2.9,13.0,36.6,66.4,50000.0
R6_retard_continu,951.0,1.7,3.6,57.2,80.9,70000.0
R7_R1_R2_R4,896.0,2.4,13.6,17.5,63.8,60000.0
R8_elargie,2088.0,2.1,7.8,38.5,70.1,60000.0
R1_chronique_bis,232.0,2.0,0.4,12.5,58.9,70000.0
R2_faux_retrogradage_bis,68.0,2.9,0.0,16.2,72.6,30000.0
R3_actuelle_bis,300.0,2.2,0.3,13.3,60.7,50000.0
R4_retard_6m_bis,338.0,2.3,0.9,16.3,62.7,50000.0
R5_retard_profond_bis,201.0,2.9,2.5,39.3,77.4,40000.0
R6_retard_continu_bis,485.0,2.0,3.5,56.1,71.9,50000.0
R7_R1_R2_R4_bis,357.0,2.3,0.8,16.8,64.2,50000.0
R8_elargie_bis,835.0,2.1,2.4,39.4,67.4,50000.0
R1_chronique_ter,706.0,1.7,3.7,13.2,63.4,80000.0
R2_faux_retrogradage_ter,281.0,3.8,31.0,16.4,43.6,30000.0
R3_actuelle_ter,987.0,2.3,11.4,14.1,59.4,60000.0
R4_retard_6m_ter,1116.0,2.4,11.4,17.5,63.0,60000.0
R5_retard_profond_ter,798.0,3.0,13.4,34.5,65.3,50000.0
R6_retard_continu_ter,1258.0,2.0,3.6,55.6,68.2,60000.0
R7_R1_R2_R4_ter,1181.0,2.4,10.8,17.4,63.0,60000.0
R8_elargie_ter,2525.0,2.2,6.8,36.3,64.0,60000.0
Hors toutes règles,18926.0,0.8,1.4,64.0,35.2,150000.0

In [136]:
# Comportement par statut à M-1, sur l'ensemble des clients ayant eu au moins un PAY_n >= 2
profils_statut = {s: profil_comportement(df_train[statut_train == s]) for s in statuts}
profils_statut['Jamais >= 2'] = profil_comportement(df_train[statut_train == 'Jamais >= 2'])
display(pd.DataFrame(profils_statut).T.round(1).rename_axis('Statut à M-1'))

,Nb clients,Mois sans paiement (moy.),% avec 6 mois sans paiement,% dette en hausse M-6 -> M-1,Utilisation plafond M-1 (médiane %),LIMIT_BAL (médiane)
Statut à M-1,,,,,,
Maintien M-1,2486.0,1.6,6.3,44.6,72.6,80000.0
PAY_1=1 paiement M-1 ou M-2,1390.0,1.7,0.0,48.8,69.7,60000.0
PAY_1=1 sans paiement M-1 ni M-2,84.0,4.1,23.8,78.6,65.5,30000.0
Sortie,2532.0,1.4,0.0,45.5,39.4,90000.0
Indéterminé,76.0,4.2,26.3,72.4,1.3,120000.0
Jamais >= 2,15193.0,0.7,1.7,67.0,29.8,160000.0

### A.4 Validation des règles sur le train

In [137]:
display(pd.DataFrame({nom: validation(df_train, masques_train[nom]) for nom in regles}).T.round(2).rename_axis('Règle'))

,Nb clients,Part (%),Taux défaut périmètre (%),Défauts captés (%),Taux défaut reste (%)
Règle,,,,,
R1_chronique,424.0,1.95,79.01,7.01,20.82
R2_faux_retrogradage,318.0,1.46,67.61,4.50,21.28
R3_actuelle,742.0,3.41,74.12,11.51,20.11
R4_retard_6m,756.0,3.47,78.04,12.35,19.93
R5_retard_profond,949.0,4.36,62.49,12.41,20.10
R6_retard_continu,951.0,4.37,65.40,13.02,19.97
R7_R1_R2_R4,896.0,4.12,74.44,13.96,19.70
R8_elargie,2088.0,9.60,67.39,29.45,17.13
R1_chronique_bis,232.0,1.07,53.88,2.62,21.61
R2_faux_retrogradage_bis,68.0,0.31,58.82,0.84,21.84
R3_actuelle_bis,300.0,1.38,55.00,3.45,21.49
R4_retard_6m_bis,338.0,1.55,53.85,3.81,21.45
R5_retard_profond_bis,201.0,0.92,55.72,2.34,21.64
R6_retard_continu_bis,485.0,2.23,44.33,4.50,21.44
R7_R1_R2_R4_bis,357.0,1.64,54.06,4.04,21.42
R8_elargie_bis,835.0,3.84,48.86,8.54,20.88
R1_chronique_ter,706.0,3.24,70.68,10.45,20.32
R2_faux_retrogradage_ter,281.0,1.29,69.40,4.08,21.33
R3_actuelle_ter,987.0,4.54,70.31,14.53,19.65
R4_retard_6m_ter,1116.0,5.13,70.16,16.39,19.35
R5_retard_profond_ter,798.0,3.67,61.28,10.24,20.46
R6_retard_continu_ter,1258.0,5.78,55.01,14.49,19.92
R7_R1_R2_R4_ter,1181.0,5.43,69.26,17.12,19.24
R8_elargie_ter,2525.0,11.60,61.27,32.38,16.79

In [138]:
# Taux de défaut de chaque règle ventilé par statut à M-1
taux_statut = pd.DataFrame(
    {s: [df_train.loc[masques_train[nom] & (statut_train == s), 'dpnm'].mean() * 100 for nom in regles] for s in statuts},
    index=list(regles),
).round(2).rename_axis('Règle')
print("Taux de défaut (%) des clients de chaque règle, par statut à M-1 :")
display(taux_statut)

print("Validation par statut, tous clients ayant eu au moins un PAY_n >= 2 :")
display(pd.DataFrame({s: validation(df_train, statut_train == s) for s in statuts}).T.round(2).rename_axis('Statut à M-1'))

Taux de défaut (%) des clients de chaque règle, par statut à M-1 :

,Maintien M-1,PAY_1=1 paiement M-1 ou M-2,PAY_1=1 sans paiement M-1 ni M-2,Sortie,Indéterminé
Règle,,,,,
R1_chronique,79.01,NaN,NaN,NaN,NaN
R2_faux_retrogradage,73.02,56.92,100.00,52.94,0.00
R3_actuelle,77.00,56.92,100.00,52.94,0.00
R4_retard_6m,78.04,NaN,NaN,NaN,NaN
R5_retard_profond,70.12,58.57,49.18,41.79,54.29
R6_retard_continu,65.40,NaN,NaN,NaN,NaN
R7_R1_R2_R4,76.80,56.92,100.00,52.94,0.00
R8_elargie,71.01,58.57,49.18,41.79,54.29
R1_chronique_bis,NaN,53.68,100.00,NaN,NaN
R2_faux_retrogradage_bis,NaN,56.92,100.00,NaN,NaN
R3_actuelle_bis,NaN,54.39,100.00,NaN,NaN
R4_retard_6m_bis,NaN,53.72,55.17,NaN,NaN
R5_retard_profond_bis,NaN,58.57,49.18,NaN,NaN
R6_retard_continu_bis,NaN,43.95,47.27,NaN,NaN
R7_R1_R2_R4_bis,NaN,53.96,55.17,NaN,NaN
R8_elargie_bis,NaN,48.74,50.00,NaN,NaN
R1_chronique_ter,80.13,53.68,100.00,30.00,0.00
R2_faux_retrogradage_ter,76.97,56.92,100.00,52.94,0.00
R3_actuelle_ter,79.25,54.39,100.00,47.73,0.00
R4_retard_6m_ter,78.04,53.72,55.17,50.00,50.00
R5_retard_profond_ter,70.56,58.57,49.18,41.79,54.29
R6_retard_continu_ter,67.09,43.95,47.27,35.21,38.81
R7_R1_R2_R4_ter,77.66,53.96,55.17,50.00,50.00
R8_elargie_ter,73.15,48.74,50.00,38.16,40.00

Validation par statut, tous clients ayant eu au moins un PAY_n >= 2 :

,Nb clients,Part (%),Taux défaut périmètre (%),Défauts captés (%),Taux défaut reste (%)
Statut à M-1,,,,,
Maintien M-1,2486.0,11.42,69.15,35.98,15.87
PAY_1=1 paiement M-1 ou M-2,1390.0,6.39,41.51,12.08,20.62
PAY_1=1 sans paiement M-1 ni M-2,84.0,0.39,50.00,0.88,21.84
Sortie,2532.0,11.64,26.26,13.92,21.38
Indéterminé,76.0,0.35,39.47,0.63,21.89

In [139]:
# Synthèse compacte : base / bis / ter côte à côte pour chaque règle
synthese = pd.DataFrame({
    (version, indicateur): [
        (masques_train[nom + suffixe].sum() if indicateur == 'Nb clients'
         else df_train.loc[masques_train[nom + suffixe], 'dpnm'].mean() * 100)
        for nom in regles_base
    ]
    for version, suffixe in [('Base', ''), ('Bis', '_bis'), ('Ter', '_ter')]
    for indicateur in ['Nb clients', 'Taux défaut (%)']
}, index=list(regles_base)).round(1).rename_axis('Règle')
print("Synthèse base / bis / ter :")
display(synthese)

# Règles ter ventilées selon PAY_1 : ce que M-1 apporte réellement
categorie_pay1 = pd.cut(df_train['PAY_1'], bins=[-3, 0, 1, 9], labels=['PAY_1 <= 0', 'PAY_1 = 1', 'PAY_1 >= 2'])
ter_par_pay1 = pd.DataFrame({
    (cat, indicateur): [
        ((masques_train[nom + '_ter']) & (categorie_pay1 == cat)).sum() if indicateur == 'Nb clients'
        else df_train.loc[masques_train[nom + '_ter'] & (categorie_pay1 == cat), 'dpnm'].mean() * 100
        for nom in regles_base
    ]
    for cat in ['PAY_1 >= 2', 'PAY_1 = 1', 'PAY_1 <= 0']
    for indicateur in ['Nb clients', 'Taux défaut (%)']
}, index=list(regles_base)).round(1).rename_axis('Règle ter')
print("Règles ter ventilées selon la valeur de PAY_1 :")
display(ter_par_pay1)

Synthèse base / bis / ter :

                           Base                        Bis                  \
                     Nb clients Taux défaut (%) Nb clients Taux défaut (%)
Règle
R1_chronique                424            79.0        232            53.9
R2_faux_retrogradage        318            67.6         68            58.8
R3_actuelle                 742            74.1        300            55.0
R4_retard_6m                756            78.0        338            53.8
R5_retard_profond           949            62.5        201            55.7
R6_retard_continu           951            65.4        485            44.3
R7_R1_R2_R4                 896            74.4        357            54.1
R8_elargie                 2088            67.4        835            48.9

                            Ter
                     Nb clients Taux défaut (%)
Règle
R1_chronique                706            70.7
R2_faux_retrogradage        281            69.4
R3_actuelle                 987            70.3
R4_retard_6m               1116            70.2
R5_retard_profond           798            61.3
R6_retard_continu          1258            55.0
R7_R1_R2_R4                1181            69.3
R8_elargie                 2525            61.3

Règles ter ventilées selon la valeur de PAY_1 :

                     PAY_1 >= 2                  PAY_1 = 1                  \
                     Nb clients Taux défaut (%) Nb clients Taux défaut (%)
Règle ter
R1_chronique                463            80.1        232            53.9
R2_faux_retrogradage        178            77.0         68            58.8
R3_actuelle                 641            79.3        300            55.0
R4_retard_6m                756            78.0        338            53.8
R5_retard_profond           428            70.6        201            55.7
R6_retard_continu           635            67.1        485            44.3
R7_R1_R2_R4                 770            77.7        357            54.1
R8_elargie                 1408            73.2        835            48.9

                     PAY_1 <= 0
                     Nb clients Taux défaut (%)
Règle ter
R1_chronique                 11            27.3
R2_faux_retrogradage         35            51.4
R3_actuelle                  46            45.7
R4_retard_6m                 22            50.0
R5_retard_profond           169            44.4
R6_retard_continu           138            37.0
R7_R1_R2_R4                  54            50.0
R8_elargie                  282            38.7